// BrightSprouts Academy — Social Studies rebuilt to the standard US scope and sequence.
// G1–2 self/family/community · G3 community & Native nations · G4 state & regions ·
// G5 US HISTORY I (colonies → Constitution) · G6 ancient civilizations · G7 world history ·
// G8 US HISTORY II (new nation → Reconstruction) · G9–10 world history · G11 US HISTORY III ·
// G12 Government, Civics & Economics.
// Three units per grade, each with its own activity and worksheet bank.
(function () {
  if (typeof LESSONS === "undefined") return;
  function U(emoji, title, intro, learn, activity, questions) {
    return { emoji: emoji, title: title, intro: intro, learn: learn, activity: activity, questions: questions };
  }

  var H = {};

  H[1] = [
    U("👨‍👩‍👧", "Me, My Family & My School",
      "Social studies starts with you! Your family, your school and the people around you all have a story.",
      ["A family can look many different ways, and every kind is a real family.",
       "A timeline puts events in the order they happened — you can make one of your own life.",
       "The past is what already happened, the present is now, and the future is still to come.",
       "Rules at home and at school keep everybody safe and fair.",
       "Everyone in a group has both rights (what they should get) and responsibilities (what they should do)."],
      "🖼️ Activity Sheet — My Timeline: Draw four pictures of your life in order: being a baby, learning to walk, starting school, and today. Label each one.",
      [{ q: "What do we call the time that already happened?", a: "The past" },
       { q: "What do we call right now?", a: "The present" },
       { q: "What is a timeline?", a: "A line that shows events in the order they happened" },
       { q: "Why do we have rules at school?", a: "To keep everyone safe and fair" },
       { q: "Name one responsibility you have at home.", a: "e.g. tidying up, feeding a pet, being kind" },
       { q: "Do all families look the same?", a: "No — families come in many shapes" },
       { q: "What comes after the present?", a: "The future" },
       { q: "Name one person who helps at your school.", a: "e.g. a teacher, nurse, cook, custodian" }]),
    U("🇺🇸", "American Symbols & Holidays",
      "Some flags, songs and buildings stand for the whole country. Let's meet the symbols of the United States.",
      ["The American flag has 50 stars for the 50 states and 13 stripes for the first 13 colonies.",
       "The bald eagle is the national bird and a symbol of the United States.",
       "The Statue of Liberty in New York Harbor was a gift from France and welcomes people to America.",
       "Independence Day is the Fourth of July — the country's birthday.",
       "The Pledge of Allegiance is a promise people make to the flag and the country."],
      "🇺🇸 Activity Sheet — Draw the Flag: Draw the American flag and count out 13 stripes. Colour them, then write one sentence about what the stars stand for.",
      [{ q: "How many stars are on the American flag?", a: "50" },
       { q: "What do the 50 stars stand for?", a: "The 50 states" },
       { q: "How many stripes does the flag have?", a: "13" },
       { q: "What do the 13 stripes stand for?", a: "The first 13 colonies" },
       { q: "What is the national bird of the United States?", a: "The bald eagle" },
       { q: "Which country gave the Statue of Liberty to America?", a: "France" },
       { q: "What holiday is on the Fourth of July?", a: "Independence Day" },
       { q: "What do we call the promise made to the flag?", a: "The Pledge of Allegiance" }]),
    U("🗺️", "Maps of My World",
      "A map is a picture of a place from above. Learning to read one helps you find your way anywhere.",
      ["A map shows a place from above, as a bird would see it.",
       "A globe is a map on a ball, showing the whole round Earth.",
       "The four main directions are north, south, east and west.",
       "A map key (or legend) explains what the little pictures and colours mean.",
       "You live in a home, in a town, in a state, in a country — each one inside the next."],
      "🗺️ Activity Sheet — Map My Room: Draw your bedroom from above. Add a key showing what each shape means, and mark north with an arrow.",
      [{ q: "What is a map?", a: "A picture of a place seen from above" },
       { q: "What is a globe?", a: "A map of the whole Earth on a ball" },
       { q: "Name the four main directions.", a: "North, south, east and west" },
       { q: "What does a map key tell you?", a: "What the symbols and colours mean" },
       { q: "Which is bigger: your town or your state?", a: "Your state" },
       { q: "Which is bigger: your state or your country?", a: "Your country" },
       { q: "What country do you live in?", a: "The United States of America" },
       { q: "Which direction is the opposite of north?", a: "South" }])
  ];

  H[2] = [
    U("🏘️", "Communities & the People Who Help",
      "A community is a group of people who live and work in the same place — and it only works because everyone pitches in.",
      ["A community is a place where people live, work and help each other.",
       "Communities can be urban (a city), suburban (near a city) or rural (in the countryside).",
       "Community helpers include firefighters, nurses, teachers, farmers, mail carriers and police officers.",
       "People pay taxes, and that money pays for shared things like schools, parks, roads and libraries.",
       "Goods are things you can buy; services are jobs people do for you."],
      "🏘️ Activity Sheet — Helper Interview: Choose one community helper. Write three questions you would ask them, then draw them doing their job.",
      [{ q: "What is a community?", a: "A place where people live, work and help each other" },
       { q: "Name the three kinds of community.", a: "Urban, suburban and rural" },
       { q: "Which kind of community is a big city?", a: "Urban" },
       { q: "Which kind of community is out in the countryside?", a: "Rural" },
       { q: "Name two community helpers.", a: "e.g. firefighter, nurse, teacher, farmer" },
       { q: "What pays for schools, parks and roads?", a: "Taxes" },
       { q: "Is a haircut a good or a service?", a: "A service" },
       { q: "Is an apple a good or a service?", a: "A good" }]),
    U("⏳", "Long Ago & Today",
      "Life used to look very different. Comparing then and now shows how much has changed — and how much has not.",
      ["Long ago there were no cars, phones or electricity in most homes.",
       "People travelled by foot, horse or wagon, and news took weeks to arrive.",
       "Inventions changed daily life: the light bulb, the telephone, the automobile and the computer.",
       "Some things have not changed at all — families, friendship, school and play.",
       "We learn about long ago from artifacts, photographs, and stories from older people."],
      "⏳ Activity Sheet — Then & Now: Fold a page in half. Draw a kitchen from 100 years ago on one side and today's on the other. List three differences.",
      [{ q: "How did people travel before cars?", a: "On foot, by horse, or by wagon" },
       { q: "Name an invention that changed everyday life.", a: "e.g. the light bulb, telephone, car, computer" },
       { q: "What is an artifact?", a: "An object from the past that teaches us about it" },
       { q: "Name something that has NOT changed over time.", a: "Families, friendship, school or play" },
       { q: "Who can tell you stories about long ago?", a: "Older people, like grandparents" },
       { q: "Did homes long ago have electricity?", a: "Most did not" },
       { q: "How long did news take to travel long ago?", a: "Days or weeks" },
       { q: "Name a way we learn about the past.", a: "Artifacts, photographs and stories" }]),
    U("🦃", "Holidays & Where We Came From",
      "American holidays remember people and events that shaped the country — and nearly every family here came from somewhere else.",
      ["Thanksgiving remembers a 1621 harvest meal shared by the Pilgrims and the Wampanoag people.",
       "Martin Luther King Jr. Day honours a leader who worked for equal rights for Black Americans.",
       "Presidents' Day honours George Washington, the first president, and other presidents.",
       "Memorial Day remembers people who died serving in the military; Veterans Day honours all who served.",
       "An immigrant is someone who moves to a new country. The United States is made up of people from all over the world, plus Native peoples who were here first."],
      "🦃 Activity Sheet — Family Roots: Ask your family where your relatives came from. Mark those places on a world map and draw one thing your family does that came with them.",
      [{ q: "Which two groups shared the 1621 harvest meal?", a: "The Pilgrims and the Wampanoag" },
       { q: "Who was the first president of the United States?", a: "George Washington" },
       { q: "What did Martin Luther King Jr. work for?", a: "Equal rights for Black Americans" },
       { q: "What is an immigrant?", a: "Someone who moves to a new country" },
       { q: "Who lived in America before settlers arrived?", a: "Native American peoples" },
       { q: "What does Veterans Day honour?", a: "Everyone who served in the military" },
       { q: "What does Memorial Day remember?", a: "Those who died serving in the military" },
       { q: "Name a holiday that honours presidents.", a: "Presidents' Day" }])
  ];

  H[3] = [
    U("🏛️", "My Community & Its Government",
      "Every town has rules and leaders. Local government is the part of government closest to your own front door.",
      ["A local government runs a town or city, led by a mayor and a city council.",
       "Citizens vote to choose their leaders — that is called an election.",
       "Laws are rules made by a government, and everyone must follow them.",
       "Local government provides services: schools, police, firefighters, libraries, parks and rubbish collection.",
       "The three levels of government in the US are local, state and national (federal)."],
      "🏛️ Activity Sheet — Town Plan: Design your own town on paper. Add a school, a fire station, a park and a library, then write one rule your town would have.",
      [{ q: "Who leads a city government?", a: "A mayor" },
       { q: "What do we call choosing leaders by voting?", a: "An election" },
       { q: "What is a law?", a: "A rule made by a government" },
       { q: "Name the three levels of US government.", a: "Local, state and national (federal)" },
       { q: "Name two services local government provides.", a: "e.g. schools, police, libraries, parks" },
       { q: "What is a citizen?", a: "A member of a country with rights and responsibilities" },
       { q: "Who makes decisions with the mayor?", a: "The city council" },
       { q: "Why do communities need laws?", a: "To keep people safe and treat everyone fairly" }]),
    U("🪶", "Native Nations of North America",
      "Long before any ships arrived, hundreds of nations already lived across this land, each with its own language and way of life.",
      ["Native Americans were the first peoples of North America, living here for thousands of years.",
       "There were — and still are — hundreds of separate nations, each with its own language, government and traditions.",
       "People lived differently depending on their region: buffalo hunting on the Plains, fishing and cedar houses in the Northwest, farming in the Southeast.",
       "Many nations farmed the 'three sisters' together: corn, beans and squash.",
       "Native nations are still here today, with their own governments, languages and cultures."],
      "🪶 Activity Sheet — Three Sisters: Draw corn, beans and squash growing together and write why planting them side by side helps each one.",
      [{ q: "Who were the first peoples of North America?", a: "Native Americans" },
       { q: "Were all Native nations the same?", a: "No — hundreds of nations, each different" },
       { q: "What are the 'three sisters'?", a: "Corn, beans and squash" },
       { q: "What animal did Plains nations depend on?", a: "The buffalo (bison)" },
       { q: "Do Native nations still exist today?", a: "Yes" },
       { q: "How did the land shape how people lived?", a: "It decided what they could hunt, fish or farm" },
       { q: "About how long have Native peoples lived here?", a: "Thousands of years" },
       { q: "Did Native nations have their own governments?", a: "Yes" }]),
    U("🌍", "Communities Around the World",
      "Children go to school in every country on Earth — but daily life can look wonderfully different.",
      ["Culture means the language, food, clothing, music and traditions a group of people share.",
       "Geography shapes culture: people build, dress and eat according to their climate and land.",
       "Most communities everywhere have the same basic needs: food, water, shelter, schools and safety.",
       "Trade means exchanging goods between people or countries, so we use things from all over the world.",
       "Learning about other cultures builds respect for people who live differently from you."],
      "🌍 Activity Sheet — Passport Page: Pick a country. Draw its flag, one traditional food, and one thing children there do that you also do.",
      [{ q: "What does culture mean?", a: "The language, food, clothing and traditions people share" },
       { q: "Name something every community needs.", a: "Food, water, shelter, schools or safety" },
       { q: "What is trade?", a: "Exchanging goods between people or countries" },
       { q: "How does climate change how people dress?", a: "They wear what suits hot or cold weather" },
       { q: "Do children go to school in other countries?", a: "Yes, all over the world" },
       { q: "Why learn about other cultures?", a: "To understand and respect other people" },
       { q: "Name something that is part of culture.", a: "Language, food, music, clothing or traditions" },
       { q: "Does geography affect what people eat?", a: "Yes — it decides what can be grown or caught" }])
  ];

  H[4] = [
    U("🗺️", "The Five Regions of the United States",
      "The United States is huge, and it changes as you cross it. Geographers split it into five regions.",
      ["The five regions are the Northeast, Southeast, Midwest, Southwest and West.",
       "The Northeast has big cities and the earliest colonies; the Southeast is warm with a long coastline.",
       "The Midwest is flat farmland — often called the nation's breadbasket.",
       "The Southwest is dry desert and canyons; the West has mountains, forests and the Pacific coast.",
       "Landforms and climate decide what people grow, build and do for work in each region."],
      "🗺️ Activity Sheet — Region Map: Draw the United States and colour the five regions. Label one state, one landform and one crop or industry in each.",
      [{ q: "How many regions is the United States usually divided into?", a: "Five" },
       { q: "Name the five regions.", a: "Northeast, Southeast, Midwest, Southwest and West" },
       { q: "Which region is known as the nation's farmland?", a: "The Midwest" },
       { q: "Which region is mostly desert and canyons?", a: "The Southwest" },
       { q: "Which region borders the Pacific Ocean?", a: "The West" },
       { q: "Which region had the earliest colonies?", a: "The Northeast" },
       { q: "What decides the work people do in a region?", a: "Its landforms and climate" },
       { q: "Which region is warm with a long coastline?", a: "The Southeast" }]),
    U("🏔️", "Landforms, Rivers & Resources",
      "Mountains, rivers and plains are not just scenery — they decided where American towns and cities grew.",
      ["Major landforms include the Appalachian Mountains in the east and the Rocky Mountains in the west.",
       "The Mississippi River is the longest river system in the United States and a major route for goods.",
       "The Great Lakes are five huge freshwater lakes on the border with Canada.",
       "Natural resources are useful things from the earth: water, soil, timber, coal, oil and minerals.",
       "Renewable resources can be replaced (trees, wind, sunlight); non-renewable ones cannot (coal, oil)."],
      "🏔️ Activity Sheet — Resource Hunt: List five things in your home and work out which natural resource each one came from.",
      [{ q: "Which mountains run along the eastern US?", a: "The Appalachian Mountains" },
       { q: "Which mountains run through the western US?", a: "The Rocky Mountains" },
       { q: "What is the longest river system in the US?", a: "The Mississippi" },
       { q: "How many Great Lakes are there?", a: "Five" },
       { q: "What is a natural resource?", a: "Something useful that comes from the earth" },
       { q: "Give an example of a renewable resource.", a: "Trees, wind, water or sunlight" },
       { q: "Give an example of a non-renewable resource.", a: "Coal, oil or natural gas" },
       { q: "Why did cities often grow beside rivers?", a: "Rivers gave water, food and a way to move goods" }]),
    U("🏛️", "My State & How It Governs",
      "Every state has its own capital, its own government and its own story — including yours.",
      ["Each of the 50 states has a capital city and its own state government.",
       "A governor leads a state, and a state legislature makes its laws.",
       "States have their own symbols: a flag, a bird, a flower and a motto.",
       "State government handles schools, highways, driving licences and state parks.",
       "Every state's story includes the Native nations who lived there first, and the people who came later."],
      "🏛️ Activity Sheet — State Profile: Research your own state. Write its capital, governor, state bird and flower, then draw its flag and outline.",
      [{ q: "How many states are in the United States?", a: "50" },
       { q: "Who leads a state government?", a: "The governor" },
       { q: "What is a state's most important city for government called?", a: "The capital" },
       { q: "Who makes a state's laws?", a: "The state legislature" },
       { q: "Name two things a state government looks after.", a: "Schools, highways, licences or state parks" },
       { q: "Name two symbols a state has.", a: "A flag, bird, flower or motto" },
       { q: "Who lived in your state before settlers came?", a: "Native American nations" },
       { q: "Does every state have the same laws?", a: "No — states make their own" }])
  ];

  H[5] = [
    U("⛵", "Exploration & the Thirteen Colonies",
      "US History, part one. Ships crossed the Atlantic, colonies took root, and the seeds of a new nation were planted.",
      ["Native nations had lived across North America for thousands of years before Europeans arrived.",
       "In 1492 Christopher Columbus sailed from Spain and reached islands in the Caribbean, opening lasting contact between Europe and the Americas.",
       "Contact brought trade but also war and European diseases, which killed a devastating share of Native peoples.",
       "Jamestown (1607) was the first permanent English settlement; Plymouth followed in 1620.",
       "Thirteen English colonies grew along the Atlantic coast, divided into New England, Middle and Southern colonies. Slavery of African people was practised in all thirteen."],
      "⛵ Activity Sheet — Colony Chart: Make three columns for New England, Middle and Southern colonies. Under each, write the climate, main crops or work, and one colony's name.",
      [{ q: "Who lived in North America before Europeans arrived?", a: "Native American nations" },
       { q: "In what year did Columbus first cross the Atlantic?", a: "1492" },
       { q: "What was the first permanent English settlement?", a: "Jamestown, in 1607" },
       { q: "Which colony was founded in 1620?", a: "Plymouth" },
       { q: "How many English colonies were there?", a: "Thirteen" },
       { q: "Name the three groups of colonies.", a: "New England, Middle and Southern" },
       { q: "What killed a huge number of Native people after contact?", a: "European diseases" },
       { q: "Was slavery practised in the colonies?", a: "Yes — in all thirteen" }]),
    U("🔔", "The American Revolution",
      "The colonies decided they would rather govern themselves — and went to war with the most powerful empire on Earth to do it.",
      ["Britain taxed the colonies without letting them elect anyone to Parliament. The colonists' cry was 'no taxation without representation'.",
       "Protests grew, including the Boston Tea Party in 1773, when colonists threw British tea into Boston Harbor.",
       "Fighting began in 1775 at Lexington and Concord in Massachusetts.",
       "The Declaration of Independence was adopted on July 4, 1776, written mainly by Thomas Jefferson.",
       "George Washington led the Continental Army, France joined the American side, and Britain surrendered at Yorktown in 1781."],
      "🔔 Activity Sheet — Declaration in Your Words: Read the famous line 'all men are created equal'. Write what it means in your own words, and who was left out of it in 1776.",
      [{ q: "What was the colonists' complaint about taxes?", a: "No taxation without representation" },
       { q: "What happened at the Boston Tea Party in 1773?", a: "Colonists threw British tea into the harbor" },
       { q: "Where did fighting begin in 1775?", a: "Lexington and Concord" },
       { q: "On what date was the Declaration of Independence adopted?", a: "July 4, 1776" },
       { q: "Who wrote most of the Declaration of Independence?", a: "Thomas Jefferson" },
       { q: "Who led the Continental Army?", a: "George Washington" },
       { q: "Which country helped the Americans win?", a: "France" },
       { q: "Where did the British surrender in 1781?", a: "Yorktown" }]),
    U("📜", "The Constitution & a New Nation",
      "Winning a war is one thing. Building a government that lasts is another — and it took a second try.",
      ["The first plan of government, the Articles of Confederation, left the national government too weak.",
       "In 1787 delegates met in Philadelphia and wrote the Constitution, which still governs the country today.",
       "The Constitution splits power into three branches — legislative (Congress makes laws), executive (the President carries them out) and judicial (the courts interpret them).",
       "Checks and balances let each branch limit the others so no one part becomes too powerful.",
       "The Bill of Rights — the first ten amendments, added in 1791 — protects freedoms such as speech, religion and a fair trial."],
      "📜 Activity Sheet — Three Branches: Draw three columns labelled Legislative, Executive and Judicial. Write who is in each and one job it does.",
      [{ q: "What was the first US plan of government called?", a: "The Articles of Confederation" },
       { q: "Why was it replaced?", a: "It left the national government too weak" },
       { q: "In what year was the Constitution written?", a: "1787" },
       { q: "Name the three branches of government.", a: "Legislative, executive and judicial" },
       { q: "Which branch makes the laws?", a: "The legislative branch (Congress)" },
       { q: "Which branch interprets the laws?", a: "The judicial branch (the courts)" },
       { q: "What are the first ten amendments called?", a: "The Bill of Rights" },
       { q: "Name a freedom the Bill of Rights protects.", a: "Speech, religion, press or a fair trial" }])
  ];

  H[6] = [
    U("🏺", "Mesopotamia & Ancient Egypt",
      "The first cities, the first writing, the first written laws — civilization begins along the great rivers.",
      ["Civilizations grew up beside rivers, which gave water, rich soil and a way to travel.",
       "Mesopotamia, between the Tigris and Euphrates rivers, is often called the cradle of civilization.",
       "The Sumerians invented cuneiform, one of the earliest writing systems, pressed into clay tablets.",
       "Hammurabi of Babylon issued one of the earliest written law codes.",
       "Ancient Egypt grew along the Nile, built the pyramids as royal tombs, wrote in hieroglyphs, and was ruled by pharaohs."],
      "🏺 Activity Sheet — Write Like a Sumerian: Invent five picture-symbols for words you use daily, then write a short message and have someone decode it.",
      [{ q: "Why did early civilizations grow beside rivers?", a: "Rivers gave water, good soil and transport" },
       { q: "Which two rivers bordered Mesopotamia?", a: "The Tigris and the Euphrates" },
       { q: "What was the Sumerian writing system called?", a: "Cuneiform" },
       { q: "Who issued one of the earliest written law codes?", a: "Hammurabi" },
       { q: "Which river was ancient Egypt built along?", a: "The Nile" },
       { q: "What were the pyramids built as?", a: "Tombs for rulers" },
       { q: "What was Egyptian picture writing called?", a: "Hieroglyphs" },
       { q: "What was an Egyptian ruler called?", a: "A pharaoh" }]),
    U("🏛️", "Ancient Greece & Rome",
      "Two civilizations on the Mediterranean gave the world democracy, philosophy, republics and roads that still exist.",
      ["Ancient Greece was made of independent city-states such as Athens and Sparta.",
       "Athens developed an early form of democracy, where citizens voted directly — though women and enslaved people were excluded.",
       "Greek thinkers including Socrates, Plato and Aristotle shaped philosophy, science and mathematics.",
       "Rome began as a republic, where citizens elected representatives to a Senate, and later became an empire ruled by emperors.",
       "Rome left lasting engineering — roads, aqueducts, concrete and the arch — and Roman law influences legal systems today."],
      "🏛️ Activity Sheet — Democracy Then & Now: List three ways Athenian democracy was like ours and three ways it was different. Who could not vote in Athens?",
      [{ q: "What were independent Greek cities called?", a: "City-states" },
       { q: "Which city-state developed early democracy?", a: "Athens" },
       { q: "Who was excluded from voting in Athens?", a: "Women and enslaved people" },
       { q: "Name a famous Greek philosopher.", a: "Socrates, Plato or Aristotle" },
       { q: "What kind of government did Rome have first?", a: "A republic" },
       { q: "In a republic, what do citizens do?", a: "Elect representatives" },
       { q: "What did Rome become after the republic?", a: "An empire, ruled by emperors" },
       { q: "Name a Roman engineering achievement.", a: "Roads, aqueducts, concrete or the arch" }]),
    U("🐉", "Ancient India & China",
      "Two of the world's oldest continuous civilizations, and the ideas and inventions they gave everyone else.",
      ["The Indus Valley civilization built carefully planned cities with drains and brick streets.",
       "Hinduism and Buddhism both began in ancient India; Buddhism was founded by Siddhartha Gautama, the Buddha.",
       "Ancient China grew along the Huang He (Yellow) River and was ruled by a series of dynasties.",
       "Chinese inventions include paper, the compass, gunpowder and printing.",
       "The Silk Road was a network of trade routes carrying goods and ideas between China, India, the Middle East and Europe."],
      "🐉 Activity Sheet — Silk Road Trader: Plan a journey along the Silk Road. List three goods you carry, three places you pass, and one idea you bring home.",
      [{ q: "What was special about Indus Valley cities?", a: "They were carefully planned, with drains and brick streets" },
       { q: "Name a religion that began in ancient India.", a: "Hinduism or Buddhism" },
       { q: "Who founded Buddhism?", a: "Siddhartha Gautama, the Buddha" },
       { q: "Which river was ancient Chinese civilization built along?", a: "The Huang He (Yellow River)" },
       { q: "What do we call a line of rulers from one family?", a: "A dynasty" },
       { q: "Name two Chinese inventions.", a: "Paper, the compass, gunpowder or printing" },
       { q: "What was the Silk Road?", a: "Trade routes connecting China with the West" },
       { q: "Did the Silk Road carry only goods?", a: "No — it carried ideas too" }])
  ];

  for (var g = 1; g <= 6; g++) {
    if (LESSONS[g]) LESSONS[g].history = { title: "Social Studies", emoji: "🏛️", units: H[g] };
  }
  window.__HISTORY_US_LOWER = true;
})();
