// BrightSprouts Academy — Social Studies, Grades 7–12 (US scope and sequence).
// G7 world history · G8 US HISTORY II · G9–10 world history · G11 US HISTORY III ·
// G12 Government, Civics & Economics.
(function () {
  if (typeof LESSONS === "undefined") return;
  function U(emoji, title, intro, learn, activity, questions) {
    return { emoji: emoji, title: title, intro: intro, learn: learn, activity: activity, questions: questions };
  }
  var H = {};

  H[7] = [
    U("🏰", "The Middle Ages",
      "After Rome fell, Europe reorganised itself around land, loyalty and the Church — and then met a plague that changed everything.",
      ["Feudalism was a system of land in exchange for loyalty and service: kings granted land to nobles, who owed them soldiers.",
       "Most people were peasants or serfs who farmed a lord's land and kept little of what they grew.",
       "The Catholic Church was the most powerful institution in medieval Europe, and monasteries preserved learning.",
       "Islamic civilization flourished at the same time, advancing mathematics, medicine and astronomy and preserving Greek texts.",
       "The Black Death, a plague arriving in Europe in the 1340s, killed roughly a third of the population and weakened feudalism."],
      "🏰 Activity Sheet — Feudal Pyramid: Draw the feudal pyramid with king, nobles, knights and peasants. Beside each, write what they gave and what they got.",
      [{ q: "What was feudalism?", a: "Land given in exchange for loyalty and service" },
       { q: "Who sat at the top of the feudal pyramid?", a: "The king" },
       { q: "Who farmed the land and kept little of it?", a: "Peasants and serfs" },
       { q: "What was the most powerful institution in medieval Europe?", a: "The Catholic Church" },
       { q: "Where was learning preserved in Europe?", a: "In monasteries" },
       { q: "Name a field Islamic scholars advanced.", a: "Mathematics, medicine or astronomy" },
       { q: "What was the Black Death?", a: "A plague that struck Europe in the 1340s" },
       { q: "About how much of Europe's population died?", a: "About one third" }]),
    U("🎨", "The Renaissance & Reformation",
      "Europe rediscovered the classical world, learned to print, and then split the Church in two.",
      ["Renaissance means 'rebirth' — a renewed interest in Greek and Roman learning, beginning in Italy.",
       "Humanism placed new value on human potential, observation and life in this world.",
       "Leonardo da Vinci and Michelangelo produced art built on anatomy, mathematics and perspective.",
       "Around 1450 Johannes Gutenberg's printing press made books cheap, spreading ideas faster than ever before.",
       "In 1517 Martin Luther challenged practices of the Catholic Church, starting the Protestant Reformation and splitting Western Christianity."],
      "🎨 Activity Sheet — Before & After Printing: List three effects of the printing press. Then name one modern invention that spread information just as fast and compare them.",
      [{ q: "What does 'Renaissance' mean?", a: "Rebirth" },
       { q: "Where did the Renaissance begin?", a: "Italy" },
       { q: "What is humanism?", a: "Valuing human potential and life in this world" },
       { q: "Name a famous Renaissance artist.", a: "Leonardo da Vinci or Michelangelo" },
       { q: "Who developed the printing press in Europe?", a: "Johannes Gutenberg" },
       { q: "Why did the printing press matter?", a: "It made books cheap and spread ideas quickly" },
       { q: "Who began the Protestant Reformation?", a: "Martin Luther" },
       { q: "In what year did Luther challenge the Church?", a: "1517" }]),
    U("🧭", "Exploration & Global Trade",
      "Better ships and better maps connected continents that had never met — with world-changing and often brutal results.",
      ["Advances in navigation — the compass, the astrolabe and the caravel — made long ocean voyages possible.",
       "Nations sought wealth, land, and new trade routes to Asia, chasing spices, silk and gold.",
       "The Columbian Exchange moved plants, animals and diseases between the Americas and the rest of the world.",
       "Foods that crossed the Atlantic changed diets everywhere: potatoes, maize and tomatoes went east; wheat, cattle and horses went west.",
       "European colonisation devastated Native populations and drove the transatlantic slave trade, which forcibly took millions of Africans to the Americas."],
      "🧭 Activity Sheet — Columbian Exchange Map: Draw arrows across an Atlantic map showing what moved each way — foods, animals and diseases. Label at least six items.",
      [{ q: "Name a navigation tool that enabled ocean voyages.", a: "The compass, astrolabe or caravel" },
       { q: "What were explorers seeking in Asia?", a: "Spices, silk and gold — and trade routes" },
       { q: "What was the Columbian Exchange?", a: "The movement of plants, animals and diseases between continents" },
       { q: "Name a food that went from the Americas to Europe.", a: "Potatoes, maize or tomatoes" },
       { q: "Name an animal Europeans brought to the Americas.", a: "Horses or cattle" },
       { q: "What happened to Native populations after contact?", a: "They were devastated, largely by disease and colonisation" },
       { q: "What was the transatlantic slave trade?", a: "The forced transport of millions of Africans to the Americas" },
       { q: "Did the exchange move diseases too?", a: "Yes — with catastrophic effects in the Americas" }])
  ];

  H[8] = [
    U("🌱", "A New Nation Grows",
      "US History, part two. The Constitution was written — now the country had to make it work.",
      ["George Washington became the first president in 1789 and set precedents still followed today.",
       "Political parties formed almost immediately, disagreeing over how strong the national government should be.",
       "The Louisiana Purchase of 1803 bought a vast territory from France and roughly doubled the size of the country.",
       "Lewis and Clark explored that territory, guided in part by Sacagawea, a Lemhi Shoshone woman.",
       "The Industrial Revolution brought factories, textile mills and railroads, changing where and how Americans worked."],
      "🌱 Activity Sheet — Then the Map Doubled: On a US outline, shade the original 13 states and the Louisiana Purchase. Write two effects of that purchase.",
      [{ q: "Who became the first US president, and when?", a: "George Washington, in 1789" },
       { q: "What did the US buy in 1803?", a: "The Louisiana Territory, from France" },
       { q: "What did the Louisiana Purchase do to the country's size?", a: "Roughly doubled it" },
       { q: "Who explored the new territory?", a: "Lewis and Clark" },
       { q: "Who guided part of their expedition?", a: "Sacagawea" },
       { q: "What did the Industrial Revolution bring?", a: "Factories, mills and railroads" },
       { q: "Why did political parties form?", a: "People disagreed over how strong the national government should be" },
       { q: "Name something Washington created by example.", a: "Precedents such as stepping down after two terms" }]),
    U("🚂", "Westward Expansion & Slavery",
      "The nation pushed west — and the question of slavery grew impossible to avoid.",
      ["'Manifest Destiny' was the belief that the US was meant to expand across the continent.",
       "Expansion forced Native nations off their lands. The Indian Removal Act led to the Trail of Tears, on which thousands of Cherokee and others died.",
       "The economy of the South depended on enslaved Black people forced to labour on cotton plantations.",
       "Abolitionists including Frederick Douglass and Harriet Tubman worked to end slavery; the Underground Railroad helped people escape to freedom.",
       "Each new state raised the same explosive question: would it be free or slave? Compromises delayed the conflict but never settled it."],
      "🚂 Activity Sheet — Two Perspectives: Write two short diary entries about westward expansion in 1840 — one from a settler heading west, one from a member of a Native nation already living there.",
      [{ q: "What was 'Manifest Destiny'?", a: "The belief the US was meant to expand across the continent" },
       { q: "What was the Trail of Tears?", a: "The forced removal of Cherokee and other nations, on which thousands died" },
       { q: "What crop did the Southern economy depend on?", a: "Cotton" },
       { q: "Who worked to end slavery?", a: "Abolitionists" },
       { q: "Name a famous abolitionist.", a: "Frederick Douglass or Harriet Tubman" },
       { q: "What was the Underground Railroad?", a: "A secret network helping enslaved people escape to freedom" },
       { q: "What question did each new state raise?", a: "Whether it would be free or slave" },
       { q: "Did compromises solve the conflict over slavery?", a: "No — they only delayed it" }]),
    U("⚔️", "The Civil War & Reconstruction",
      "The country split in two and fought itself. What followed decided what freedom would actually mean.",
      ["Southern states seceded after Abraham Lincoln's election, forming the Confederacy; the war ran from 1861 to 1865.",
       "Slavery was the central cause of secession and the war.",
       "The Emancipation Proclamation of 1863 declared enslaved people in Confederate states to be free and made ending slavery a war aim.",
       "The Union won in 1865. Lincoln was assassinated days after the surrender.",
       "Three amendments followed: the 13th ended slavery, the 14th granted citizenship and equal protection, and the 15th protected Black men's right to vote. Reconstruction's gains were then rolled back by segregation laws."],
      "⚔️ Activity Sheet — The Three Amendments: Make a table of the 13th, 14th and 15th Amendments — what each one did, and why each was needed.",
      [{ q: "In what years was the Civil War fought?", a: "1861 to 1865" },
       { q: "What was the central cause of the war?", a: "Slavery" },
       { q: "What were the seceding states called?", a: "The Confederacy" },
       { q: "Who was president during the Civil War?", a: "Abraham Lincoln" },
       { q: "What did the Emancipation Proclamation declare?", a: "That enslaved people in Confederate states were free" },
       { q: "Which amendment ended slavery?", a: "The 13th" },
       { q: "Which amendment granted citizenship and equal protection?", a: "The 14th" },
       { q: "What happened to Reconstruction's gains?", a: "They were rolled back by segregation laws" }])
  ];

  H[9] = [
    U("⚙️", "Revolutions & the Industrial Age",
      "Within a century, ideas about who should rule and machines that could outwork any human remade the world.",
      ["The Enlightenment argued for reason, natural rights and government by consent — ideas that fuelled revolutions.",
       "The American and French Revolutions both challenged rule by kings; the French Revolution began in 1789.",
       "The Industrial Revolution began in Britain with textiles, steam power and coal.",
       "Factory work brought cities, wages and terrible conditions, including child labour, prompting unions and reform laws.",
       "Industrial powers then competed for colonies and raw materials, driving a new wave of imperialism across Africa and Asia."],
      "⚙️ Activity Sheet — Cause & Effect Chain: Build a chain from 'new farming methods' to 'crowded industrial cities'. Use at least five linked steps.",
      [{ q: "What did Enlightenment thinkers argue for?", a: "Reason, natural rights and government by consent" },
       { q: "In what year did the French Revolution begin?", a: "1789" },
       { q: "Where did the Industrial Revolution begin?", a: "Britain" },
       { q: "What powered early industry?", a: "Steam, fuelled by coal" },
       { q: "Name a problem of early factory work.", a: "Child labour, long hours or dangerous conditions" },
       { q: "What did workers form to demand better conditions?", a: "Unions" },
       { q: "What is imperialism?", a: "Powerful nations taking control of other territories" },
       { q: "Why did industrial nations want colonies?", a: "For raw materials and markets" }]),
    U("💣", "World War I & Its Aftermath",
      "An assassination lit a fuse under a continent already stacked with alliances and weapons.",
      ["Long-term causes are often summarised as militarism, alliances, imperialism and nationalism.",
       "The war ran from 1914 to 1918, triggered by the assassination of Archduke Franz Ferdinand.",
       "New weapons — machine guns, poison gas, tanks and aircraft — produced trench warfare and staggering casualties.",
       "The United States entered in 1917, helping tip the balance to the Allies.",
       "The Treaty of Versailles punished Germany harshly; that resentment, plus the Great Depression, helped fascism rise in the 1930s."],
      "💣 Activity Sheet — M.A.I.N. Causes: Make four boxes for militarism, alliances, imperialism and nationalism. Give a real example of each and rank which you think mattered most.",
      [{ q: "In what years was World War I fought?", a: "1914 to 1918" },
       { q: "Whose assassination triggered the war?", a: "Archduke Franz Ferdinand" },
       { q: "Name the four long-term causes.", a: "Militarism, alliances, imperialism and nationalism" },
       { q: "What kind of warfare dominated the Western Front?", a: "Trench warfare" },
       { q: "Name a new weapon of World War I.", a: "Machine guns, poison gas, tanks or aircraft" },
       { q: "In what year did the US enter the war?", a: "1917" },
       { q: "What treaty ended the war?", a: "The Treaty of Versailles" },
       { q: "What did that treaty do to Germany?", a: "Punished it harshly, breeding resentment" }]),
    U("🕊️", "World War II & the Holocaust",
      "The deadliest conflict in human history — and the crime that forced the world to define crimes against humanity.",
      ["The war began in 1939 when Germany invaded Poland, and ended in 1945.",
       "The Allies included Britain, the Soviet Union, the United States and China; the Axis were Germany, Italy and Japan.",
       "The US entered after Japan attacked Pearl Harbor on December 7, 1941.",
       "The Holocaust was the systematic murder of six million Jewish people, along with millions of Roma, disabled people, Poles, Soviet prisoners and others, by Nazi Germany.",
       "The war ended in Europe in May 1945 and in the Pacific in August 1945 after atomic bombs were dropped on Hiroshima and Nagasaki. The United Nations was founded to prevent another such war."],
      "🕊️ Activity Sheet — Why Remember: Write a paragraph on why the Holocaust must be taught and remembered. Include what ordinary people can do when they see hatred.",
      [{ q: "In what years was World War II fought?", a: "1939 to 1945" },
       { q: "What event began the war in Europe?", a: "Germany's invasion of Poland" },
       { q: "Name two Allied powers.", a: "Britain, the Soviet Union, the US or China" },
       { q: "Name the three main Axis powers.", a: "Germany, Italy and Japan" },
       { q: "What brought the United States into the war?", a: "The attack on Pearl Harbor, December 7, 1941" },
       { q: "What was the Holocaust?", a: "The systematic murder of six million Jewish people and millions of others by Nazi Germany" },
       { q: "How did the war in the Pacific end?", a: "After atomic bombs were dropped on Hiroshima and Nagasaki in August 1945" },
       { q: "What organisation was founded to prevent future wars?", a: "The United Nations" }])
  ];

  H[10] = [
    U("❄️", "The Cold War",
      "Two superpowers, two systems, and forty years of confrontation that never quite became direct war between them.",
      ["After 1945 the United States and the Soviet Union emerged as rival superpowers with opposed systems: capitalism and democracy against communism and one-party rule.",
       "It is called 'cold' because the two never fought each other directly, competing instead through allies, spying, propaganda and an arms race.",
       "Europe was divided; the Berlin Wall, built in 1961, became the symbol of that division.",
       "Proxy wars were fought in Korea and Vietnam, and the Cuban Missile Crisis of 1962 brought the world close to nuclear war.",
       "The Berlin Wall fell in 1989 and the Soviet Union dissolved in 1991, ending the Cold War."],
      "❄️ Activity Sheet — Two Systems: Make a comparison table of the US and Soviet systems — economy, government, press and daily life. Add one thing both claimed to offer.",
      [{ q: "Which two superpowers faced off in the Cold War?", a: "The United States and the Soviet Union" },
       { q: "Why is it called a 'cold' war?", a: "They never fought each other directly" },
       { q: "What was built in 1961 to divide a city?", a: "The Berlin Wall" },
       { q: "Name a Cold War proxy war.", a: "Korea or Vietnam" },
       { q: "What crisis in 1962 nearly caused nuclear war?", a: "The Cuban Missile Crisis" },
       { q: "What economic system did the Soviet Union follow?", a: "Communism" },
       { q: "In what year did the Berlin Wall fall?", a: "1989" },
       { q: "When did the Soviet Union dissolve?", a: "1991" }]),
    U("🌍", "Independence & the Modern World",
      "As empires retreated, dozens of new nations drew their own futures — and a connected world brought new problems.",
      ["After World War II, colonies across Africa and Asia won independence, a process called decolonisation.",
       "India gained independence in 1947, following a movement in which Mohandas Gandhi led nonviolent resistance.",
       "Many new nations inherited borders drawn by colonisers, which cut across peoples and caused lasting conflict.",
       "In South Africa, apartheid enforced racial segregation until it ended in the early 1990s; Nelson Mandela became president in 1994.",
       "Globalisation links economies and cultures worldwide, bringing both opportunity and shared problems such as climate change."],
      "🌍 Activity Sheet — Independence Profile: Choose one country that gained independence after 1945. Note the year, the colonial power, and one challenge it faced afterwards.",
      [{ q: "What is decolonisation?", a: "Colonies gaining independence from empires" },
       { q: "When did India gain independence?", a: "1947" },
       { q: "Who led nonviolent resistance in India?", a: "Mohandas Gandhi" },
       { q: "Why did colonial borders cause conflict?", a: "They were drawn by outsiders and cut across peoples" },
       { q: "What was apartheid?", a: "Enforced racial segregation in South Africa" },
       { q: "Who became South Africa's president in 1994?", a: "Nelson Mandela" },
       { q: "What is globalisation?", a: "The linking of economies and cultures worldwide" },
       { q: "Name a shared global problem today.", a: "Climate change (or pandemics, inequality)" }]),
    U("💡", "Human Rights & the World Today",
      "Out of the twentieth century's worst moments came the idea that some rights belong to every person, everywhere.",
      ["The Universal Declaration of Human Rights was adopted by the United Nations in 1948.",
       "It says all human beings are born free and equal in dignity and rights.",
       "Genocide is the deliberate destruction of a people; the world has pledged 'never again' repeatedly, and repeatedly failed.",
       "International courts and organisations now exist to hold leaders accountable for crimes against humanity.",
       "Rights are not automatic — they are protected by informed citizens, free press and independent courts."],
      "💡 Activity Sheet — Rights Audit: Read five articles of the Universal Declaration. For each, write one way it shows up in daily life and one place it is at risk.",
      [{ q: "In what year was the Universal Declaration of Human Rights adopted?", a: "1948" },
       { q: "Which organisation adopted it?", a: "The United Nations" },
       { q: "What does it say about how people are born?", a: "Free and equal in dignity and rights" },
       { q: "What is genocide?", a: "The deliberate destruction of a people" },
       { q: "What exists to hold leaders accountable?", a: "International courts" },
       { q: "Name something that protects rights day to day.", a: "Informed citizens, a free press or independent courts" },
       { q: "Are human rights only for citizens of one country?", a: "No — they belong to every person" },
       { q: "Why study past atrocities?", a: "To recognise the warning signs and prevent them" }])
  ];

  H[11] = [
    U("🏭", "The Gilded Age & Progressive Era",
      "US History, part three. Industry made vast fortunes and vast misery, and reformers set out to fix it.",
      ["After the Civil War, industry, railroads and steel transformed the US economy.",
       "Millions of immigrants arrived, many through Ellis Island, supplying labour and reshaping American cities.",
       "Enormous fortunes sat beside tenement poverty, child labour and unsafe factories.",
       "Progressive reformers pushed for safety laws, limits on child labour, food and drug inspection and trust-busting.",
       "The women's suffrage movement won the vote with the 19th Amendment in 1920."],
      "🏭 Activity Sheet — Reform Proposal: Pick one Gilded Age problem. Write the problem, who it harmed, the reform proposed, and whether it worked.",
      [{ q: "What transformed the US economy after the Civil War?", a: "Industry, railroads and steel" },
       { q: "Where did many immigrants arrive in New York?", a: "Ellis Island" },
       { q: "Name a problem of the Gilded Age.", a: "Child labour, unsafe factories or tenement poverty" },
       { q: "What did Progressive reformers want?", a: "Safety laws, limits on child labour, inspection and trust-busting" },
       { q: "Which amendment gave women the vote?", a: "The 19th" },
       { q: "In what year was it ratified?", a: "1920" },
       { q: "What is a trust, in this era?", a: "A giant business combination that limited competition" },
       { q: "Why is it called the 'Gilded' Age?", a: "It looked golden on the surface but hid serious problems" }]),
    U("📻", "Depression, the New Deal & the War at Home",
      "The economy collapsed, government's role changed permanently, and a world war reshaped American life.",
      ["The stock market crashed in 1929, beginning the Great Depression; unemployment reached about one in four workers.",
       "The Dust Bowl drove farming families from the Plains after drought and soil erosion.",
       "Franklin D. Roosevelt's New Deal created jobs programmes, banking reform and Social Security, expanding the federal government's role.",
       "World War II ended the Depression as industry mobilised; women entered factories in huge numbers, symbolised by 'Rosie the Riveter'.",
       "The US government forcibly incarcerated about 120,000 Japanese Americans, most of them citizens, in camps — later formally apologised for."],
      "📻 Activity Sheet — New Deal Programme: Choose one New Deal programme. Write what problem it addressed, who it helped, and whether anything like it exists today.",
      [{ q: "What happened in 1929?", a: "The stock market crashed, starting the Great Depression" },
       { q: "About how many workers were unemployed at the worst point?", a: "About one in four" },
       { q: "What was the Dust Bowl?", a: "Drought and soil erosion that drove farmers off the Plains" },
       { q: "Whose programme was the New Deal?", a: "Franklin D. Roosevelt's" },
       { q: "Name a lasting New Deal creation.", a: "Social Security" },
       { q: "What finally ended the Depression?", a: "Mobilisation for World War II" },
       { q: "What did 'Rosie the Riveter' represent?", a: "Women working in wartime factories" },
       { q: "What happened to Japanese Americans during the war?", a: "About 120,000 were forcibly incarcerated in camps" }]),
    U("✊", "Civil Rights to the Present",
      "The long struggle to make the promise of equal protection real — and the America that followed it.",
      ["Segregation laws enforced racial separation, especially in the South, long after slavery ended.",
       "Brown v. Board of Education (1954) ruled that segregated public schools were unconstitutional.",
       "The Montgomery Bus Boycott began after Rosa Parks was arrested in 1955; Martin Luther King Jr. became a leading voice for nonviolent protest.",
       "The Civil Rights Act of 1964 banned discrimination in public places and employment; the Voting Rights Act of 1965 protected the right to vote.",
       "Movements for women's rights, disability rights, Native rights and LGBTQ rights followed, and debates over equality and voting access continue today."],
      "✊ Activity Sheet — Movement Timeline: Build a timeline from 1954 to 1965 with at least six events. For each, note what changed in law or daily life.",
      [{ q: "What did segregation laws do?", a: "Enforced racial separation" },
       { q: "What did Brown v. Board of Education decide in 1954?", a: "That segregated public schools were unconstitutional" },
       { q: "Whose 1955 arrest sparked the Montgomery Bus Boycott?", a: "Rosa Parks" },
       { q: "Who led nonviolent civil rights protest?", a: "Martin Luther King Jr." },
       { q: "What did the Civil Rights Act of 1964 ban?", a: "Discrimination in public places and employment" },
       { q: "What did the Voting Rights Act of 1965 protect?", a: "The right to vote" },
       { q: "Name another movement that followed.", a: "Women's, disability, Native or LGBTQ rights" },
       { q: "Did the struggle end in 1965?", a: "No — debates over equality and voting continue" }])
  ];

  H[12] = [
    U("🏛️", "The Constitution & How Government Works",
      "Senior year civics. If you are about to be able to vote, this is the instruction manual.",
      ["The Constitution is the supreme law of the United States; all other laws must agree with it.",
       "Power is separated into three branches — legislative, executive and judicial — each checking the others.",
       "Congress has two chambers: the House of Representatives (seats by population) and the Senate (two per state).",
       "Federalism divides power between the national government and the states.",
       "The Supreme Court can rule laws unconstitutional, a power called judicial review; amendments require supermajorities to pass."],
      "🏛️ Activity Sheet — Trace a Bill: Follow one bill from idea to law. Show every step, and mark the two points where it could most easily fail.",
      [{ q: "What is the supreme law of the United States?", a: "The Constitution" },
       { q: "Name the three branches of government.", a: "Legislative, executive and judicial" },
       { q: "What are the two chambers of Congress?", a: "The House of Representatives and the Senate" },
       { q: "How many senators does each state get?", a: "Two" },
       { q: "How are House seats allocated?", a: "By population" },
       { q: "What is federalism?", a: "Power divided between national and state governments" },
       { q: "What is judicial review?", a: "The courts' power to rule a law unconstitutional" },
       { q: "Why are checks and balances there?", a: "So no branch becomes too powerful" }]),
    U("🗳️", "Citizenship, Rights & Voting",
      "Rights come with responsibilities, and a democracy runs on people actually turning up.",
      ["Citizens have rights including speech, religion, assembly, due process and a fair trial.",
       "Citizens also have responsibilities: obeying laws, paying taxes, serving on juries and voting.",
       "Amendments expanded the vote over time — the 15th, 19th, 24th and 26th, which set the voting age at 18.",
       "Registering to vote, checking your polling place and reading about candidates are the practical steps of participation.",
       "Media literacy is a civic skill: check the source, look for evidence, and be wary of anything designed to make you furious."],
      "🗳️ Activity Sheet — Voter's Guide: Research one real ballot measure or office. Summarise both sides fairly in your own words, then state which questions you would still want answered.",
      [{ q: "Name three rights citizens hold.", a: "Speech, religion, assembly, due process or fair trial" },
       { q: "Name three responsibilities of citizens.", a: "Obeying laws, paying taxes, jury duty, voting" },
       { q: "Which amendment set the voting age at 18?", a: "The 26th" },
       { q: "Which amendment protected Black men's right to vote?", a: "The 15th" },
       { q: "Which amendment gave women the vote?", a: "The 19th" },
       { q: "What is the first practical step to voting?", a: "Registering to vote" },
       { q: "Name a media-literacy check.", a: "Check the source and look for evidence" },
       { q: "Why be wary of content that makes you furious?", a: "Strong emotion is often used to bypass careful thinking" }]),
    U("💵", "Economics & Personal Finance",
      "How an economy works, and how to keep your own finances from working against you.",
      ["Scarcity means resources are limited, so every choice has an opportunity cost — what you gave up.",
       "Supply and demand set prices in a market economy: scarce and wanted means expensive.",
       "A budget tracks income against expenses. Paying yourself first — saving before spending — is the habit that compounds.",
       "Credit is borrowed money that must be repaid with interest. Compound interest grows savings powerfully and grows debt just as fast.",
       "Taxes fund public services; understanding a paycheck, gross versus net pay, and an emergency fund are core adult skills."],
      "💵 Activity Sheet — Real Budget: Build a monthly budget for a first job. Include rent, food, transport, savings and one unexpected $400 expense. What breaks first?",
      [{ q: "What is scarcity?", a: "Resources are limited while wants are not" },
       { q: "What is opportunity cost?", a: "What you gave up to make a choice" },
       { q: "What sets prices in a market economy?", a: "Supply and demand" },
       { q: "What is a budget?", a: "A plan tracking income against expenses" },
       { q: "What does 'pay yourself first' mean?", a: "Save before you spend" },
       { q: "What is credit?", a: "Borrowed money repaid with interest" },
       { q: "Why is compound interest powerful?", a: "It grows savings — and debt — faster over time" },
       { q: "What is the difference between gross and net pay?", a: "Gross is before deductions, net is what you take home" }])
  ];

  for (var g = 7; g <= 12; g++) {
    if (LESSONS[g]) LESSONS[g].history = { title: "Social Studies", emoji: "🏛️", units: H[g] };
  }
})();
