// BrightSprouts Academy — Flora & Fauna, part 2: Europe, Americas, Oceania
Object.assign(FF_COUNTRY, {
// ================= EUROPE =================
al:{flora:[["Olive tree","Olea europaea"],["Albanian oak","Quercus robur"],["Bosnian pine","Pinus heldreichii"],["Sage","Salvia officinalis"],["Chestnut tree","Castanea sativa"]],
    fauna:[["Golden eagle","Aquila chrysaetos"],["Brown bear","Ursus arctos"],["Balkan lynx","Lynx lynx"],["Grey wolf","Canis lupus"],["Dalmatian pelican","Pelecanus crispus"]]},
ad:{flora:[["Grandalla","Narcissus poeticus"],["Scots pine","Pinus sylvestris"],["Silver birch","Betula pendula"],["Edelweiss","Leontopodium nivale"],["European beech","Fagus sylvatica"]],
    fauna:[["Pyrenean chamois","Rupicapra pyrenaica"],["Golden eagle","Aquila chrysaetos"],["Bearded vulture","Gypaetus barbatus"],["Alpine marmot","Marmota marmota"],["Red fox","Vulpes vulpes"]]},
at:{flora:[["Edelweiss","Leontopodium nivale"],["Norway spruce","Picea abies"],["European larch","Larix decidua"],["Gentian","Gentiana clusii"],["European beech","Fagus sylvatica"]],
    fauna:[["Alpine ibex","Capra ibex"],["Alpine marmot","Marmota marmota"],["Golden eagle","Aquila chrysaetos"],["Red deer","Cervus elaphus"],["Chamois","Rupicapra rupicapra"]]},
by:{flora:[["Scots pine","Pinus sylvestris"],["Silver birch","Betula pendula"],["Cornflower","Centaurea cyanus"],["Norway spruce","Picea abies"],["English oak","Quercus robur"]],
    fauna:[["European bison","Bison bonasus"],["Grey wolf","Canis lupus"],["Eurasian lynx","Lynx lynx"],["White stork","Ciconia ciconia"],["Eurasian beaver","Castor fiber"]]},
be:{flora:[["Red poppy","Papaver rhoeas"],["European beech","Fagus sylvatica"],["Bluebell","Hyacinthoides non-scripta"],["English oak","Quercus robur"],["Common hawthorn","Crataegus monogyna"]],
    fauna:[["Red fox","Vulpes vulpes"],["European hedgehog","Erinaceus europaeus"],["Roe deer","Capreolus capreolus"],["Common kestrel","Falco tinnunculus"],["Eurasian badger","Meles meles"]]},
ba:{flora:[["Bosnian pine","Pinus heldreichii"],["European beech","Fagus sylvatica"],["Norway spruce","Picea abies"],["Bosnian lily","Lilium bosniacum"],["Chestnut tree","Castanea sativa"]],
    fauna:[["Brown bear","Ursus arctos"],["Grey wolf","Canis lupus"],["Eurasian lynx","Lynx lynx"],["Chamois","Rupicapra rupicapra"],["Golden eagle","Aquila chrysaetos"]]},
bg:{flora:[["Damask rose","Rosa damascena"],["Bulgarian fir","Abies borisii-regis"],["Edelweiss","Leontopodium nivale"],["European beech","Fagus sylvatica"],["Macedonian pine","Pinus peuce"]],
    fauna:[["Brown bear","Ursus arctos"],["Dalmatian pelican","Pelecanus crispus"],["Eastern imperial eagle","Aquila heliaca"],["Grey wolf","Canis lupus"],["Chamois","Rupicapra rupicapra"]]},
hr:{flora:[["Olive tree","Olea europaea"],["Lavender","Lavandula angustifolia"],["Aleppo pine","Pinus halepensis"],["Croatian iris","Iris croatica"],["European beech","Fagus sylvatica"]],
    fauna:[["Brown bear","Ursus arctos"],["Eurasian lynx","Lynx lynx"],["Griffon vulture","Gyps fulvus"],["Bottlenose dolphin","Tursiops truncatus"],["Olm","Proteus anguinus"]]},
cz:{flora:[["Small-leaved lime","Tilia cordata"],["Norway spruce","Picea abies"],["European beech","Fagus sylvatica"],["Rose","Rosa canina"],["Scots pine","Pinus sylvestris"]],
    fauna:[["Eurasian lynx","Lynx lynx"],["Red deer","Cervus elaphus"],["European hare","Lepus europaeus"],["White stork","Ciconia ciconia"],["Eurasian otter","Lutra lutra"]]},
dk:{flora:[["European beech","Fagus sylvatica"],["Marguerite daisy","Leucanthemum vulgare"],["Common heather","Calluna vulgaris"],["English oak","Quercus robur"],["Scots pine","Pinus sylvestris"]],
    fauna:[["Mute swan","Cygnus olor"],["Red deer","Cervus elaphus"],["Harbour seal","Phoca vitulina"],["European hedgehog","Erinaceus europaeus"],["Red fox","Vulpes vulpes"]]},
ee:{flora:[["Cornflower","Centaurea cyanus"],["Silver birch","Betula pendula"],["Scots pine","Pinus sylvestris"],["Norway spruce","Picea abies"],["Juniper","Juniperus communis"]],
    fauna:[["Grey wolf","Canis lupus"],["Eurasian lynx","Lynx lynx"],["Brown bear","Ursus arctos"],["Barn swallow","Hirundo rustica"],["Eurasian beaver","Castor fiber"]]},
fi:{flora:[["Silver birch","Betula pendula"],["Lily of the valley","Convallaria majalis"],["Norway spruce","Picea abies"],["Cloudberry","Rubus chamaemorus"],["Lingonberry","Vaccinium vitis-idaea"]],
    fauna:[["Brown bear","Ursus arctos"],["Reindeer","Rangifer tarandus"],["Whooper swan","Cygnus cygnus"],["Saimaa ringed seal","Pusa hispida"],["Eurasian lynx","Lynx lynx"]]},
fr:{flora:[["Lavender","Lavandula angustifolia"],["Grapevine","Vitis vinifera"],["Iris","Iris germanica"],["European beech","Fagus sylvatica"],["Stone pine","Pinus pinea"]],
    fauna:[["Camargue horse","Equus caballus"],["Greater flamingo","Phoenicopterus roseus"],["Alpine ibex","Capra ibex"],["Wild boar","Sus scrofa"],["Golden eagle","Aquila chrysaetos"]]},
de:{flora:[["English oak","Quercus robur"],["Cornflower","Centaurea cyanus"],["European beech","Fagus sylvatica"],["Norway spruce","Picea abies"],["Small-leaved lime","Tilia cordata"]],
    fauna:[["White-tailed eagle","Haliaeetus albicilla"],["Red deer","Cervus elaphus"],["Wild boar","Sus scrofa"],["European wildcat","Felis silvestris"],["Black stork","Ciconia nigra"]]},
gr:{flora:[["Olive tree","Olea europaea"],["Cypress","Cupressus sempervirens"],["Oregano","Origanum vulgare"],["Aleppo pine","Pinus halepensis"],["Grapevine","Vitis vinifera"]],
    fauna:[["Loggerhead sea turtle","Caretta caretta"],["Monk seal","Monachus monachus"],["Cretan wild goat","Capra aegagrus"],["Griffon vulture","Gyps fulvus"],["Brown bear","Ursus arctos"]]},
hu:{flora:[["Tulip","Tulipa gesneriana"],["English oak","Quercus robur"],["Common poppy","Papaver rhoeas"],["Acacia","Robinia pseudoacacia"],["Small-leaved lime","Tilia cordata"]],
    fauna:[["Great bustard","Otis tarda"],["Grey wolf","Canis lupus"],["White stork","Ciconia ciconia"],["Red deer","Cervus elaphus"],["Eurasian otter","Lutra lutra"]]},
is:{flora:[["Mountain avens","Dryas octopetala"],["Downy birch","Betula pubescens"],["Arctic thyme","Thymus praecox"],["Common heather","Calluna vulgaris"],["Moss campion","Silene acaulis"]],
    fauna:[["Arctic fox","Vulpes lagopus"],["Atlantic puffin","Fratercula arctica"],["Icelandic horse","Equus caballus"],["Humpback whale","Megaptera novaeangliae"],["Gyrfalcon","Falco rusticolus"]]},
ie:{flora:[["Shamrock","Trifolium dubium"],["Sessile oak","Quercus petraea"],["Bluebell","Hyacinthoides non-scripta"],["Common heather","Calluna vulgaris"],["Gorse","Ulex europaeus"]],
    fauna:[["Red deer","Cervus elaphus"],["Atlantic puffin","Fratercula arctica"],["Irish hare","Lepus timidus"],["Grey seal","Halichoerus grypus"],["European otter","Lutra lutra"]]},
it:{flora:[["Olive tree","Olea europaea"],["Stone pine","Pinus pinea"],["Cypress","Cupressus sempervirens"],["Lemon tree","Citrus limon"],["Grapevine","Vitis vinifera"]],
    fauna:[["Italian wolf","Canis lupus"],["Marsican brown bear","Ursus arctos"],["Alpine ibex","Capra ibex"],["Peregrine falcon","Falco peregrinus"],["Greater flamingo","Phoenicopterus roseus"]]},
lv:{flora:[["Oxeye daisy","Leucanthemum vulgare"],["Scots pine","Pinus sylvestris"],["Silver birch","Betula pendula"],["Small-leaved lime","Tilia cordata"],["Norway spruce","Picea abies"]],
    fauna:[["White wagtail","Motacilla alba"],["Eurasian lynx","Lynx lynx"],["Grey wolf","Canis lupus"],["Eurasian beaver","Castor fiber"],["Black stork","Ciconia nigra"]]},
li:{flora:[["Yellow lily","Lilium bulbiferum"],["Norway spruce","Picea abies"],["Edelweiss","Leontopodium nivale"],["European beech","Fagus sylvatica"],["Gentian","Gentiana clusii"]],
    fauna:[["Alpine ibex","Capra ibex"],["Chamois","Rupicapra rupicapra"],["Golden eagle","Aquila chrysaetos"],["Red deer","Cervus elaphus"],["Alpine marmot","Marmota marmota"]]},
lt:{flora:[["Common rue","Ruta graveolens"],["Scots pine","Pinus sylvestris"],["Silver birch","Betula pendula"],["English oak","Quercus robur"],["Norway spruce","Picea abies"]],
    fauna:[["White stork","Ciconia ciconia"],["Grey wolf","Canis lupus"],["European bison","Bison bonasus"],["Eurasian lynx","Lynx lynx"],["Eurasian beaver","Castor fiber"]]},
lu:{flora:[["Common rose","Rosa canina"],["European beech","Fagus sylvatica"],["English oak","Quercus robur"],["Bluebell","Hyacinthoides non-scripta"],["Grapevine","Vitis vinifera"]],
    fauna:[["Red fox","Vulpes vulpes"],["Roe deer","Capreolus capreolus"],["Eurasian badger","Meles meles"],["Wild boar","Sus scrofa"],["Black woodpecker","Dryocopus martius"]]},
mt:{flora:[["Maltese rock-centaury","Cheirolophus crassifolius"],["Olive tree","Olea europaea"],["Carob tree","Ceratonia siliqua"],["Aleppo pine","Pinus halepensis"],["Prickly pear","Opuntia ficus-indica"]],
    fauna:[["Blue rock thrush","Monticola solitarius"],["Loggerhead sea turtle","Caretta caretta"],["Mediterranean chameleon","Chamaeleo chamaeleon"],["Bottlenose dolphin","Tursiops truncatus"],["Maltese wall lizard","Podarcis filfolensis"]]},
md:{flora:[["Grapevine","Vitis vinifera"],["English oak","Quercus robur"],["Sunflower","Helianthus annuus"],["Walnut tree","Juglans regia"],["Small-leaved lime","Tilia cordata"]],
    fauna:[["Roe deer","Capreolus capreolus"],["Red deer","Cervus elaphus"],["White stork","Ciconia ciconia"],["Eurasian otter","Lutra lutra"],["Wild boar","Sus scrofa"]]},
mc:{flora:[["Olive tree","Olea europaea"],["Aleppo pine","Pinus halepensis"],["Lemon tree","Citrus limon"],["Agave","Agave americana"],["Carnation","Dianthus caryophyllus"]],
    fauna:[["Bottlenose dolphin","Tursiops truncatus"],["Peregrine falcon","Falco peregrinus"],["Loggerhead sea turtle","Caretta caretta"],["Yellow-legged gull","Larus michahellis"],["Moorish gecko","Tarentola mauritanica"]]},
me:{flora:[["Olive tree","Olea europaea"],["Bosnian pine","Pinus heldreichii"],["European beech","Fagus sylvatica"],["Sage","Salvia officinalis"],["Chestnut tree","Castanea sativa"]],
    fauna:[["Brown bear","Ursus arctos"],["Chamois","Rupicapra rupicapra"],["Golden eagle","Aquila chrysaetos"],["Dalmatian pelican","Pelecanus crispus"],["Grey wolf","Canis lupus"]]},
nl:{flora:[["Tulip","Tulipa gesneriana"],["English oak","Quercus robur"],["Common heather","Calluna vulgaris"],["Marram grass","Calamagrostis arenaria"],["European beech","Fagus sylvatica"]],
    fauna:[["Harbour seal","Phoca vitulina"],["Eurasian spoonbill","Platalea leucorodia"],["Red deer","Cervus elaphus"],["European hare","Lepus europaeus"],["Konik horse","Equus caballus"]]},
mk:{flora:[["Poppy","Papaver rhoeas"],["Macedonian pine","Pinus peuce"],["European beech","Fagus sylvatica"],["Oregano","Origanum vulgare"],["Chestnut tree","Castanea sativa"]],
    fauna:[["Balkan lynx","Lynx lynx"],["Brown bear","Ursus arctos"],["Ohrid trout","Salmo letnica"],["Golden eagle","Aquila chrysaetos"],["Grey wolf","Canis lupus"]]},
no:{flora:[["Norway spruce","Picea abies"],["Common heather","Calluna vulgaris"],["Cloudberry","Rubus chamaemorus"],["Downy birch","Betula pubescens"],["Scots pine","Pinus sylvestris"]],
    fauna:[["Moose","Alces alces"],["Reindeer","Rangifer tarandus"],["Polar bear","Ursus maritimus"],["Atlantic puffin","Fratercula arctica"],["Arctic fox","Vulpes lagopus"]]},
pl:{flora:[["Common poppy","Papaver rhoeas"],["Scots pine","Pinus sylvestris"],["English oak","Quercus robur"],["Silver birch","Betula pendula"],["Norway spruce","Picea abies"]],
    fauna:[["European bison","Bison bonasus"],["White stork","Ciconia ciconia"],["Grey wolf","Canis lupus"],["Eurasian lynx","Lynx lynx"],["Eurasian beaver","Castor fiber"]]},
pt:{flora:[["Cork oak","Quercus suber"],["Lavender","Lavandula stoechas"],["Olive tree","Olea europaea"],["Stone pine","Pinus pinea"],["Grapevine","Vitis vinifera"]],
    fauna:[["Iberian lynx","Lynx pardinus"],["Iberian wolf","Canis lupus"],["Bottlenose dolphin","Tursiops truncatus"],["Griffon vulture","Gyps fulvus"],["Iberian ibex","Capra pyrenaica"]]},
ro:{flora:[["Dog rose","Rosa canina"],["European beech","Fagus sylvatica"],["Norway spruce","Picea abies"],["Edelweiss","Leontopodium nivale"],["English oak","Quercus robur"]],
    fauna:[["Brown bear","Ursus arctos"],["Eurasian lynx","Lynx lynx"],["Grey wolf","Canis lupus"],["Great white pelican","Pelecanus onocrotalus"],["Chamois","Rupicapra rupicapra"]]},
ru:{flora:[["Silver birch","Betula pendula"],["Siberian larch","Larix sibirica"],["Siberian pine","Pinus sibirica"],["Chamomile","Matricaria chamomilla"],["Rowan","Sorbus aucuparia"]],
    fauna:[["Siberian tiger","Panthera tigris"],["Brown bear","Ursus arctos"],["Sable","Martes zibellina"],["Arctic fox","Vulpes lagopus"],["Beluga sturgeon","Huso huso"]]},
sm:{flora:[["Cyclamen","Cyclamen hederifolium"],["Holm oak","Quercus ilex"],["Olive tree","Olea europaea"],["Chestnut tree","Castanea sativa"],["Grapevine","Vitis vinifera"]],
    fauna:[["Peregrine falcon","Falco peregrinus"],["Red fox","Vulpes vulpes"],["European badger","Meles meles"],["Barn swallow","Hirundo rustica"],["Crested porcupine","Hystrix cristata"]]},
rs:{flora:[["Serbian spruce","Picea omorika"],["English oak","Quercus robur"],["Plum tree","Prunus domestica"],["European beech","Fagus sylvatica"],["Small-leaved lime","Tilia cordata"]],
    fauna:[["Grey wolf","Canis lupus"],["Brown bear","Ursus arctos"],["Eastern imperial eagle","Aquila heliaca"],["Red deer","Cervus elaphus"],["Eurasian otter","Lutra lutra"]]},
sk:{flora:[["Small-leaved lime","Tilia cordata"],["Norway spruce","Picea abies"],["European beech","Fagus sylvatica"],["Edelweiss","Leontopodium nivale"],["Scots pine","Pinus sylvestris"]],
    fauna:[["Brown bear","Ursus arctos"],["Eurasian lynx","Lynx lynx"],["Chamois","Rupicapra rupicapra"],["Golden eagle","Aquila chrysaetos"],["Grey wolf","Canis lupus"]]},
si:{flora:[["Carnation","Dianthus carthusianorum"],["Norway spruce","Picea abies"],["European beech","Fagus sylvatica"],["Edelweiss","Leontopodium nivale"],["Linden tree","Tilia platyphyllos"]],
    fauna:[["Brown bear","Ursus arctos"],["Olm","Proteus anguinus"],["Alpine ibex","Capra ibex"],["Eurasian lynx","Lynx lynx"],["Chamois","Rupicapra rupicapra"]]},
es:{flora:[["Olive tree","Olea europaea"],["Cork oak","Quercus suber"],["Carnation","Dianthus caryophyllus"],["Orange tree","Citrus sinensis"],["Holm oak","Quercus ilex"]],
    fauna:[["Iberian lynx","Lynx pardinus"],["Spanish imperial eagle","Aquila adalberti"],["Iberian ibex","Capra pyrenaica"],["Greater flamingo","Phoenicopterus roseus"],["Iberian wolf","Canis lupus"]]},
se:{flora:[["Norway spruce","Picea abies"],["Silver birch","Betula pendula"],["Lingonberry","Vaccinium vitis-idaea"],["Twinflower","Linnaea borealis"],["Scots pine","Pinus sylvestris"]],
    fauna:[["Moose","Alces alces"],["Brown bear","Ursus arctos"],["Reindeer","Rangifer tarandus"],["Eurasian lynx","Lynx lynx"],["Common blackbird","Turdus merula"]]},
ch:{flora:[["Edelweiss","Leontopodium nivale"],["Norway spruce","Picea abies"],["Gentian","Gentiana clusii"],["European larch","Larix decidua"],["Alpenrose","Rhododendron ferrugineum"]],
    fauna:[["Alpine ibex","Capra ibex"],["Alpine marmot","Marmota marmota"],["Chamois","Rupicapra rupicapra"],["Golden eagle","Aquila chrysaetos"],["Bearded vulture","Gypaetus barbatus"]]},
ua:{flora:[["Sunflower","Helianthus annuus"],["Guelder rose","Viburnum opulus"],["English oak","Quercus robur"],["Feather grass","Stipa capillata"],["Silver birch","Betula pendula"]],
    fauna:[["European bison","Bison bonasus"],["Grey wolf","Canis lupus"],["White stork","Ciconia ciconia"],["Brown bear","Ursus arctos"],["Steppe eagle","Aquila nipalensis"]]},
gb:{flora:[["English oak","Quercus robur"],["Dog rose","Rosa canina"],["Bluebell","Hyacinthoides non-scripta"],["Scots pine","Pinus sylvestris"],["Common holly","Ilex aquifolium"]],
    fauna:[["Red deer","Cervus elaphus"],["Red fox","Vulpes vulpes"],["European robin","Erithacus rubecula"],["Grey seal","Halichoerus grypus"],["European hedgehog","Erinaceus europaeus"]]},
va:{flora:[["Stone pine","Pinus pinea"],["Olive tree","Olea europaea"],["Cypress","Cupressus sempervirens"],["Holm oak","Quercus ilex"],["Laurel","Laurus nobilis"]],
    fauna:[["Rock dove","Columba livia"],["Peregrine falcon","Falco peregrinus"],["Common swift","Apus apus"],["Common kestrel","Falco tinnunculus"],["Italian wall lizard","Podarcis siculus"]]},

// ================= NORTH AMERICA =================
ag:{flora:[["Coconut palm","Cocos nucifera"],["Whitewood tree","Bucida buceras"],["Mangrove","Rhizophora mangle"],["Hibiscus","Hibiscus rosa-sinensis"],["Sea grape","Coccoloba uvifera"]],
    fauna:[["Frigatebird","Fregata magnificens"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Antiguan racer","Alsophis antiguae"],["Brown pelican","Pelecanus occidentalis"],["Green iguana","Iguana iguana"]]},
bs:{flora:[["Yellow elder","Tecoma stans"],["Coconut palm","Cocos nucifera"],["Mangrove","Rhizophora mangle"],["Lignum vitae","Guaiacum sanctum"],["Sea grape","Coccoloba uvifera"]],
    fauna:[["Caribbean flamingo","Phoenicopterus ruber"],["Bahama parrot","Amazona leucocephala"],["Green sea turtle","Chelonia mydas"],["Rock iguana","Cyclura cychlura"],["Bottlenose dolphin","Tursiops truncatus"]]},
bb:{flora:[["Pride of Barbados","Caesalpinia pulcherrima"],["Coconut palm","Cocos nucifera"],["Bearded fig tree","Ficus citrifolia"],["Mahogany","Swietenia mahagoni"],["Sugarcane","Saccharum officinarum"]],
    fauna:[["Green monkey","Chlorocebus sabaeus"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Barbados bullfinch","Loxigilla barbadensis"],["Brown pelican","Pelecanus occidentalis"],["Flying fish","Hirundichthys affinis"]]},
bz:{flora:[["Black orchid","Prosthechea cochleata"],["Mahogany","Swietenia macrophylla"],["Ceiba tree","Ceiba pentandra"],["Mangrove","Rhizophora mangle"],["Cohune palm","Attalea cohune"]],
    fauna:[["Baird's tapir","Tapirus bairdii"],["Jaguar","Panthera onca"],["Keel-billed toucan","Ramphastos sulfuratus"],["West Indian manatee","Trichechus manatus"],["Howler monkey","Alouatta pigra"]]},
ca:{flora:[["Sugar maple","Acer saccharum"],["White spruce","Picea glauca"],["Douglas fir","Pseudotsuga menziesii"],["Fireweed","Chamaenerion angustifolium"],["Trillium","Trillium grandiflorum"]],
    fauna:[["North American beaver","Castor canadensis"],["Moose","Alces alces"],["Canada goose","Branta canadensis"],["Polar bear","Ursus maritimus"],["Orca","Orcinus orca"]]},
cr:{flora:[["Guaria morada orchid","Guarianthe skinneri"],["Guanacaste tree","Enterolobium cyclocarpum"],["Coffee plant","Coffea arabica"],["Heliconia","Heliconia rostrata"],["Ceiba tree","Ceiba pentandra"]],
    fauna:[["Resplendent quetzal","Pharomachrus mocinno"],["Three-toed sloth","Bradypus variegatus"],["Red-eyed tree frog","Agalychnis callidryas"],["Scarlet macaw","Ara macao"],["Jaguar","Panthera onca"]]},
cu:{flora:[["Royal palm","Roystonea regia"],["Butterfly jasmine","Hedychium coronarium"],["Mahogany","Swietenia mahagoni"],["Tobacco plant","Nicotiana tabacum"],["Cork palm","Microcycas calocoma"]],
    fauna:[["Cuban trogon","Priotelus temnurus"],["Bee hummingbird","Mellisuga helenae"],["Cuban crocodile","Crocodylus rhombifer"],["West Indian manatee","Trichechus manatus"],["Cuban solenodon","Solenodon cubanus"]]},
dm:{flora:[["Carib wood","Sabinea carinalis"],["Coconut palm","Cocos nucifera"],["Gommier tree","Dacryodes excelsa"],["Heliconia","Heliconia caribaea"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Imperial amazon","Amazona imperialis"],["Red-necked amazon","Amazona arausiaca"],["Sperm whale","Physeter macrocephalus"],["Green iguana","Iguana delicatissima"],["Hawksbill sea turtle","Eretmochelys imbricata"]]},
do:{flora:[["Mahogany","Swietenia mahagoni"],["Royal palm","Roystonea hispaniolana"],["Bayahibe rose","Leuenbergeria quisqueyana"],["Coconut palm","Cocos nucifera"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Palmchat","Dulus dominicus"],["Rhinoceros iguana","Cyclura cornuta"],["Hispaniolan solenodon","Solenodon paradoxus"],["Humpback whale","Megaptera novaeangliae"],["American crocodile","Crocodylus acutus"]]},
sv:{flora:[["Izote","Yucca gigantea"],["Maquilishuat","Handroanthus impetiginosus"],["Coffee plant","Coffea arabica"],["Ceiba tree","Ceiba pentandra"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Turquoise-browed motmot","Eumomota superciliosa"],["Green sea turtle","Chelonia mydas"],["Ocelot","Leopardus pardalis"],["Howler monkey","Alouatta palliata"],["Green iguana","Iguana iguana"]]},
gd:{flora:[["Bougainvillea","Bougainvillea glabra"],["Nutmeg tree","Myristica fragrans"],["Coconut palm","Cocos nucifera"],["Cocoa tree","Theobroma cacao"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Grenada dove","Leptotila wellsi"],["Mona monkey","Cercopithecus mona"],["Leatherback sea turtle","Dermochelys coriacea"],["Green iguana","Iguana iguana"],["Brown pelican","Pelecanus occidentalis"]]},
gt:{flora:[["White nun orchid","Lycaste virginalis"],["Ceiba tree","Ceiba pentandra"],["Coffee plant","Coffea arabica"],["Maize","Zea mays"],["Mahogany","Swietenia macrophylla"]],
    fauna:[["Resplendent quetzal","Pharomachrus mocinno"],["Jaguar","Panthera onca"],["Baird's tapir","Tapirus bairdii"],["Scarlet macaw","Ara macao"],["Howler monkey","Alouatta pigra"]]},
ht:{flora:[["Hispaniolan mahogany","Swietenia mahagoni"],["Royal palm","Roystonea hispaniolana"],["Coconut palm","Cocos nucifera"],["Mango tree","Mangifera indica"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Hispaniolan trogon","Priotelus roseigaster"],["Rhinoceros iguana","Cyclura cornuta"],["Hispaniolan solenodon","Solenodon paradoxus"],["American crocodile","Crocodylus acutus"],["Hispaniolan parakeet","Psittacara chloropterus"]]},
hn:{flora:[["Orchid","Rhyncholaelia digbyana"],["Caribbean pine","Pinus caribaea"],["Mahogany","Swietenia macrophylla"],["Coffee plant","Coffea arabica"],["Ceiba tree","Ceiba pentandra"]],
    fauna:[["Scarlet macaw","Ara macao"],["Jaguar","Panthera onca"],["Baird's tapir","Tapirus bairdii"],["Whale shark","Rhincodon typus"],["White-throated capuchin","Cebus capucinus"]]},
jm:{flora:[["Lignum vitae","Guaiacum officinale"],["Blue mahoe","Talipariti elatum"],["Coconut palm","Cocos nucifera"],["Coffee plant","Coffea arabica"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Red-billed streamertail","Trochilus polytmus"],["Jamaican iguana","Cyclura collei"],["American crocodile","Crocodylus acutus"],["Jamaican giant swallowtail","Papilio homerus"],["Jamaican boa","Chilabothrus subflavus"]]},
mx:{flora:[["Dahlia","Dahlia pinnata"],["Agave","Agave americana"],["Prickly pear","Opuntia ficus-indica"],["Vanilla orchid","Vanilla planifolia"],["Montezuma cypress","Taxodium mucronatum"]],
    fauna:[["Golden eagle","Aquila chrysaetos"],["Jaguar","Panthera onca"],["Axolotl","Ambystoma mexicanum"],["Monarch butterfly","Danaus plexippus"],["Coyote","Canis latrans"]]},
ni:{flora:[["Sacuanjoche","Plumeria rubra"],["Ceiba tree","Ceiba pentandra"],["Coffee plant","Coffea arabica"],["Mahogany","Swietenia macrophylla"],["Mangrove","Rhizophora mangle"]],
    fauna:[["Turquoise-browed motmot","Eumomota superciliosa"],["Jaguar","Panthera onca"],["Bull shark","Carcharhinus leucas"],["Howler monkey","Alouatta palliata"],["Green sea turtle","Chelonia mydas"]]},
pa:{flora:[["Holy Ghost orchid","Peristeria elata"],["Ceiba tree","Ceiba pentandra"],["Coffee plant","Coffea arabica"],["Mangrove","Rhizophora mangle"],["Heliconia","Heliconia rostrata"]],
    fauna:[["Harpy eagle","Harpia harpyja"],["Geoffroy's tamarin","Saguinus geoffroyi"],["Three-toed sloth","Bradypus variegatus"],["Jaguar","Panthera onca"],["Golden frog","Atelopus zeteki"]]},
kn:{flora:[["Poinciana","Delonix regia"],["Coconut palm","Cocos nucifera"],["Sugarcane","Saccharum officinarum"],["Mangrove","Rhizophora mangle"],["Hibiscus","Hibiscus rosa-sinensis"]],
    fauna:[["Green vervet monkey","Chlorocebus sabaeus"],["Brown pelican","Pelecanus occidentalis"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Green iguana","Iguana iguana"],["Magnificent frigatebird","Fregata magnificens"]]},
lc:{flora:[["Heliconia","Heliconia caribaea"],["Coconut palm","Cocos nucifera"],["Calabash tree","Crescentia cujete"],["Mangrove","Rhizophora mangle"],["Banana plant","Musa acuminata"]],
    fauna:[["Saint Lucia amazon","Amazona versicolor"],["Saint Lucia whiptail","Cnemidophorus vanzoi"],["Leatherback sea turtle","Dermochelys coriacea"],["Green iguana","Iguana iguana"],["Brown pelican","Pelecanus occidentalis"]]},
vc:{flora:[["Soufriere tree","Spachea perforata"],["Coconut palm","Cocos nucifera"],["Breadfruit tree","Artocarpus altilis"],["Mangrove","Rhizophora mangle"],["Banana plant","Musa acuminata"]],
    fauna:[["Saint Vincent amazon","Amazona guildingii"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Green iguana","Iguana iguana"],["Brown pelican","Pelecanus occidentalis"],["Humpback whale","Megaptera novaeangliae"]]},
tt:{flora:[["Chaconia","Warszewiczia coccinea"],["Coconut palm","Cocos nucifera"],["Mangrove","Rhizophora mangle"],["Cocoa tree","Theobroma cacao"],["Immortelle tree","Erythrina poeppigiana"]],
    fauna:[["Scarlet ibis","Eudocimus ruber"],["Cocrico","Ortalis ruficauda"],["Leatherback sea turtle","Dermochelys coriacea"],["Red howler monkey","Alouatta seniculus"],["Ocelot","Leopardus pardalis"]]},
us:{flora:[["Giant sequoia","Sequoiadendron giganteum"],["Saguaro cactus","Carnegiea gigantea"],["Coast redwood","Sequoia sempervirens"],["Sugar maple","Acer saccharum"],["Sunflower","Helianthus annuus"]],
    fauna:[["Bald eagle","Haliaeetus leucocephalus"],["American bison","Bison bison"],["Grizzly bear","Ursus arctos"],["White-tailed deer","Odocoileus virginianus"],["American alligator","Alligator mississippiensis"]]},

// ================= SOUTH AMERICA =================
ar:{flora:[["Ceibo","Erythrina crista-galli"],["Ombú","Phytolacca dioica"],["Yerba mate","Ilex paraguariensis"],["Monkey puzzle tree","Araucaria araucana"],["Jacaranda","Jacaranda mimosifolia"]],
    fauna:[["Puma","Puma concolor"],["Guanaco","Lama guanicoe"],["Greater rhea","Rhea americana"],["Magellanic penguin","Spheniscus magellanicus"],["Capybara","Hydrochoerus hydrochaeris"]]},
bo:{flora:[["Kantuta","Cantua buxifolia"],["Quinoa","Chenopodium quinoa"],["Coca plant","Erythroxylum coca"],["Brazil nut tree","Bertholletia excelsa"],["Puya raimondii","Puya raimondii"]],
    fauna:[["Andean condor","Vultur gryphus"],["Llama","Lama glama"],["Alpaca","Vicugna pacos"],["Spectacled bear","Tremarctos ornatus"],["Vicuña","Vicugna vicugna"]]},
br:{flora:[["Brazil nut tree","Bertholletia excelsa"],["Rubber tree","Hevea brasiliensis"],["Ipê tree","Handroanthus albus"],["Açaí palm","Euterpe oleracea"],["Passionflower","Passiflora edulis"]],
    fauna:[["Jaguar","Panthera onca"],["Toco toucan","Ramphastos toco"],["Capybara","Hydrochoerus hydrochaeris"],["Hyacinth macaw","Anodorhynchus hyacinthinus"],["Giant anteater","Myrmecophaga tridactyla"]]},
cl:{flora:[["Copihue","Lapageria rosea"],["Monkey puzzle tree","Araucaria araucana"],["Alerce","Fitzroya cupressoides"],["Chilean palm","Jubaea chilensis"],["Grapevine","Vitis vinifera"]],
    fauna:[["Andean condor","Vultur gryphus"],["Guanaco","Lama guanicoe"],["Humboldt penguin","Spheniscus humboldti"],["Pudú","Pudu puda"],["Chilean flamingo","Phoenicopterus chilensis"]]},
co:{flora:[["May flower orchid","Cattleya trianae"],["Wax palm","Ceroxylon quindiuense"],["Coffee plant","Coffea arabica"],["Heliconia","Heliconia rostrata"],["Frailejón","Espeletia grandiflora"]],
    fauna:[["Andean condor","Vultur gryphus"],["Spectacled bear","Tremarctos ornatus"],["Cotton-top tamarin","Saguinus oedipus"],["Pink river dolphin","Inia geoffrensis"],["Jaguar","Panthera onca"]]},
ec:{flora:[["Rose","Rosa chinensis"],["Cinchona tree","Cinchona pubescens"],["Cacao tree","Theobroma cacao"],["Frailejón","Espeletia pycnophylla"],["Balsa tree","Ochroma pyramidale"]],
    fauna:[["Galápagos giant tortoise","Chelonoidis niger"],["Marine iguana","Amblyrhynchus cristatus"],["Blue-footed booby","Sula nebouxii"],["Andean condor","Vultur gryphus"],["Galápagos penguin","Spheniscus mendiculus"]]},
gy:{flora:[["Victoria water lily","Victoria amazonica"],["Greenheart","Chlorocardium rodiei"],["Mora tree","Mora excelsa"],["Kapok tree","Ceiba pentandra"],["Heliconia","Heliconia psittacorum"]],
    fauna:[["Giant river otter","Pteronura brasiliensis"],["Hoatzin","Opisthocomus hoazin"],["Harpy eagle","Harpia harpyja"],["Jaguar","Panthera onca"],["Giant anteater","Myrmecophaga tridactyla"]]},
py:{flora:[["Yerba mate","Ilex paraguariensis"],["Lapacho","Handroanthus impetiginosus"],["Coconut palm","Acrocomia aculeata"],["Jacaranda","Jacaranda mimosifolia"],["Water lily","Victoria cruziana"]],
    fauna:[["Jaguar","Panthera onca"],["Giant anteater","Myrmecophaga tridactyla"],["Capybara","Hydrochoerus hydrochaeris"],["Greater rhea","Rhea americana"],["Maned wolf","Chrysocyon brachyurus"]]},
pe:{flora:[["Cantuta","Cantua buxifolia"],["Cinchona tree","Cinchona officinalis"],["Potato","Solanum tuberosum"],["Puya raimondii","Puya raimondii"],["Quinoa","Chenopodium quinoa"]],
    fauna:[["Vicuña","Vicugna vicugna"],["Andean condor","Vultur gryphus"],["Llama","Lama glama"],["Andean cock-of-the-rock","Rupicola peruvianus"],["Pink river dolphin","Inia geoffrensis"]]},
sr:{flora:[["Faya lobi","Ixora coccinea"],["Greenheart","Chlorocardium rodiei"],["Kapok tree","Ceiba pentandra"],["Mora tree","Mora excelsa"],["Heliconia","Heliconia psittacorum"]],
    fauna:[["Leatherback sea turtle","Dermochelys coriacea"],["Giant river otter","Pteronura brasiliensis"],["Jaguar","Panthera onca"],["Scarlet ibis","Eudocimus ruber"],["Harpy eagle","Harpia harpyja"]]},
uy:{flora:[["Ceibo","Erythrina crista-galli"],["Ombú","Phytolacca dioica"],["Yerba mate","Ilex paraguariensis"],["Eucalyptus","Eucalyptus globulus"],["Pampas grass","Cortaderia selloana"]],
    fauna:[["Capybara","Hydrochoerus hydrochaeris"],["Greater rhea","Rhea americana"],["Southern right whale","Eubalaena australis"],["Pampas deer","Ozotoceros bezoarticus"],["South American sea lion","Otaria flavescens"]]},
ve:{flora:[["May flower orchid","Cattleya mossiae"],["Araguaney","Handroanthus chrysanthus"],["Coffee plant","Coffea arabica"],["Kapok tree","Ceiba pentandra"],["Heliconia","Heliconia rostrata"]],
    fauna:[["Troupial","Icterus icterus"],["Capybara","Hydrochoerus hydrochaeris"],["Giant anteater","Myrmecophaga tridactyla"],["Orinoco crocodile","Crocodylus intermedius"],["Scarlet ibis","Eudocimus ruber"]]},

// ================= OCEANIA =================
au:{flora:[["Golden wattle","Acacia pycnantha"],["Eucalyptus","Eucalyptus globulus"],["Bottlebrush","Callistemon citrinus"],["Banksia","Banksia serrata"],["Macadamia","Macadamia integrifolia"]],
    fauna:[["Red kangaroo","Osphranter rufus"],["Koala","Phascolarctos cinereus"],["Platypus","Ornithorhynchus anatinus"],["Emu","Dromaius novaehollandiae"],["Wombat","Vombatus ursinus"]]},
fj:{flora:[["Tagimoucia","Medinilla waterhousei"],["Coconut palm","Cocos nucifera"],["Hibiscus","Hibiscus rosa-sinensis"],["Mangrove","Rhizophora stylosa"],["Breadfruit tree","Artocarpus altilis"]],
    fauna:[["Fiji banded iguana","Brachylophus fasciatus"],["Collared lory","Phigys solitarius"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Fijian flying fox","Pteropus tonganus"],["Humphead wrasse","Cheilinus undulatus"]]},
ki:{flora:[["Coconut palm","Cocos nucifera"],["Screwpine","Pandanus tectorius"],["Breadfruit tree","Artocarpus altilis"],["Beach naupaka","Scaevola taccada"],["Giant swamp taro","Cyrtosperma merkusii"]],
    fauna:[["Great frigatebird","Fregata minor"],["Coconut crab","Birgus latro"],["Green sea turtle","Chelonia mydas"],["Red-tailed tropicbird","Phaethon rubricauda"],["Bristle-thighed curlew","Numenius tahitiensis"]]},
mh:{flora:[["Coconut palm","Cocos nucifera"],["Screwpine","Pandanus tectorius"],["Breadfruit tree","Artocarpus altilis"],["Beach naupaka","Scaevola taccada"],["Mangrove","Bruguiera gymnorhiza"]],
    fauna:[["Green sea turtle","Chelonia mydas"],["Coconut crab","Birgus latro"],["Grey reef shark","Carcharhinus amblyrhynchos"],["Great frigatebird","Fregata minor"],["Giant clam","Tridacna gigas"]]},
fm:{flora:[["Coconut palm","Cocos nucifera"],["Betel nut palm","Areca catechu"],["Breadfruit tree","Artocarpus altilis"],["Mangrove","Rhizophora apiculata"],["Screwpine","Pandanus tectorius"]],
    fauna:[["Micronesian kingfisher","Todiramphus cinnamominus"],["Coconut crab","Birgus latro"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Manta ray","Mobula alfredi"],["Pacific flying fox","Pteropus mariannus"]]},
nr:{flora:[["Coconut palm","Cocos nucifera"],["Screwpine","Pandanus tectorius"],["Tomano tree","Calophyllum inophyllum"],["Beach naupaka","Scaevola taccada"],["Frangipani","Plumeria rubra"]],
    fauna:[["Nauru reed warbler","Acrocephalus rehsei"],["Great frigatebird","Fregata minor"],["Brown noddy","Anous stolidus"],["Coconut crab","Birgus latro"],["Green sea turtle","Chelonia mydas"]]},
nz:{flora:[["Silver fern","Alsophila dealbata"],["Pōhutukawa","Metrosideros excelsa"],["Kauri","Agathis australis"],["Mānuka","Leptospermum scoparium"],["Cabbage tree","Cordyline australis"]],
    fauna:[["Kiwi","Apteryx mantelli"],["Kea","Nestor notabilis"],["Tuatara","Sphenodon punctatus"],["Hector's dolphin","Cephalorhynchus hectori"],["Little penguin","Eudyptula minor"]]},
pw:{flora:[["Coconut palm","Cocos nucifera"],["Mangrove","Rhizophora apiculata"],["Screwpine","Pandanus tectorius"],["Betel nut palm","Areca catechu"],["Breadfruit tree","Artocarpus altilis"]],
    fauna:[["Palau fruit dove","Ptilinopus pelewensis"],["Saltwater crocodile","Crocodylus porosus"],["Dugong","Dugong dugon"],["Golden jellyfish","Mastigias papua"],["Hawksbill sea turtle","Eretmochelys imbricata"]]},
pg:{flora:[["Sago palm","Metroxylon sagu"],["Orchid","Dendrobium lasianthera"],["Klinkii pine","Araucaria hunsteinii"],["Breadfruit tree","Artocarpus altilis"],["Mangrove","Rhizophora apiculata"]],
    fauna:[["Raggiana bird-of-paradise","Paradisaea raggiana"],["Tree kangaroo","Dendrolagus goodfellowi"],["Southern cassowary","Casuarius casuarius"],["Spotted cuscus","Spilocuscus maculatus"],["Blyth's hornbill","Rhyticeros plicatus"]]},
ws:{flora:[["Teuila","Alpinia purpurata"],["Coconut palm","Cocos nucifera"],["Breadfruit tree","Artocarpus altilis"],["Banyan tree","Ficus obliqua"],["Screwpine","Pandanus tectorius"]],
    fauna:[["Tooth-billed pigeon","Didunculus strigirostris"],["Samoan flying fox","Pteropus samoensis"],["Green sea turtle","Chelonia mydas"],["Pacific boa","Candoia bibroni"],["Humpback whale","Megaptera novaeangliae"]]},
sb:{flora:[["Coconut palm","Cocos nucifera"],["Hibiscus","Hibiscus rosa-sinensis"],["Ngali nut tree","Canarium indicum"],["Mangrove","Rhizophora apiculata"],["Breadfruit tree","Artocarpus altilis"]],
    fauna:[["Solomons cockatoo","Cacatua ducorpsii"],["Saltwater crocodile","Crocodylus porosus"],["Coconut crab","Birgus latro"],["Prehensile-tailed skink","Corucia zebrata"],["Hawksbill sea turtle","Eretmochelys imbricata"]]},
to:{flora:[["Heilala","Garcinia sessilis"],["Coconut palm","Cocos nucifera"],["Screwpine","Pandanus tectorius"],["Banyan tree","Ficus obliqua"],["Breadfruit tree","Artocarpus altilis"]],
    fauna:[["Humpback whale","Megaptera novaeangliae"],["Tongan flying fox","Pteropus tonganus"],["Blue-crowned lorikeet","Vini australis"],["Green sea turtle","Chelonia mydas"],["Banded iguana","Brachylophus fasciatus"]]},
tv:{flora:[["Coconut palm","Cocos nucifera"],["Screwpine","Pandanus tectorius"],["Beach naupaka","Scaevola taccada"],["Giant swamp taro","Cyrtosperma merkusii"],["Tomano tree","Calophyllum inophyllum"]],
    fauna:[["Green sea turtle","Chelonia mydas"],["Coconut crab","Birgus latro"],["Great frigatebird","Fregata minor"],["Brown noddy","Anous stolidus"],["Reef manta ray","Mobula alfredi"]]},
vu:{flora:[["Coconut palm","Cocos nucifera"],["Banyan tree","Ficus prolixa"],["Screwpine","Pandanus tectorius"],["Kava","Piper methysticum"],["Breadfruit tree","Artocarpus altilis"]],
    fauna:[["Vanuatu flying fox","Pteropus anetianus"],["Dugong","Dugong dugon"],["Coconut crab","Birgus latro"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Vanuatu megapode","Megapodius layardi"]]}
});

// ---- Iconic species → country (verified: each species' top GBIF country) ----
const FF_ICONIC = [
  ["giant panda","Ailuropoda melanoleuca","China"],["red kangaroo","Osphranter rufus","Australia"],
  ["kiwi","Apteryx mantelli","New Zealand"],["Bengal tiger","Panthera tigris","India"],
  ["bald eagle","Haliaeetus leucocephalus","United States"],["North American beaver","Castor canadensis","Canada"],
  ["axolotl","Ambystoma mexicanum","Mexico"],["Japanese macaque","Macaca fuscata","Japan"],
  ["ring-tailed lemur","Lemur catta","Madagascar"],["Komodo dragon","Varanus komodoensis","Indonesia"],
  ["Iberian lynx","Lynx pardinus","Spain"],["koala","Phascolarctos cinereus","Australia"],
  ["Raggiana bird-of-paradise","Paradisaea raggiana","Papua New Guinea"],["silver fern","Alsophila dealbata","New Zealand"],
  ["golden wattle","Acacia pycnantha","Australia"],["toco toucan","Ramphastos toco","Brazil"],
  ["platypus","Ornithorhynchus anatinus","Australia"],["okapi","Okapia johnstoni","DR Congo"],
  ["resplendent quetzal","Pharomachrus mocinno","Guatemala and Costa Rica"],
  ["Philippine eagle","Pithecophaga jefferyi","the Philippines"],
  ["Galápagos giant tortoise","Chelonoidis niger","Ecuador"],["giant sequoia","Sequoiadendron giganteum","United States"],
  ["Przewalski's horse","Equus przewalskii","Mongolia"],["dragon blood tree","Dracaena cinnabari","Yemen"]
];

LESSONS[13].florafauna = {
  title: "Flora & Fauna of the World", emoji: "🌿",
  intro: "Flora means plants; fauna means animals. Every country below lists 5 plants and 5 animals that really live there — each one checked against real wildlife records from scientists around the world.",
  learn: [
    "FLORA = the plant life of a place (trees, flowers, crops). FAUNA = the animal life. Remember: FLOWERS are flora, FURRY things are fauna!",
    "Every living thing has a scientific name in Latin, used by scientists everywhere. A lion is Panthera leo in every language on Earth!",
    "Species live where the climate and habitat suit them — which is why neighbouring countries often share wildlife, but islands can be completely different. The Philippines has no orangutans even though nearby Borneo does!",
    "Endemic means found nowhere else on Earth — like Madagascar's lemurs, New Zealand's kiwi, and the Philippine eagle."
  ],
  activity: "🔎 Backyard Biologist: Make a flora & fauna list for YOUR home — 5 plants and 5 animals you can find in your own neighbourhood. Try to find one scientific name. You just did real field science!",
  floraFauna: true
};
