// BrightSprouts Academy — General Knowledge: Flora & Fauna of the World
// Per-country lists. Each species: [common name, scientific name].
// Chosen from national symbols + genuinely native/characteristic species,
// and machine-verified against GBIF occurrence records for that country.
const FF_COUNTRY = {
// ================= AFRICA =================
dz:{flora:[["Date palm","Phoenix dactylifera"],["Olive tree","Olea europaea"],["Atlas cedar","Cedrus atlantica"],["Aleppo pine","Pinus halepensis"],["Esparto grass","Macrochloa tenacissima"]],
    fauna:[["Fennec fox","Vulpes zerda"],["Dromedary camel","Camelus dromedarius"],["Barbary macaque","Macaca sylvanus"],["Barbary sheep","Ammotragus lervia"],["Golden jackal","Canis aureus"]]},
ao:{flora:[["Baobab","Adansonia digitata"],["Welwitschia","Welwitschia mirabilis"],["Mopane","Colophospermum mopane"],["Marula","Sclerocarya birrea"],["Oil palm","Elaeis guineensis"]],
    fauna:[["Giant sable antelope","Hippotragus niger"],["African elephant","Loxodonta africana"],["Red-crested turaco","Tauraco erythrolophus"],["African wild dog","Lycaon pictus"],["Nile crocodile","Crocodylus niloticus"]]},
bj:{flora:[["Baobab","Adansonia digitata"],["Oil palm","Elaeis guineensis"],["Shea tree","Vitellaria paradoxa"],["Kola nut tree","Cola nitida"],["Raffia palm","Raphia hookeri"]],
    fauna:[["West African lion","Panthera leo"],["Hippopotamus","Hippopotamus amphibius"],["African buffalo","Syncerus caffer"],["Nile crocodile","Crocodylus niloticus"],["Senegal parrot","Poicephalus senegalus"]]},
bw:{flora:[["Baobab","Adansonia digitata"],["Mopane","Colophospermum mopane"],["Camel thorn","Vachellia erioloba"],["Marula","Sclerocarya birrea"],["Devil's claw","Harpagophytum procumbens"]],
    fauna:[["African elephant","Loxodonta africana"],["Plains zebra","Equus quagga"],["Meerkat","Suricata suricatta"],["Lion","Panthera leo"],["African wild dog","Lycaon pictus"]]},
bf:{flora:[["Shea tree","Vitellaria paradoxa"],["Baobab","Adansonia digitata"],["Néré tree","Parkia biglobosa"],["Tamarind","Tamarindus indica"],["Acacia","Vachellia nilotica"]],
    fauna:[["African elephant","Loxodonta africana"],["Hippopotamus","Hippopotamus amphibius"],["Roan antelope","Hippotragus equinus"],["Warthog","Phacochoerus africanus"],["Abyssinian roller","Coracias abyssinicus"]]},
bi:{flora:[["Oil palm","Elaeis guineensis"],["Coffee plant","Coffea arabica"],["Banana plant","Musa acuminata"],["Papyrus","Cyperus papyrus"],["Albizia","Albizia gummifera"]],
    fauna:[["Hippopotamus","Hippopotamus amphibius"],["Chimpanzee","Pan troglodytes"],["African fish eagle","Icthyophaga vocifer"],["Nile crocodile","Crocodylus niloticus"],["Grey crowned crane","Balearica regulorum"]]},
cv:{flora:[["Dragon tree","Dracaena draco"],["Coconut palm","Cocos nucifera"],["Sugarcane","Saccharum officinarum"],["Prickly pear","Opuntia ficus-indica"],["Tamarind","Tamarindus indica"]],
    fauna:[["Loggerhead sea turtle","Caretta caretta"],["Cape Verde shearwater","Calonectris edwardsii"],["Humpback whale","Megaptera novaeangliae"],["Grey-headed kingfisher","Halcyon leucocephala"],["Bottlenose dolphin","Tursiops truncatus"]]},
cm:{flora:[["African mahogany","Khaya anthotheca"],["Oil palm","Elaeis guineensis"],["Ebony tree","Diospyros crassiflora"],["Cocoa tree","Theobroma cacao"],["Raffia palm","Raphia farinifera"]],
    fauna:[["Western gorilla","Gorilla gorilla"],["Forest elephant","Loxodonta cyclotis"],["Mandrill","Mandrillus sphinx"],["Chimpanzee","Pan troglodytes"],["Grey parrot","Psittacus erithacus"]]},
cf:{flora:[["African mahogany","Khaya anthotheca"],["Oil palm","Elaeis guineensis"],["Kapok tree","Ceiba pentandra"],["Sapele","Entandrophragma cylindricum"],["Coffee plant","Coffea canephora"]],
    fauna:[["Western gorilla","Gorilla gorilla"],["Forest elephant","Loxodonta cyclotis"],["Bongo","Tragelaphus eurycerus"],["Chimpanzee","Pan troglodytes"],["Nile crocodile","Crocodylus niloticus"]]},
td:{flora:[["Date palm","Phoenix dactylifera"],["Baobab","Adansonia digitata"],["Doum palm","Hyphaene thebaica"],["Acacia","Vachellia nilotica"],["Papyrus","Cyperus papyrus"]],
    fauna:[["Addax","Addax nasomaculatus"],["Dorcas gazelle","Gazella dorcas"],["African elephant","Loxodonta africana"],["Hippopotamus","Hippopotamus amphibius"],["Ostrich","Struthio camelus"]]},
km:{flora:[["Ylang-ylang","Cananga odorata"],["Coconut palm","Cocos nucifera"],["Vanilla orchid","Vanilla planifolia"],["Clove tree","Syzygium aromaticum"],["Banana plant","Musa acuminata"]],
    fauna:[["Livingstone's fruit bat","Pteropus livingstonii"],["Green sea turtle","Chelonia mydas"],["Coelacanth","Latimeria chalumnae"],["Humpback whale","Megaptera novaeangliae"],["Comoro blue pigeon","Alectroenas sganzini"]]},
cg:{flora:[["Okoumé","Aucoumea klaineana"],["Oil palm","Elaeis guineensis"],["Kapok tree","Ceiba pentandra"],["Limba tree","Terminalia superba"],["Sapele","Entandrophragma cylindricum"]],
    fauna:[["Western gorilla","Gorilla gorilla"],["Forest elephant","Loxodonta cyclotis"],["Chimpanzee","Pan troglodytes"],["Mandrill","Mandrillus sphinx"],["Grey parrot","Psittacus erithacus"]]},
cd:{flora:[["African mahogany","Khaya anthotheca"],["Oil palm","Elaeis guineensis"],["Ebony tree","Diospyros crassiflora"],["Kapok tree","Ceiba pentandra"],["Giant lobelia","Lobelia deckenii"]],
    fauna:[["Okapi","Okapia johnstoni"],["Eastern gorilla","Gorilla beringei"],["Bonobo","Pan paniscus"],["Forest elephant","Loxodonta cyclotis"],["Congo peafowl","Afropavo congensis"]]},
ci:{flora:[["Cocoa tree","Theobroma cacao"],["Oil palm","Elaeis guineensis"],["Kola nut tree","Cola nitida"],["Kapok tree","Ceiba pentandra"],["Coffee plant","Coffea canephora"]],
    fauna:[["Chimpanzee","Pan troglodytes"],["Pygmy hippopotamus","Choeropsis liberiensis"],["African elephant","Loxodonta africana"],["Bongo","Tragelaphus eurycerus"],["Grey parrot","Psittacus erithacus"]]},
dj:{flora:[["Doum palm","Hyphaene thebaica"],["Date palm","Phoenix dactylifera"],["Acacia","Vachellia tortilis"],["Boswellia","Boswellia sacra"],["Mangrove","Avicennia marina"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Beira antelope","Dorcatragus megalotis"],["Djibouti francolin","Pternistis ochropectus"],["Whale shark","Rhincodon typus"],["Hamadryas baboon","Papio hamadryas"]]},
eg:{flora:[["Papyrus","Cyperus papyrus"],["Date palm","Phoenix dactylifera"],["Blue lotus","Nymphaea nouchali"],["Doum palm","Hyphaene thebaica"],["Sycamore fig","Ficus sycomorus"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Nile crocodile","Crocodylus niloticus"],["Egyptian vulture","Neophron percnopterus"],["Fennec fox","Vulpes zerda"],["Egyptian goose","Alopochen aegyptiaca"]]},
gq:{flora:[["Oil palm","Elaeis guineensis"],["Cocoa tree","Theobroma cacao"],["Kapok tree","Ceiba pentandra"],["Okoumé","Aucoumea klaineana"],["Coffee plant","Coffea canephora"]],
    fauna:[["Western gorilla","Gorilla gorilla"],["Mandrill","Mandrillus sphinx"],["Forest elephant","Loxodonta cyclotis"],["Leatherback sea turtle","Dermochelys coriacea"],["Grey parrot","Psittacus erithacus"]]},
er:{flora:[["Doum palm","Hyphaene thebaica"],["Acacia","Vachellia tortilis"],["Olive tree","Olea europaea"],["Boswellia","Boswellia papyrifera"],["Dragon tree","Dracaena ombet"]],
    fauna:[["African wild ass","Equus africanus"],["Dorcas gazelle","Gazella dorcas"],["Hamadryas baboon","Papio hamadryas"],["Ostrich","Struthio camelus"],["Dromedary camel","Camelus dromedarius"]]},
sz:{flora:[["Marula","Sclerocarya birrea"],["Aloe","Aloe marlothii"],["Coral tree","Erythrina lysistemon"],["Cycad","Encephalartos lebomboensis"],["Acacia","Vachellia karroo"]],
    fauna:[["White rhinoceros","Ceratotherium simum"],["African elephant","Loxodonta africana"],["Blue wildebeest","Connochaetes taurinus"],["Nile crocodile","Crocodylus niloticus"],["Purple-crested turaco","Gallirex porphyreolophus"]]},
et:{flora:[["Coffee plant","Coffea arabica"],["Teff","Eragrostis tef"],["Giant lobelia","Lobelia rhynchopetalum"],["African juniper","Juniperus procera"],["Enset","Ensete ventricosum"]],
    fauna:[["Ethiopian wolf","Canis simensis"],["Gelada","Theropithecus gelada"],["Walia ibex","Capra walie"],["Hamadryas baboon","Papio hamadryas"],["Lion","Panthera leo"]]},
ga:{flora:[["Okoumé","Aucoumea klaineana"],["Oil palm","Elaeis guineensis"],["Kapok tree","Ceiba pentandra"],["Ebony tree","Diospyros crassiflora"],["Padouk","Pterocarpus soyauxii"]],
    fauna:[["Western gorilla","Gorilla gorilla"],["Forest elephant","Loxodonta cyclotis"],["Mandrill","Mandrillus sphinx"],["Leatherback sea turtle","Dermochelys coriacea"],["Chimpanzee","Pan troglodytes"]]},
gm:{flora:[["Oil palm","Elaeis guineensis"],["Baobab","Adansonia digitata"],["Mangrove","Rhizophora racemosa"],["Rhun palm","Borassus aethiopum"],["Groundnut","Arachis hypogaea"]],
    fauna:[["Hippopotamus","Hippopotamus amphibius"],["West African manatee","Trichechus senegalensis"],["Guinea baboon","Papio papio"],["African fish eagle","Icthyophaga vocifer"],["Nile crocodile","Crocodylus niloticus"]]},
gh:{flora:[["Cocoa tree","Theobroma cacao"],["Oil palm","Elaeis guineensis"],["Kola nut tree","Cola nitida"],["Kapok tree","Ceiba pentandra"],["Shea tree","Vitellaria paradoxa"]],
    fauna:[["African elephant","Loxodonta africana"],["Chimpanzee","Pan troglodytes"],["Mona monkey","Cercopithecus mona"],["Nile crocodile","Crocodylus niloticus"],["Grey parrot","Psittacus erithacus"]]},
gn:{flora:[["Oil palm","Elaeis guineensis"],["Kola nut tree","Cola nitida"],["Mango tree","Mangifera indica"],["Kapok tree","Ceiba pentandra"],["Rice","Oryza glaberrima"]],
    fauna:[["Western chimpanzee","Pan troglodytes"],["Hippopotamus","Hippopotamus amphibius"],["Diana monkey","Cercopithecus diana"],["Guinea baboon","Papio papio"],["Western red colobus","Piliocolobus badius"]]},
gw:{flora:[["Oil palm","Elaeis guineensis"],["Mangrove","Rhizophora racemosa"],["Cashew tree","Anacardium occidentale"],["Baobab","Adansonia digitata"],["Rice","Oryza glaberrima"]],
    fauna:[["Hippopotamus","Hippopotamus amphibius"],["Chimpanzee","Pan troglodytes"],["Green sea turtle","Chelonia mydas"],["African manatee","Trichechus senegalensis"],["Guinea baboon","Papio papio"]]},
ke:{flora:[["Umbrella thorn acacia","Vachellia tortilis"],["Baobab","Adansonia digitata"],["Coffee plant","Coffea arabica"],["Tea plant","Camellia sinensis"],["Papyrus","Cyperus papyrus"]],
    fauna:[["Lion","Panthera leo"],["African elephant","Loxodonta africana"],["Masai giraffe","Giraffa tippelskirchi"],["Plains zebra","Equus quagga"],["Lesser flamingo","Phoeniconaias minor"]]},
ls:{flora:[["Spiral aloe","Aloe polyphylla"],["Cape willow","Salix mucronata"],["Red-hot poker","Kniphofia caulescens"],["Everlasting flower","Helichrysum trilineatum"],["Sorghum","Sorghum bicolor"]],
    fauna:[["Eland","Taurotragus oryx"],["Bearded vulture","Gypaetus barbatus"],["Rock hyrax","Procavia capensis"],["Black-backed jackal","Lupulella mesomelas"],["Southern bald ibis","Geronticus calvus"]]},
lr:{flora:[["Oil palm","Elaeis guineensis"],["Rubber tree","Hevea brasiliensis"],["Kapok tree","Ceiba pentandra"],["Kola nut tree","Cola nitida"],["Mahogany","Khaya ivorensis"]],
    fauna:[["Pygmy hippopotamus","Choeropsis liberiensis"],["Western chimpanzee","Pan troglodytes"],["Forest elephant","Loxodonta cyclotis"],["Zebra duiker","Cephalophus zebra"],["Grey parrot","Psittacus erithacus"]]},
ly:{flora:[["Date palm","Phoenix dactylifera"],["Olive tree","Olea europaea"],["Pomegranate","Punica granatum"],["Acacia","Vachellia tortilis"],["Esparto grass","Macrochloa tenacissima"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Fennec fox","Vulpes zerda"],["Dorcas gazelle","Gazella dorcas"],["Barbary sheep","Ammotragus lervia"],["Egyptian vulture","Neophron percnopterus"]]},
mg:{flora:[["Traveller's tree","Ravenala madagascariensis"],["Grandidier's baobab","Adansonia grandidieri"],["Vanilla orchid","Vanilla planifolia"],["Madagascar periwinkle","Catharanthus roseus"],["Octopus tree","Didierea madagascariensis"]],
    fauna:[["Ring-tailed lemur","Lemur catta"],["Indri","Indri indri"],["Panther chameleon","Furcifer pardalis"],["Fossa","Cryptoprocta ferox"],["Aye-aye","Daubentonia madagascariensis"]]},
mw:{flora:[["Mopane","Colophospermum mopane"],["Baobab","Adansonia digitata"],["Tea plant","Camellia sinensis"],["Mulanje cedar","Widdringtonia whytei"],["Msasa tree","Julbernardia globiflora"]],
    fauna:[["Hippopotamus","Hippopotamus amphibius"],["African elephant","Loxodonta africana"],["Nile crocodile","Crocodylus niloticus"],["Cichlid fish","Maylandia zebra"],["African fish eagle","Icthyophaga vocifer"]]},
ml:{flora:[["Baobab","Adansonia digitata"],["Shea tree","Vitellaria paradoxa"],["Néré tree","Parkia biglobosa"],["Doum palm","Hyphaene thebaica"],["Acacia","Vachellia nilotica"]],
    fauna:[["African elephant","Loxodonta africana"],["Hippopotamus","Hippopotamus amphibius"],["Dorcas gazelle","Gazella dorcas"],["West African manatee","Trichechus senegalensis"],["Ostrich","Struthio camelus"]]},
mr:{flora:[["Date palm","Phoenix dactylifera"],["Acacia","Vachellia tortilis"],["Doum palm","Hyphaene thebaica"],["Baobab","Adansonia digitata"],["Gum arabic tree","Senegalia senegal"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Dorcas gazelle","Gazella dorcas"],["Fennec fox","Vulpes zerda"],["Monk seal","Monachus monachus"],["Greater flamingo","Phoenicopterus roseus"]]},
mu:{flora:[["Trochetia","Trochetia boutoniana"],["Coconut palm","Cocos nucifera"],["Sugarcane","Saccharum officinarum"],["Traveller's tree","Ravenala madagascariensis"],["Ebony tree","Diospyros tessellaria"]],
    fauna:[["Mauritius kestrel","Falco punctatus"],["Pink pigeon","Nesoenas mayeri"],["Mauritian flying fox","Pteropus niger"],["Green sea turtle","Chelonia mydas"],["Telfair's skink","Leiolopisma telfairii"]]},
ma:{flora:[["Argan tree","Argania spinosa"],["Date palm","Phoenix dactylifera"],["Olive tree","Olea europaea"],["Atlas cedar","Cedrus atlantica"],["Cork oak","Quercus suber"]],
    fauna:[["Barbary macaque","Macaca sylvanus"],["Dromedary camel","Camelus dromedarius"],["Fennec fox","Vulpes zerda"],["Barbary sheep","Ammotragus lervia"],["Northern bald ibis","Geronticus eremita"]]},
mz:{flora:[["Baobab","Adansonia digitata"],["Mopane","Colophospermum mopane"],["Coconut palm","Cocos nucifera"],["Mangrove","Rhizophora mucronata"],["Marula","Sclerocarya birrea"]],
    fauna:[["African elephant","Loxodonta africana"],["Dugong","Dugong dugon"],["Nile crocodile","Crocodylus niloticus"],["Hippopotamus","Hippopotamus amphibius"],["Whale shark","Rhincodon typus"]]},
na:{flora:[["Welwitschia","Welwitschia mirabilis"],["Quiver tree","Aloidendron dichotomum"],["Camel thorn","Vachellia erioloba"],["Baobab","Adansonia digitata"],["Mopane","Colophospermum mopane"]],
    fauna:[["Gemsbok","Oryx gazella"],["Springbok","Antidorcas marsupialis"],["Cheetah","Acinonyx jubatus"],["Meerkat","Suricata suricatta"],["African elephant","Loxodonta africana"]]},
ne:{flora:[["Doum palm","Hyphaene thebaica"],["Baobab","Adansonia digitata"],["Acacia","Vachellia nilotica"],["Date palm","Phoenix dactylifera"],["Shea tree","Vitellaria paradoxa"]],
    fauna:[["West African giraffe","Giraffa camelopardalis"],["Addax","Addax nasomaculatus"],["Dorcas gazelle","Gazella dorcas"],["Dromedary camel","Camelus dromedarius"],["Ostrich","Struthio camelus"]]},
ng:{flora:[["Oil palm","Elaeis guineensis"],["Kapok tree","Ceiba pentandra"],["Kola nut tree","Cola nitida"],["Shea tree","Vitellaria paradoxa"],["Mangrove","Rhizophora racemosa"]],
    fauna:[["African elephant","Loxodonta africana"],["Chimpanzee","Pan troglodytes"],["Grey parrot","Psittacus erithacus"],["Nile crocodile","Crocodylus niloticus"],["West African manatee","Trichechus senegalensis"]]},
rw:{flora:[["Coffee plant","Coffea arabica"],["Tea plant","Camellia sinensis"],["Giant lobelia","Lobelia gibberoa"],["Bamboo","Yushania alpina"],["Banana plant","Musa acuminata"]],
    fauna:[["Mountain gorilla","Gorilla beringei"],["Golden monkey","Cercopithecus mitis"],["Chimpanzee","Pan troglodytes"],["Grey crowned crane","Balearica regulorum"],["Hippopotamus","Hippopotamus amphibius"]]},
st:{flora:[["Cocoa tree","Theobroma cacao"],["Coffee plant","Coffea arabica"],["Coconut palm","Cocos nucifera"],["Breadfruit tree","Artocarpus altilis"],["Giant begonia","Begonia baccata"]],
    fauna:[["São Tomé ibis","Bostrychia bocagei"],["Green sea turtle","Chelonia mydas"],["São Tomé giant treefrog","Leptopelis palmatus"],["Humpback whale","Megaptera novaeangliae"],["Grey parrot","Psittacus erithacus"]]},
sn:{flora:[["Baobab","Adansonia digitata"],["Oil palm","Elaeis guineensis"],["Mangrove","Rhizophora racemosa"],["Acacia","Senegalia senegal"],["Groundnut","Arachis hypogaea"]],
    fauna:[["Greater flamingo","Phoenicopterus roseus"],["West African manatee","Trichechus senegalensis"],["Guinea baboon","Papio papio"],["Warthog","Phacochoerus africanus"],["Great white pelican","Pelecanus onocrotalus"]]},
sc:{flora:[["Coco de mer","Lodoicea maldivica"],["Coconut palm","Cocos nucifera"],["Jellyfish tree","Medusagyne oppositifolia"],["Vanilla orchid","Vanilla planifolia"],["Takamaka","Calophyllum inophyllum"]],
    fauna:[["Aldabra giant tortoise","Aldabrachelys gigantea"],["Seychelles black parrot","Coracopsis barklyi"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Seychelles fody","Foudia sechellarum"],["Seychelles flying fox","Pteropus seychellensis"]]},
sl:{flora:[["Oil palm","Elaeis guineensis"],["Kola nut tree","Cola nitida"],["Kapok tree","Ceiba pentandra"],["Mangrove","Rhizophora racemosa"],["Rice","Oryza glaberrima"]],
    fauna:[["Western chimpanzee","Pan troglodytes"],["Pygmy hippopotamus","Choeropsis liberiensis"],["African elephant","Loxodonta africana"],["West African manatee","Trichechus senegalensis"],["Rufous fishing owl","Scotopelia ussheri"]]},
so:{flora:[["Frankincense tree","Boswellia sacra"],["Myrrh tree","Commiphora myrrha"],["Acacia","Vachellia tortilis"],["Doum palm","Hyphaene thebaica"],["Date palm","Phoenix dactylifera"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Somali wild ass","Equus africanus"],["Gerenuk","Litocranius walleri"],["Speke's gazelle","Gazella spekei"],["Hamadryas baboon","Papio hamadryas"]]},
za:{flora:[["King protea","Protea cynaroides"],["Baobab","Adansonia digitata"],["Quiver tree","Aloidendron dichotomum"],["Yellowwood","Afrocarpus falcatus"],["Marula","Sclerocarya birrea"]],
    fauna:[["Springbok","Antidorcas marsupialis"],["White rhinoceros","Ceratotherium simum"],["African penguin","Spheniscus demersus"],["Meerkat","Suricata suricatta"],["Blue crane","Grus paradisea"]]},
ss:{flora:[["Papyrus","Cyperus papyrus"],["Shea tree","Vitellaria paradoxa"],["Acacia","Vachellia seyal"],["Baobab","Adansonia digitata"],["Doum palm","Hyphaene thebaica"]],
    fauna:[["White-eared kob","Kobus kob"],["Nile lechwe","Kobus megaceros"],["African elephant","Loxodonta africana"],["Shoebill","Balaeniceps rex"],["Nile crocodile","Crocodylus niloticus"]]},
sd:{flora:[["Acacia","Senegalia senegal"],["Date palm","Phoenix dactylifera"],["Doum palm","Hyphaene thebaica"],["Baobab","Adansonia digitata"],["Papyrus","Cyperus papyrus"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Nubian ibex","Capra nubiana"],["Dorcas gazelle","Gazella dorcas"],["Nile crocodile","Crocodylus niloticus"],["Ostrich","Struthio camelus"]]},
tz:{flora:[["Baobab","Adansonia digitata"],["Umbrella thorn acacia","Vachellia tortilis"],["Coffee plant","Coffea arabica"],["African blackwood","Dalbergia melanoxylon"],["Giant lobelia","Lobelia deckenii"]],
    fauna:[["Lion","Panthera leo"],["Masai giraffe","Giraffa tippelskirchi"],["Blue wildebeest","Connochaetes taurinus"],["African elephant","Loxodonta africana"],["Chimpanzee","Pan troglodytes"]]},
tg:{flora:[["Oil palm","Elaeis guineensis"],["Baobab","Adansonia digitata"],["Kapok tree","Ceiba pentandra"],["Shea tree","Vitellaria paradoxa"],["Cocoa tree","Theobroma cacao"]],
    fauna:[["African elephant","Loxodonta africana"],["Hippopotamus","Hippopotamus amphibius"],["Warthog","Phacochoerus africanus"],["Nile crocodile","Crocodylus niloticus"],["Senegal parrot","Poicephalus senegalus"]]},
tn:{flora:[["Olive tree","Olea europaea"],["Date palm","Phoenix dactylifera"],["Cork oak","Quercus suber"],["Aleppo pine","Pinus halepensis"],["Jasmine","Jasminum grandiflorum"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Fennec fox","Vulpes zerda"],["Barbary sheep","Ammotragus lervia"],["Greater flamingo","Phoenicopterus roseus"],["Golden jackal","Canis aureus"]]},
ug:{flora:[["Coffee plant","Coffea canephora"],["Papyrus","Cyperus papyrus"],["Banana plant","Musa acuminata"],["Bark cloth fig","Ficus natalensis"],["Giant lobelia","Lobelia gibberoa"]],
    fauna:[["Mountain gorilla","Gorilla beringei"],["Chimpanzee","Pan troglodytes"],["Grey crowned crane","Balearica regulorum"],["Hippopotamus","Hippopotamus amphibius"],["Shoebill","Balaeniceps rex"]]},
zm:{flora:[["Mopane","Colophospermum mopane"],["Baobab","Adansonia digitata"],["Msasa tree","Brachystegia spiciformis"],["Marula","Sclerocarya birrea"],["Sausage tree","Kigelia africana"]],
    fauna:[["African elephant","Loxodonta africana"],["African fish eagle","Icthyophaga vocifer"],["Hippopotamus","Hippopotamus amphibius"],["Thornicroft's giraffe","Giraffa camelopardalis"],["Lion","Panthera leo"]]},
zw:{flora:[["Msasa tree","Brachystegia spiciformis"],["Baobab","Adansonia digitata"],["Flame lily","Gloriosa superba"],["Mopane","Colophospermum mopane"],["Marula","Sclerocarya birrea"]],
    fauna:[["African elephant","Loxodonta africana"],["Sable antelope","Hippotragus niger"],["Hippopotamus","Hippopotamus amphibius"],["African fish eagle","Icthyophaga vocifer"],["Lion","Panthera leo"]]},

// ================= ASIA =================
af:{flora:[["Pomegranate","Punica granatum"],["Almond tree","Prunus dulcis"],["Saffron crocus","Crocus sativus"],["Pistachio tree","Pistacia vera"],["Grapevine","Vitis vinifera"]],
    fauna:[["Snow leopard","Panthera uncia"],["Marco Polo sheep","Ovis ammon"],["Bactrian camel","Camelus bactrianus"],["Golden eagle","Aquila chrysaetos"],["Markhor","Capra falconeri"]]},
am:{flora:[["Apricot tree","Prunus armeniaca"],["Grapevine","Vitis vinifera"],["Pomegranate","Punica granatum"],["Walnut tree","Juglans regia"],["Oriental plane","Platanus orientalis"]],
    fauna:[["Armenian mouflon","Ovis gmelini"],["Bezoar ibex","Capra aegagrus"],["Brown bear","Ursus arctos"],["Golden eagle","Aquila chrysaetos"],["Grey wolf","Canis lupus"]]},
az:{flora:[["Pomegranate","Punica granatum"],["Grapevine","Vitis vinifera"],["Oriental plane","Platanus orientalis"],["Persian ironwood","Parrotia persica"],["Saffron crocus","Crocus sativus"]],
    fauna:[["Caucasian leopard","Panthera pardus"],["Goitered gazelle","Gazella subgutturosa"],["Brown bear","Ursus arctos"],["Beluga sturgeon","Huso huso"],["Golden eagle","Aquila chrysaetos"]]},
bh:{flora:[["Date palm","Phoenix dactylifera"],["Acacia","Vachellia tortilis"],["Mangrove","Avicennia marina"],["Desert hyacinth","Cistanche tubulosa"],["Christ's thorn jujube","Ziziphus spina-christi"]],
    fauna:[["Arabian oryx","Oryx leucoryx"],["Dromedary camel","Camelus dromedarius"],["Greater flamingo","Phoenicopterus roseus"],["Dugong","Dugong dugon"],["Hawksbill sea turtle","Eretmochelys imbricata"]]},
bd:{flora:[["Mangrove","Heritiera fomes"],["Mango tree","Mangifera indica"],["Water lily","Nymphaea nouchali"],["Jackfruit tree","Artocarpus heterophyllus"],["Banyan tree","Ficus benghalensis"]],
    fauna:[["Bengal tiger","Panthera tigris"],["Asian elephant","Elephas maximus"],["Ganges river dolphin","Platanista gangetica"],["Fishing cat","Prionailurus viverrinus"],["Oriental magpie-robin","Copsychus saularis"]]},
bt:{flora:[["Blue poppy","Meconopsis gakyidiana"],["Rhododendron","Rhododendron arboreum"],["Bhutan cypress","Cupressus cashmeriana"],["Bamboo","Borinda grossa"],["Blue pine","Pinus wallichiana"]],
    fauna:[["Takin","Budorcas taxicolor"],["Black-necked crane","Grus nigricollis"],["Snow leopard","Panthera uncia"],["Red panda","Ailurus fulgens"],["Golden langur","Trachypithecus geei"]]},
bn:{flora:[["Simpor","Dillenia suffruticosa"],["Dipterocarp tree","Shorea macrophylla"],["Kapur tree","Dryobalanops aromatica"],["Mangrove","Rhizophora apiculata"],["Nipa palm","Nypa fruticans"]],
    fauna:[["Proboscis monkey","Nasalis larvatus"],["Bornean gibbon","Hylobates muelleri"],["Rhinoceros hornbill","Buceros rhinoceros"],["Clouded leopard","Neofelis diardi"],["Saltwater crocodile","Crocodylus porosus"]]},
kh:{flora:[["Sugar palm","Borassus flabellifer"],["Rice","Oryza sativa"],["Lotus","Nelumbo nucifera"],["Rumduol","Sphaerocoryne affinis"],["Sacred fig","Ficus religiosa"]],
    fauna:[["Kouprey","Bos sauveli"],["Asian elephant","Elephas maximus"],["Giant ibis","Thaumatibis gigantea"],["Irrawaddy dolphin","Orcaella brevirostris"],["Siamese crocodile","Crocodylus siamensis"]]},
cn:{flora:[["Bamboo","Phyllostachys edulis"],["Ginkgo","Ginkgo biloba"],["Peony","Paeonia lactiflora"],["Dawn redwood","Metasequoia glyptostroboides"],["Tea plant","Camellia sinensis"]],
    fauna:[["Giant panda","Ailuropoda melanoleuca"],["Golden snub-nosed monkey","Rhinopithecus roxellana"],["Red-crowned crane","Grus japonensis"],["Chinese alligator","Alligator sinensis"],["Snow leopard","Panthera uncia"]]},
cy:{flora:[["Olive tree","Olea europaea"],["Cyprus cedar","Cedrus brevifolia"],["Carob tree","Ceratonia siliqua"],["Aleppo pine","Pinus brutia"],["Cyclamen","Cyclamen cyprium"]],
    fauna:[["Cyprus mouflon","Ovis gmelini"],["Green sea turtle","Chelonia mydas"],["Cyprus warbler","Curruca melanothorax"],["Griffon vulture","Gyps fulvus"],["Monk seal","Monachus monachus"]]},
ge:{flora:[["Grapevine","Vitis vinifera"],["Caucasian fir","Abies nordmanniana"],["Walnut tree","Juglans regia"],["Persian ironwood","Parrotia persica"],["Rhododendron","Rhododendron ponticum"]],
    fauna:[["Caucasian tur","Capra caucasica"],["Brown bear","Ursus arctos"],["Bearded vulture","Gypaetus barbatus"],["Grey wolf","Canis lupus"],["Chamois","Rupicapra rupicapra"]]},
in:{flora:[["Banyan tree","Ficus benghalensis"],["Lotus","Nelumbo nucifera"],["Mango tree","Mangifera indica"],["Neem tree","Azadirachta indica"],["Sandalwood","Santalum album"]],
    fauna:[["Bengal tiger","Panthera tigris"],["Indian elephant","Elephas maximus"],["Indian peafowl","Pavo cristatus"],["Indian rhinoceros","Rhinoceros unicornis"],["King cobra","Ophiophagus hannah"]]},
id:{flora:[["Rafflesia","Rafflesia arnoldii"],["Moon orchid","Phalaenopsis amabilis"],["Teak","Tectona grandis"],["Clove tree","Syzygium aromaticum"],["Coconut palm","Cocos nucifera"]],
    fauna:[["Komodo dragon","Varanus komodoensis"],["Bornean orangutan","Pongo pygmaeus"],["Sumatran tiger","Panthera tigris"],["Javan rhinoceros","Rhinoceros sondaicus"],["Bali myna","Leucopsar rothschildi"]]},
ir:{flora:[["Pomegranate","Punica granatum"],["Saffron crocus","Crocus sativus"],["Pistachio tree","Pistacia vera"],["Persian ironwood","Parrotia persica"],["Damask rose","Rosa damascena"]],
    fauna:[["Asiatic cheetah","Acinonyx jubatus"],["Persian leopard","Panthera pardus"],["Persian fallow deer","Dama mesopotamica"],["Goitered gazelle","Gazella subgutturosa"],["Brown bear","Ursus arctos"]]},
iq:{flora:[["Date palm","Phoenix dactylifera"],["Papyrus","Cyperus papyrus"],["Pomegranate","Punica granatum"],["Fig tree","Ficus carica"],["Common reed","Phragmites australis"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Goitered gazelle","Gazella subgutturosa"],["Basra reed warbler","Acrocephalus griseldis"],["Grey wolf","Canis lupus"],["Striped hyena","Hyaena hyaena"]]},
il:{flora:[["Olive tree","Olea europaea"],["Date palm","Phoenix dactylifera"],["Pomegranate","Punica granatum"],["Common anemone","Anemone coronaria"],["Aleppo pine","Pinus halepensis"]],
    fauna:[["Nubian ibex","Capra nubiana"],["Mountain gazelle","Gazella gazella"],["Hoopoe","Upupa epops"],["Rock hyrax","Procavia capensis"],["Striped hyena","Hyaena hyaena"]]},
jp:{flora:[["Cherry blossom","Prunus serrulata"],["Japanese maple","Acer palmatum"],["Chrysanthemum","Chrysanthemum morifolium"],["Japanese cedar","Cryptomeria japonica"],["Bamboo","Phyllostachys edulis"]],
    fauna:[["Japanese macaque","Macaca fuscata"],["Red-crowned crane","Grus japonensis"],["Sika deer","Cervus nippon"],["Japanese raccoon dog","Nyctereutes viverrinus"],["Asian black bear","Ursus thibetanus"]]},
jo:{flora:[["Black iris","Iris nigricans"],["Olive tree","Olea europaea"],["Date palm","Phoenix dactylifera"],["Aleppo pine","Pinus halepensis"],["Oleander","Nerium oleander"]],
    fauna:[["Arabian oryx","Oryx leucoryx"],["Nubian ibex","Capra nubiana"],["Sinai rosefinch","Carpodacus synoicus"],["Striped hyena","Hyaena hyaena"],["Dromedary camel","Camelus dromedarius"]]},
kz:{flora:[["Wild apple","Malus sieversii"],["Saxaul","Haloxylon ammodendron"],["Wild tulip","Tulipa greigii"],["Feather grass","Stipa capillata"],["Siberian spruce","Picea obovata"]],
    fauna:[["Saiga antelope","Saiga tatarica"],["Snow leopard","Panthera uncia"],["Golden eagle","Aquila chrysaetos"],["Steppe eagle","Aquila nipalensis"],["Grey wolf","Canis lupus"]]},
kw:{flora:[["Date palm","Phoenix dactylifera"],["Arfaj","Rhanterium epapposum"],["Acacia","Vachellia gerrardii"],["Mangrove","Avicennia marina"],["Desert hyacinth","Cistanche tubulosa"]],
    fauna:[["Dromedary camel","Camelus dromedarius"],["Greater flamingo","Phoenicopterus roseus"],["Desert monitor","Varanus griseus"],["Sand gazelle","Gazella marica"],["Socotra cormorant","Phalacrocorax nigrogularis"]]},
kg:{flora:[["Walnut tree","Juglans regia"],["Wild apple","Malus sieversii"],["Tien Shan spruce","Picea schrenkiana"],["Wild tulip","Tulipa kaufmanniana"],["Juniper","Juniperus semiglobosa"]],
    fauna:[["Snow leopard","Panthera uncia"],["Marco Polo sheep","Ovis ammon"],["Golden eagle","Aquila chrysaetos"],["Ibex","Capra sibirica"],["Grey wolf","Canis lupus"]]},
la:{flora:[["Frangipani","Plumeria rubra"],["Teak","Tectona grandis"],["Rice","Oryza sativa"],["Bamboo","Bambusa bambos"],["Lotus","Nelumbo nucifera"]],
    fauna:[["Asian elephant","Elephas maximus"],["Saola","Pseudoryx nghetinhensis"],["Irrawaddy dolphin","Orcaella brevirostris"],["Douc langur","Pygathrix nemaeus"],["Clouded leopard","Neofelis nebulosa"]]},
lb:{flora:[["Cedar of Lebanon","Cedrus libani"],["Olive tree","Olea europaea"],["Grapevine","Vitis vinifera"],["Aleppo pine","Pinus halepensis"],["Fig tree","Ficus carica"]],
    fauna:[["Striped hyena","Hyaena hyaena"],["Grey wolf","Canis lupus"],["Golden jackal","Canis aureus"],["Griffon vulture","Gyps fulvus"],["Rock hyrax","Procavia capensis"]]},
my:{flora:[["Hibiscus","Hibiscus rosa-sinensis"],["Rafflesia","Rafflesia arnoldii"],["Durian tree","Durio zibethinus"],["Dipterocarp tree","Shorea leprosula"],["Mangrove","Rhizophora apiculata"]],
    fauna:[["Malayan tapir","Tapirus indicus"],["Bornean orangutan","Pongo pygmaeus"],["Rhinoceros hornbill","Buceros rhinoceros"],["Proboscis monkey","Nasalis larvatus"],["Malayan tiger","Panthera tigris"]]},
mv:{flora:[["Coconut palm","Cocos nucifera"],["Tropical almond","Terminalia catappa"],["Screwpine","Pandanus tectorius"],["Mangrove","Rhizophora mucronata"],["Banyan tree","Ficus benghalensis"]],
    fauna:[["Whale shark","Rhincodon typus"],["Manta ray","Mobula alfredi"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Maldivian flying fox","Pteropus medius"],["Clownfish","Amphiprion clarkii"]]},
mn:{flora:[["Feather grass","Stipa krylovii"],["Siberian larch","Larix sibirica"],["Saxaul","Haloxylon ammodendron"],["Edelweiss","Leontopodium ochroleucum"],["Siberian pine","Pinus sibirica"]],
    fauna:[["Przewalski's horse","Equus przewalskii"],["Bactrian camel","Camelus bactrianus"],["Snow leopard","Panthera uncia"],["Mongolian gazelle","Procapra gutturosa"],["Golden eagle","Aquila chrysaetos"]]},
mm:{flora:[["Padauk","Pterocarpus macrocarpus"],["Teak","Tectona grandis"],["Rice","Oryza sativa"],["Banyan tree","Ficus benghalensis"],["Lotus","Nelumbo nucifera"]],
    fauna:[["Asian elephant","Elephas maximus"],["Irrawaddy dolphin","Orcaella brevirostris"],["Red panda","Ailurus fulgens"],["Hoolock gibbon","Hoolock hoolock"],["Green peafowl","Pavo muticus"]]},
np:{flora:[["Rhododendron","Rhododendron arboreum"],["Sal tree","Shorea robusta"],["Himalayan blue pine","Pinus wallichiana"],["Bamboo","Drepanostachyum falcatum"],["Orchid","Dendrobium densiflorum"]],
    fauna:[["Bengal tiger","Panthera tigris"],["One-horned rhinoceros","Rhinoceros unicornis"],["Snow leopard","Panthera uncia"],["Red panda","Ailurus fulgens"],["Himalayan monal","Lophophorus impejanus"]]},
kp:{flora:[["Korean pine","Pinus koraiensis"],["Rose of Sharon","Hibiscus syriacus"],["Ginseng","Panax ginseng"],["Azalea","Rhododendron mucronulatum"],["Manchurian walnut","Juglans mandshurica"]],
    fauna:[["Asian black bear","Ursus thibetanus"],["Red-crowned crane","Grus japonensis"],["Amur goral","Naemorhedus caudatus"],["Mandarin duck","Aix galericulata"],["Siberian roe deer","Capreolus pygargus"]]},
om:{flora:[["Frankincense tree","Boswellia sacra"],["Date palm","Phoenix dactylifera"],["Baobab","Adansonia digitata"],["Acacia","Vachellia tortilis"],["Dragon tree","Dracaena serrulata"]],
    fauna:[["Arabian oryx","Oryx leucoryx"],["Arabian leopard","Panthera pardus"],["Dromedary camel","Camelus dromedarius"],["Green sea turtle","Chelonia mydas"],["Arabian tahr","Arabitragus jayakari"]]},
pk:{flora:[["Deodar cedar","Cedrus deodara"],["Jasmine","Jasminum officinale"],["Mango tree","Mangifera indica"],["Chir pine","Pinus roxburghii"],["Date palm","Phoenix dactylifera"]],
    fauna:[["Markhor","Capra falconeri"],["Snow leopard","Panthera uncia"],["Indus river dolphin","Platanista minor"],["Chukar partridge","Alectoris chukar"],["Asiatic black bear","Ursus thibetanus"]]},
ph:{flora:[["Sampaguita","Jasminum sambac"],["Narra","Pterocarpus indicus"],["Coconut palm","Cocos nucifera"],["Waling-waling orchid","Vanda sanderiana"],["Rice","Oryza sativa"]],
    fauna:[["Philippine eagle","Pithecophaga jefferyi"],["Philippine tarsier","Carlito syrichta"],["Carabao","Bubalus bubalis"],["Rufous hornbill","Buceros hydrocorax"],["Whale shark","Rhincodon typus"]]},
qa:{flora:[["Date palm","Phoenix dactylifera"],["Sidra tree","Ziziphus spina-christi"],["Mangrove","Avicennia marina"],["Acacia","Vachellia tortilis"],["Desert hyacinth","Cistanche tubulosa"]],
    fauna:[["Arabian oryx","Oryx leucoryx"],["Dromedary camel","Camelus dromedarius"],["Whale shark","Rhincodon typus"],["Dugong","Dugong dugon"],["Greater flamingo","Phoenicopterus roseus"]]},
sa:{flora:[["Date palm","Phoenix dactylifera"],["Frankincense tree","Boswellia sacra"],["Acacia","Vachellia tortilis"],["Juniper","Juniperus procera"],["Desert hyacinth","Cistanche tubulosa"]],
    fauna:[["Arabian oryx","Oryx leucoryx"],["Dromedary camel","Camelus dromedarius"],["Nubian ibex","Capra nubiana"],["Hamadryas baboon","Papio hamadryas"],["Sand gazelle","Gazella marica"]]},
sg:{flora:[["Vanda Miss Joaquim","Papilionanthe hookeriana"],["Rain tree","Samanea saman"],["Tembusu","Cyrtophyllum fragrans"],["Mangrove","Rhizophora apiculata"],["Coconut palm","Cocos nucifera"]],
    fauna:[["Sunda pangolin","Manis javanica"],["Long-tailed macaque","Macaca fascicularis"],["Oriental pied hornbill","Anthracoceros albirostris"],["Smooth-coated otter","Lutrogale perspicillata"],["Malayan colugo","Galeopterus variegatus"]]},
kr:{flora:[["Rose of Sharon","Hibiscus syriacus"],["Korean pine","Pinus koraiensis"],["Ginseng","Panax ginseng"],["Azalea","Rhododendron mucronulatum"],["Korean fir","Abies koreana"]],
    fauna:[["Korean magpie","Pica serica"],["Asian black bear","Ursus thibetanus"],["Siberian roe deer","Capreolus pygargus"],["Red-crowned crane","Grus japonensis"],["Raccoon dog","Nyctereutes procyonoides"]]},
lk:{flora:[["Blue water lily","Nymphaea nouchali"],["Ceylon ironwood","Mesua ferrea"],["Tea plant","Camellia sinensis"],["Coconut palm","Cocos nucifera"],["Cinnamon tree","Cinnamomum verum"]],
    fauna:[["Sri Lankan elephant","Elephas maximus"],["Sri Lankan leopard","Panthera pardus"],["Purple-faced langur","Semnopithecus vetulus"],["Sri Lanka junglefowl","Gallus lafayettii"],["Blue whale","Balaenoptera musculus"]]},
sy:{flora:[["Olive tree","Olea europaea"],["Damask rose","Rosa damascena"],["Pistachio tree","Pistacia vera"],["Aleppo pine","Pinus halepensis"],["Fig tree","Ficus carica"]],
    fauna:[["Syrian brown bear","Ursus arctos"],["Striped hyena","Hyaena hyaena"],["Northern bald ibis","Geronticus eremita"],["Grey wolf","Canis lupus"],["Mountain gazelle","Gazella gazella"]]},
tw:{flora:[["Formosan cypress","Chamaecyparis formosensis"],["Plum blossom","Prunus mume"],["Butterfly orchid","Phalaenopsis aphrodite"],["Camphor tree","Cinnamomum camphora"],["Tea plant","Camellia sinensis"]],
    fauna:[["Formosan black bear","Ursus thibetanus"],["Formosan rock macaque","Macaca cyclopis"],["Mikado pheasant","Syrmaticus mikado"],["Taiwan blue magpie","Urocissa caerulea"],["Formosan sika deer","Cervus nippon"]]},
tj:{flora:[["Walnut tree","Juglans regia"],["Wild tulip","Tulipa kaufmanniana"],["Pistachio tree","Pistacia vera"],["Juniper","Juniperus seravschanica"],["Mulberry tree","Morus alba"]],
    fauna:[["Snow leopard","Panthera uncia"],["Marco Polo sheep","Ovis ammon"],["Markhor","Capra falconeri"],["Golden eagle","Aquila chrysaetos"],["Brown bear","Ursus arctos"]]},
th:{flora:[["Golden shower tree","Cassia fistula"],["Lotus","Nelumbo nucifera"],["Teak","Tectona grandis"],["Rice","Oryza sativa"],["Orchid","Rhynchostylis gigantea"]],
    fauna:[["Asian elephant","Elephas maximus"],["Indochinese tiger","Panthera tigris"],["Gaur","Bos gaurus"],["Siamese fighting fish","Betta splendens"],["Great hornbill","Buceros bicornis"]]},
tl:{flora:[["Sandalwood","Santalum album"],["Coconut palm","Cocos nucifera"],["Eucalyptus","Eucalyptus urophylla"],["Coffee plant","Coffea arabica"],["Tamarind","Tamarindus indica"]],
    fauna:[["Saltwater crocodile","Crocodylus porosus"],["Timor deer","Rusa timorensis"],["Green sea turtle","Chelonia mydas"],["Blue whale","Balaenoptera musculus"],["Timor sparrow","Padda fuscata"]]},
tr:{flora:[["Tulip","Tulipa armena"],["Olive tree","Olea europaea"],["Turkish pine","Pinus brutia"],["Oriental plane","Platanus orientalis"],["Hazelnut tree","Corylus avellana"]],
    fauna:[["Anatolian leopard","Panthera pardus"],["Brown bear","Ursus arctos"],["Loggerhead sea turtle","Caretta caretta"],["Grey wolf","Canis lupus"],["Bezoar ibex","Capra aegagrus"]]},
tm:{flora:[["Saxaul","Haloxylon ammodendron"],["Wild tulip","Tulipa turkestanica"],["Pistachio tree","Pistacia vera"],["Juniper","Juniperus turcomanica"],["Cotton plant","Gossypium hirsutum"]],
    fauna:[["Akhal-Teke horse","Equus caballus"],["Goitered gazelle","Gazella subgutturosa"],["Caracal","Caracal caracal"],["Markhor","Capra falconeri"],["Grey wolf","Canis lupus"]]},
ae:{flora:[["Date palm","Phoenix dactylifera"],["Ghaf tree","Prosopis cineraria"],["Mangrove","Avicennia marina"],["Acacia","Vachellia tortilis"],["Desert hyacinth","Cistanche tubulosa"]],
    fauna:[["Arabian oryx","Oryx leucoryx"],["Dromedary camel","Camelus dromedarius"],["Greater flamingo","Phoenicopterus roseus"],["Hawksbill sea turtle","Eretmochelys imbricata"],["Sand gazelle","Gazella marica"]]},
uz:{flora:[["Wild tulip","Tulipa greigii"],["Mulberry tree","Morus alba"],["Cotton plant","Gossypium hirsutum"],["Saxaul","Haloxylon ammodendron"],["Walnut tree","Juglans regia"]],
    fauna:[["Snow leopard","Panthera uncia"],["Goitered gazelle","Gazella subgutturosa"],["Golden eagle","Aquila chrysaetos"],["Grey wolf","Canis lupus"],["Bukhara deer","Cervus hanglu"]]},
vn:{flora:[["Lotus","Nelumbo nucifera"],["Rice","Oryza sativa"],["Bamboo","Bambusa vulgaris"],["Coconut palm","Cocos nucifera"],["Cinnamon tree","Cinnamomum cassia"]],
    fauna:[["Saola","Pseudoryx nghetinhensis"],["Asian elephant","Elephas maximus"],["Red-shanked douc","Pygathrix nemaeus"],["Indochinese tiger","Panthera tigris"],["Sarus crane","Antigone antigone"]]},
ye:{flora:[["Dragon blood tree","Dracaena cinnabari"],["Frankincense tree","Boswellia sacra"],["Coffee plant","Coffea arabica"],["Date palm","Phoenix dactylifera"],["Desert rose","Adenium obesum"]],
    fauna:[["Arabian leopard","Panthera pardus"],["Dromedary camel","Camelus dromedarius"],["Hamadryas baboon","Papio hamadryas"],["Socotra cormorant","Phalacrocorax nigrogularis"],["Arabian wolf","Canis lupus"]]}
};
