// BrightSprouts Academy — General Knowledge: Flora & Fauna of the World
// Every country gets 5 flora + 5 fauna, assigned by ecological region (nature ignores borders!),
// with signature countries getting their own custom lists.
const FF_REGIONS = {
  // ---------- AFRICA ----------
  north_africa: { isos:["dz","eg","ly","ma","tn","mr"],
    flora:["Date palm","Olive tree","Atlas cedar","Fig tree","Esparto grass"],
    fauna:["Dromedary camel","Fennec fox","Barbary macaque","Egyptian vulture","Desert monitor lizard"] },
  west_africa: { isos:["bj","bf","ci","cv","gm","gh","gn","gw","lr","ml","ne","ng","sn","sl","tg","td"],
    flora:["Baobab tree","Shea tree","Oil palm","Kola nut tree","Raffia palm"],
    fauna:["Hippopotamus","Chimpanzee","African grey parrot","Nile crocodile","West African giraffe"] },
  central_africa: { isos:["cm","cf","cg","cd","gq","ga","st"],
    flora:["African mahogany","Okoumé tree","Ebony tree","Oil palm","Giant lobelia"],
    fauna:["Gorilla","Forest elephant","Okapi","Mandrill","African grey parrot"] },
  east_africa: { isos:["bi","dj","er","et","ke","rw","so","ss","sd","tz","ug"],
    flora:["Umbrella thorn acacia","Baobab tree","Coffee plant","Papyrus","Candelabra euphorbia"],
    fauna:["Lion","African elephant","Giraffe","Zebra","Flamingo"] },
  southern_africa: { isos:["ao","bw","sz","ls","mw","mz","na","za","zm","zw"],
    flora:["Baobab tree","Marula tree","Mopane tree","King protea","Quiver tree"],
    fauna:["African elephant","White rhinoceros","Springbok","Meerkat","African wild dog"] },
  indian_ocean_africa: { isos:["km","mg","mu","sc"],
    flora:["Traveler's palm","Vanilla orchid","Coco de mer palm","Ylang-ylang tree","Grandidier's baobab"],
    fauna:["Ring-tailed lemur","Panther chameleon","Aldabra giant tortoise","Flying fox (fruit bat)","Paradise flycatcher"] },
  // ---------- ASIA ----------
  middle_east: { isos:["bh","iq","il","jo","kw","lb","om","qa","sa","sy","ae","ye","cy","ir","tr"],
    flora:["Date palm","Frankincense tree","Cedar of Lebanon","Pomegranate tree","Fig tree"],
    fauna:["Arabian oryx","Dromedary camel","Saker falcon","Sand gazelle","Arabian leopard"] },
  central_asia: { isos:["kz","kg","tj","tm","uz","af"],
    flora:["Wild apple tree","Saxaul tree","Wild tulip","Walnut tree","Pistachio tree"],
    fauna:["Snow leopard","Bactrian camel","Golden eagle","Argali mountain sheep","Saiga antelope"] },
  south_asia: { isos:["bd","bt","mv","np","pk","lk"],
    flora:["Banyan tree","Lotus","Mango tree","Rhododendron","Neem tree"],
    fauna:["Bengal tiger","Asian elephant","Peacock","King cobra","Snow leopard"] },
  southeast_asia: { isos:["bn","kh","id","la","my","mm","ph","sg","th","tl","vn"],
    flora:["Rafflesia (world's largest flower)","Teak tree","Banana plant","Wild orchid","Mangrove tree"],
    fauna:["Orangutan","Komodo dragon","Asian elephant","Gibbon","Hornbill"] },
  east_asia: { isos:["kp","kr","mn","tw"],
    flora:["Korean pine","Cherry blossom tree","Bamboo","Ginkgo tree","Azalea"],
    fauna:["Siberian tiger","Red-crowned crane","Przewalski's wild horse","Formosan black bear","Raccoon dog"] },
  caucasus: { isos:["am","az","ge"],
    flora:["Pomegranate tree","Grapevine","Caucasian fir","Apricot tree","Walnut tree"],
    fauna:["Caucasian leopard","Brown bear","Bezoar ibex","Golden eagle","Sturgeon"] },
  // ---------- EUROPE ----------
  northern_europe: { isos:["dk","ee","fi","is","lv","lt","no","se"],
    flora:["Norway spruce","Silver birch","Lingonberry","Heather","Cloudberry"],
    fauna:["Moose","Reindeer","Brown bear","Lynx","Atlantic puffin"] },
  western_europe: { isos:["at","be","ch","ie","li","lu","nl"],
    flora:["Oak tree","Beech tree","Edelweiss","Tulip","Bluebell"],
    fauna:["Red fox","Red deer","Hedgehog","Alpine ibex","White stork"] },
  southern_europe: { isos:["ad","gr","hr","mt","mc","pt","sm","si","va"],
    flora:["Olive tree","Cypress tree","Lavender","Cork oak","Lemon tree"],
    fauna:["Loggerhead sea turtle","Mediterranean monk seal","Flamingo","Moorish gecko","Griffon vulture"] },
  eastern_europe: { isos:["al","ba","bg","by","cz","hu","md","me","mk","pl","ro","rs","sk","ua"],
    flora:["Sunflower","Oak tree","Linden tree","Wild rose","Hornbeam"],
    fauna:["European bison","Brown bear","Grey wolf","White stork","Wild boar"] },
  // ---------- AMERICAS ----------
  central_america: { isos:["bz","cr","sv","gt","hn","ni","pa"],
    flora:["Orchid","Ceiba (kapok) tree","Mahogany tree","Banana plant","Coffee plant"],
    fauna:["Resplendent quetzal","Jaguar","Sloth","Howler monkey","Scarlet macaw"] },
  caribbean: { isos:["ag","bs","bb","cu","dm","do","gd","ht","jm","kn","lc","vc","tt"],
    flora:["Coconut palm","Hibiscus","Mahogany tree","Frangipani","Breadfruit tree"],
    fauna:["Green iguana","Hummingbird","Flamingo","Sea turtle","Imperial parrot"] },
  amazon_andes: { isos:["bo","co","ec","pe","ve"],
    flora:["Cinchona tree","Wild orchid","Kapok (ceiba) tree","Quinoa","Heliconia"],
    fauna:["Andean condor","Llama","Alpaca","Spectacled bear","Pink river dolphin"] },
  southern_cone: { isos:["ar","cl","py","uy"],
    flora:["Monkey puzzle tree","Ombú tree","Ceibo flower","Yerba mate","Patagonian cypress"],
    fauna:["Puma","Guanaco","Rhea","Magellanic penguin","Capybara"] },
  guianas: { isos:["gy","sr"],
    flora:["Greenheart tree","Giant water lily (Victoria amazonica)","Mora tree","Heliconia","Kapok tree"],
    fauna:["Giant river otter","Jaguar","Harpy eagle","Hoatzin bird","Leatherback sea turtle"] },
  // ---------- OCEANIA ----------
  pacific_islands: { isos:["fj","ki","mh","fm","nr","pw","ws","sb","to","tv","vu"],
    flora:["Coconut palm","Breadfruit tree","Pandanus tree","Hibiscus","Taro plant"],
    fauna:["Sea turtle","Coconut crab","Flying fox (fruit bat)","Clownfish","Frigatebird"] },
  // ---------- SIGNATURE COUNTRIES ----------
  c_us: { isos:["us"], flora:["Giant sequoia","Saguaro cactus","Coast redwood","Sugar maple","Sunflower"],
    fauna:["Bald eagle","American bison","Grizzly bear","White-tailed deer","American alligator"] },
  c_ca: { isos:["ca"], flora:["Sugar maple","White spruce","Douglas fir","Trillium","Fireweed"],
    fauna:["Beaver","Moose","Canada goose","Polar bear","Orca (killer whale)"] },
  c_mx: { isos:["mx"], flora:["Dahlia","Agave","Prickly pear cactus","Vanilla orchid","Montezuma cypress"],
    fauna:["Golden eagle","Jaguar","Axolotl","Monarch butterfly","Coyote"] },
  c_br: { isos:["br"], flora:["Brazil nut tree","Rubber tree","Ipê tree","Açaí palm","Passionflower"],
    fauna:["Jaguar","Toco toucan","Capybara","Hyacinth macaw","Pink river dolphin"] },
  c_au: { isos:["au"], flora:["Eucalyptus (gum tree)","Golden wattle","Moreton Bay fig","Bottlebrush","Macadamia tree"],
    fauna:["Kangaroo","Koala","Platypus","Emu","Wombat"] },
  c_nz: { isos:["nz"], flora:["Silver fern","Pōhutukawa tree","Kauri tree","Mānuka","Cabbage tree"],
    fauna:["Kiwi bird","Kea parrot","Tuatara","Hector's dolphin","Little blue penguin"] },
  c_pg: { isos:["pg"], flora:["Sago palm","Breadfruit tree","Wild orchid","Klinkii pine","Taro plant"],
    fauna:["Bird of paradise","Tree kangaroo","Cassowary","Cuscus","Hornbill"] },
  c_cn: { isos:["cn"], flora:["Bamboo","Ginkgo tree","Peony","Dawn redwood","Tea plant"],
    fauna:["Giant panda","Golden snub-nosed monkey","Red-crowned crane","Chinese alligator","South China tiger"] },
  c_jp: { isos:["jp"], flora:["Cherry blossom (sakura)","Japanese maple","Bamboo","Chrysanthemum","Japanese black pine"],
    fauna:["Japanese macaque (snow monkey)","Red-crowned crane","Koi carp","Sika deer","Tanuki (raccoon dog)"] },
  c_in: { isos:["in"], flora:["Banyan tree","Lotus","Mango tree","Neem tree","Sandalwood tree"],
    fauna:["Bengal tiger","Indian elephant","Peacock","King cobra","Indian rhinoceros"] },
  c_ru: { isos:["ru"], flora:["Siberian larch","Silver birch","Siberian pine","Chamomile","Rowan tree"],
    fauna:["Siberian tiger","Brown bear","Arctic fox","Sable","Beluga sturgeon"] },
  c_gb: { isos:["gb"], flora:["English oak","Rose","Bluebell","Scots pine","Holly"],
    fauna:["Red deer","Red fox","European robin","Grey seal","Hedgehog"] },
  c_fr: { isos:["fr"], flora:["Lavender","Iris","Oak tree","Grapevine","Sunflower"],
    fauna:["Wild boar","Camargue horse","Flamingo","Red squirrel","Golden eagle"] },
  c_de: { isos:["de"], flora:["Oak tree","Cornflower","Beech tree","Linden tree","Norway spruce"],
    fauna:["White-tailed eagle","Red deer","Wild boar","European wildcat","Black stork"] },
  c_it: { isos:["it"], flora:["Olive tree","Cypress tree","Stone pine","Lemon tree","Grapevine"],
    fauna:["Italian wolf","Marsican brown bear","Alpine ibex","Flamingo","Peregrine falcon"] },
  c_es: { isos:["es"], flora:["Olive tree","Cork oak","Carnation","Orange tree","Holm oak"],
    fauna:["Iberian lynx","Spanish imperial eagle","Flamingo","Iberian wolf","Chameleon"] }
};
const FF_BY_ISO = {};
for (const key in FF_REGIONS) FF_REGIONS[key].isos.forEach(iso => FF_BY_ISO[iso] = FF_REGIONS[key]);

// Iconic species → country, for "which country is famous for..." questions
const FF_ICONIC = [
  ["giant panda","China"],["kangaroo","Australia"],["kiwi bird","New Zealand"],["Bengal tiger","India"],
  ["bald eagle","United States"],["beaver","Canada"],["axolotl","Mexico"],["cherry blossom (sakura)","Japan"],
  ["ring-tailed lemur","Madagascar"],["Komodo dragon","Indonesia"],["Iberian lynx","Spain"],["koala","Australia"],
  ["bird of paradise","Papua New Guinea"],["silver fern","New Zealand"],["golden wattle","Australia"],
  ["toco toucan","Brazil"],["platypus","Australia"],["Siberian tiger","Russia"],["English oak","United Kingdom"],
  ["lavender","France"],["olive tree","Italy (and the Mediterranean)"],["okapi","DR Congo"],["quetzal","Guatemala (and Costa Rica)"]
];

LESSONS[13].florafauna = {
  title: "Flora & Fauna of the World", emoji: "🌿",
  intro: "Flora means plants; fauna means animals. Every country below lists 5 famous plants and 5 famous animals of its lands — because nature doesn't stop at borders, neighboring countries often share their wildlife!",
  learn: [
    "FLORA = the plant life of a place (trees, flowers, crops). FAUNA = the animal life. Remember: FLOWERS are flora, FURRY things are fauna!",
    "Animals and plants live by climate and habitat, not by country lines — the baobab tree grows across a dozen African countries, and the jaguar roams from Mexico to Argentina.",
    "Some species are so special they became national symbols: the bald eagle (USA), the kiwi (New Zealand), the giant panda (China).",
    "Endemic means found nowhere else on Earth — like Madagascar's lemurs, New Zealand's tuatara, and Australia's platypus."
  ],
  activity: "🔎 Backyard Biologist: Make a flora & fauna list for YOUR home — 5 plants and 5 animals you can find in your own neighborhood. You just did real field science!",
  floraFauna: true
};
