// BrightSprouts Academy - free Read Online library.
// Every title is in the US public domain and sourced from Project Gutenberg,
// which verifies public-domain status. Texts load on demand, one book at a time.
const PD_BOOKS = [
{
"slug": "winnie-the-pooh",
"t": "Winnie-the-Pooh",
"a": "A. A. Milne",
"y": 1926,
"b": "1-2",
"g": "Animal Stories",
"w": "A bear of very little brain, a boy called Christopher Robin, and the friendliest wood in all of books.",
"ch": 10,
"words": 22116,
"kb": 124,
"src": "Project Gutenberg #67098"
},
{
"slug": "peter-rabbit",
"t": "The Tale of Peter Rabbit",
"a": "Beatrix Potter",
"y": 1902,
"b": "1-2",
"g": "Animal Stories",
"w": "Peter squeezes under the gate into Mr McGregor's garden. He should not have. Four minutes of perfect mischief.",
"ch": 1,
"words": 1012,
"kb": 6,
"src": "Project Gutenberg #14838"
},
{
"slug": "just-so-stories",
"t": "Just So Stories",
"a": "Rudyard Kipling",
"y": 1902,
"b": "1-2",
"g": "Fable",
"w": "How the camel got his hump, how the elephant got his trunk. Written to be read out loud in a silly voice.",
"ch": 12,
"words": 28644,
"kb": 161,
"src": "Project Gutenberg #2781"
},
{
"slug": "aesop",
"t": "Aesop's Fables",
"a": "Aesop",
"y": 1867,
"b": "1-2",
"g": "Fable",
"w": "The tortoise and the hare, the boy who cried wolf. Two thousand years old and still the best short stories there are.",
"ch": 132,
"words": 22931,
"kb": 124,
"src": "Project Gutenberg #11339"
},
{
"slug": "grimm",
"t": "Grimms' Fairy Tales",
"a": "The Brothers Grimm",
"y": 1812,
"b": "3-5",
"g": "Fairy Tale",
"w": "Rapunzel, Hansel and Gretel, Rumpelstiltskin, in the original spikier versions.",
"ch": 62,
"words": 100626,
"kb": 531,
"src": "Project Gutenberg #2591"
},
{
"slug": "andersen",
"t": "Andersen's Fairy Tales",
"a": "Hans Christian Andersen",
"y": 1837,
"b": "3-5",
"g": "Fairy Tale",
"w": "The Ugly Duckling, The Little Mermaid, The Emperor's New Clothes. Sadder and stranger than the cartoons.",
"ch": 19,
"words": 55290,
"kb": 303,
"src": "Project Gutenberg #1597"
},
{
"slug": "alice",
"t": "Alice's Adventures in Wonderland",
"a": "Lewis Carroll",
"y": 1865,
"b": "3-5",
"g": "Fantasy",
"w": "Down the rabbit hole into total, glorious nonsense. Nothing has ever been this odd since.",
"ch": 12,
"words": 26417,
"kb": 150,
"src": "Project Gutenberg #11"
},
{
"slug": "looking-glass",
"t": "Through the Looking-Glass",
"a": "Lewis Carroll",
"y": 1871,
"b": "3-5",
"g": "Fantasy",
"w": "Alice climbs through a mirror into a chess game. Contains the Jabberwocky.",
"ch": 10,
"words": 29235,
"kb": 169,
"src": "Project Gutenberg #12"
},
{
"slug": "wizard-of-oz",
"t": "The Wonderful Wizard of Oz",
"a": "L. Frank Baum",
"y": 1900,
"b": "3-5",
"g": "Fantasy",
"w": "A tornado, a yellow road, and four friends who already had what they were looking for.",
"ch": 14,
"words": 39649,
"kb": 213,
"src": "Project Gutenberg #55"
},
{
"slug": "peter-pan",
"t": "Peter Pan",
"a": "J. M. Barrie",
"y": 1911,
"b": "3-5",
"g": "Fantasy",
"w": "Second star to the right. Darker and sharper than you remember: Peter is not entirely nice.",
"ch": 17,
"words": 47078,
"kb": 262,
"src": "Project Gutenberg #16"
},
{
"slug": "wind-in-willows",
"t": "The Wind in the Willows",
"a": "Kenneth Grahame",
"y": 1908,
"b": "3-5",
"g": "Animal Stories",
"w": "Mole, Ratty, Badger and the appalling Mr Toad. The riverbank chapters are the coziest pages in English.",
"ch": 14,
"words": 58408,
"kb": 329,
"src": "Project Gutenberg #27805"
},
{
"slug": "pinocchio",
"t": "The Adventures of Pinocchio",
"a": "Carlo Collodi",
"y": 1883,
"b": "3-5",
"g": "Fantasy",
"w": "A wooden puppet who lies, runs away, and is nearly fried as a fish. Far wilder than the film.",
"ch": 36,
"words": 39785,
"kb": 220,
"src": "Project Gutenberg #500"
},
{
"slug": "doctor-dolittle",
"t": "The Story of Doctor Dolittle",
"a": "Hugh Lofting",
"y": 1920,
"b": "3-5",
"g": "Animal Stories",
"w": "A doctor who gives up people to learn animal languages, then sails to Africa with a parrot.",
"ch": 20,
"words": 25039,
"kb": 139,
"src": "Project Gutenberg #501"
},
{
"slug": "five-children",
"t": "Five Children and It",
"a": "E. Nesbit",
"y": 1902,
"b": "3-5",
"g": "Fantasy",
"w": "A sand fairy grants one wish a day, and every single one goes wrong.",
"ch": 11,
"words": 52954,
"kb": 295,
"src": "Project Gutenberg #17314"
},
{
"slug": "railway-children",
"t": "The Railway Children",
"a": "E. Nesbit",
"y": 1906,
"b": "3-5",
"g": "Realistic Fiction",
"w": "Three children move to a cottage by a railway line after their father disappears. The ending is famous for a reason.",
"ch": 14,
"words": 59195,
"kb": 335,
"src": "Project Gutenberg #1874"
},
{
"slug": "secret-garden",
"t": "The Secret Garden",
"a": "Frances Hodgson Burnett",
"y": 1911,
"b": "3-5",
"g": "Realistic Fiction",
"w": "A sour, lonely girl finds a locked garden and brings it, and herself, back to life.",
"ch": 27,
"words": 80413,
"kb": 446,
"src": "Project Gutenberg #113"
},
{
"slug": "little-princess",
"t": "A Little Princess",
"a": "Frances Hodgson Burnett",
"y": 1905,
"b": "3-5",
"g": "Realistic Fiction",
"w": "Sara Crewe loses everything and stays kind anyway. The attic chapters will destroy you.",
"ch": 14,
"words": 66362,
"kb": 369,
"src": "Project Gutenberg #146"
},
{
"slug": "heidi",
"t": "Heidi",
"a": "Johanna Spyri",
"y": 1881,
"b": "3-5",
"g": "Realistic Fiction",
"w": "A girl, a grandfather, and a mountain. The most homesick book ever written.",
"ch": 23,
"words": 66022,
"kb": 357,
"src": "Project Gutenberg #46409"
},
{
"slug": "black-beauty",
"t": "Black Beauty",
"a": "Anna Sewell",
"y": 1877,
"b": "3-5",
"g": "Animal Stories",
"w": "A horse tells his own life story. Written to change how people treated horses, and it did.",
"ch": 14,
"words": 59961,
"kb": 308,
"src": "Project Gutenberg #271"
},
{
"slug": "anne-green-gables",
"t": "Anne of Green Gables",
"a": "L. M. Montgomery",
"y": 1908,
"b": "6-8",
"g": "Realistic Fiction",
"w": "An orphan is sent to Prince Edward Island by mistake and talks without stopping for 400 pages. Wonderful.",
"ch": 38,
"words": 101964,
"kb": 575,
"src": "Project Gutenberg #45"
},
{
"slug": "tom-sawyer",
"t": "The Adventures of Tom Sawyer",
"a": "Mark Twain",
"y": 1876,
"b": "6-8",
"g": "Adventure",
"w": "Fence painting, a cave, a graveyard at midnight. The great American boyhood.",
"ch": 37,
"words": 69744,
"kb": 399,
"src": "Project Gutenberg #74"
},
{
"slug": "treasure-island",
"t": "Treasure Island",
"a": "Robert Louis Stevenson",
"y": 1883,
"b": "6-8",
"g": "Adventure",
"w": "A map, a one-legged cook, and the invention of every pirate cliche you know.",
"ch": 14,
"words": 68634,
"kb": 372,
"src": "Project Gutenberg #120"
},
{
"slug": "jungle-book",
"t": "The Jungle Book",
"a": "Rudyard Kipling",
"y": 1894,
"b": "6-8",
"g": "Adventure",
"w": "Mowgli raised by wolves, and Rikki-Tikki-Tavi versus the cobras.",
"ch": 14,
"words": 50839,
"kb": 278,
"src": "Project Gutenberg #236"
},
{
"slug": "little-women",
"t": "Little Women",
"a": "Louisa May Alcott",
"y": 1868,
"b": "6-8",
"g": "Classic",
"w": "Four sisters growing up in wartime. Jo March made more writers than any character in fiction.",
"ch": 60,
"words": 191744,
"kb": 1060,
"src": "Project Gutenberg #37106"
},
{
"slug": "eighty-days",
"t": "Around the World in Eighty Days",
"a": "Jules Verne",
"y": 1873,
"b": "6-8",
"g": "Adventure",
"w": "A bet, a butler, and a race against the clock across the planet. Pure momentum.",
"ch": 37,
"words": 62686,
"kb": 374,
"src": "Project Gutenberg #103"
},
{
"slug": "twenty-thousand",
"t": "Twenty Thousand Leagues Under the Sea",
"a": "Jules Verne",
"y": 1870,
"b": "6-8",
"g": "Science Fiction",
"w": "Captain Nemo, the Nautilus, and the sea monster that wasn't.",
"ch": 46,
"words": 104234,
"kb": 606,
"src": "Project Gutenberg #164"
},
{
"slug": "call-of-wild",
"t": "The Call of the Wild",
"a": "Jack London",
"y": 1903,
"b": "6-8",
"g": "Adventure",
"w": "A stolen dog becomes wild in the Klondike. Short, hard, magnificent.",
"ch": 7,
"words": 31716,
"kb": 177,
"src": "Project Gutenberg #215"
},
{
"slug": "christmas-carol",
"t": "A Christmas Carol",
"a": "Charles Dickens",
"y": 1843,
"b": "6-8",
"g": "Classic",
"w": "Three ghosts, one night, and the most famous change of heart in literature.",
"ch": 14,
"words": 28541,
"kb": 161,
"src": "Project Gutenberg #46"
},
{
"slug": "time-machine",
"t": "The Time Machine",
"a": "H. G. Wells",
"y": 1895,
"b": "9-12",
"g": "Science Fiction",
"w": "The first time-travel novel. Rides 800,000 years into the future and finds something awful.",
"ch": 14,
"words": 32454,
"kb": 182,
"src": "Project Gutenberg #35"
},
{
"slug": "war-of-worlds",
"t": "The War of the Worlds",
"a": "H. G. Wells",
"y": 1898,
"b": "9-12",
"g": "Science Fiction",
"w": "Martians land in Surrey. The alien invasion that all other alien invasions copied.",
"ch": 26,
"words": 59774,
"kb": 341,
"src": "Project Gutenberg #36"
},
{
"slug": "frankenstein",
"t": "Frankenstein",
"a": "Mary Shelley",
"y": 1818,
"b": "9-12",
"g": "Classic",
"w": "Written by an 18-year-old. The monster is articulate, lonely and right, which is the horror of it.",
"ch": 14,
"words": 75042,
"kb": 423,
"src": "Project Gutenberg #84"
},
{
"slug": "jekyll-hyde",
"t": "The Strange Case of Dr. Jekyll and Mr. Hyde",
"a": "Robert Louis Stevenson",
"y": 1886,
"b": "9-12",
"g": "Classic",
"w": "A respectable doctor and the thing inside him. Short enough to read in an evening.",
"ch": 10,
"words": 25529,
"kb": 141,
"src": "Project Gutenberg #43"
},
{
"slug": "sherlock",
"t": "The Adventures of Sherlock Holmes",
"a": "Arthur Conan Doyle",
"y": 1892,
"b": "9-12",
"g": "Mystery",
"w": "Twelve cases. The detective who taught every detective since how to notice things.",
"ch": 12,
"words": 104350,
"kb": 577,
"src": "Project Gutenberg #1661"
},
{
"slug": "pride-prejudice",
"t": "Pride and Prejudice",
"a": "Jane Austen",
"y": 1813,
"b": "9-12",
"g": "Classic",
"w": "Elizabeth Bennet, Mr Darcy, and the funniest first sentence in English.",
"ch": 59,
"words": 121376,
"kb": 698,
"src": "Project Gutenberg #1342"
}
];
