// BrightSprouts Academy - species photo lookup (thumbnails from Wikimedia Commons)
const SPECIES_IMG = {
"African elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg/250px-African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg",
"African grey parrot": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Perroquet_%C3%A0_Yampopo_Beach_-_Douala.jpg/250px-Perroquet_%C3%A0_Yampopo_Beach_-_Douala.jpg",
"African mahogany": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Genuine_Mahogany_veneer_with_ripple_marks.jpg/250px-Genuine_Mahogany_veneer_with_ripple_marks.jpg",
"African wild dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/African_Wild_Dog_at_Working_with_Wildlife.jpg/250px-African_Wild_Dog_at_Working_with_Wildlife.jpg",
"Agave": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Agave_americana_R01.jpg/250px-Agave_americana_R01.jpg",
"Aldabra giant tortoise": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Giant_Tortoise.JPG/250px-Giant_Tortoise.JPG",
"Alpaca": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Alpaca_in_Higashiyama_Zoo_-_1.jpg/250px-Alpaca_in_Higashiyama_Zoo_-_1.jpg",
"Alpine ibex": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg/250px-003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg",
"American alligator": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/American_Alligator.jpg/250px-American_Alligator.jpg",
"American bison": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/American_bison_k5680-1.jpg/250px-American_bison_k5680-1.jpg",
"Andean condor": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/AndeanCondorMale.jpg/250px-AndeanCondorMale.jpg",
"Apricot tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Apricot_and_cross_section.jpg/250px-Apricot_and_cross_section.jpg",
"Arabian leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/PikiWiki_Israel_14861_judean_desert_leopard_cropped.JPG/250px-PikiWiki_Israel_14861_judean_desert_leopard_cropped.JPG",
"Arabian oryx": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Arabian_oryx_%28oryx_leucoryx%29.jpg/250px-Arabian_oryx_%28oryx_leucoryx%29.jpg",
"Arctic fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Vulpes_lagopus_in_Iceland_%28cropped_3%29.jpg/250px-Vulpes_lagopus_in_Iceland_%28cropped_3%29.jpg",
"Argali mountain sheep": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ovis_ammon_%28cropped%29.jpg/250px-Ovis_ammon_%28cropped%29.jpg",
"Asian elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Elephas_maximus_%28Bandipur%29.jpg/250px-Elephas_maximus_%28Bandipur%29.jpg",
"Atlantic puffin": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Puffin_%28Fratercula_arctica%29.jpg/250px-Puffin_%28Fratercula_arctica%29.jpg",
"Atlas cedar": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Cedrus_atlantica.jpg/250px-Cedrus_atlantica.jpg",
"Axolotl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Axolotl_ganz.jpg/250px-Axolotl_ganz.jpg",
"Azalea": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Rhododendron_indicum1.jpg/250px-Rhododendron_indicum1.jpg",
"Açaí palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Euterpe_oleracea_salu.jpg/250px-Euterpe_oleracea_salu.jpg",
"Bactrian camel": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Camelus_bactrianus_%2855026866188%29.jpg/250px-Camelus_bactrianus_%2855026866188%29.jpg",
"Bald eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg/250px-Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg",
"Bamboo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Bamboo_forest.jpg/250px-Bamboo_forest.jpg",
"Banana plant": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Starr_050826-4195_Musa_sp..jpg/250px-Starr_050826-4195_Musa_sp..jpg",
"Banyan tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Big_Banyan_Tree_at_Bangalore.jpg/250px-Big_Banyan_Tree_at_Bangalore.jpg",
"Baobab tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Baobab_Adansonia_digitata.jpg/250px-Baobab_Adansonia_digitata.jpg",
"Barbary macaque": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Macaca_sylvanus.Mother_and_baby.jpg/250px-Macaca_sylvanus.Mother_and_baby.jpg",
"Beaver": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/250px-American_Beaver.jpg",
"Beech tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Beech-tree.JPG/250px-Beech-tree.JPG",
"Beluga sturgeon": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/%D0%91%D1%96%D0%BB%D1%83%D0%B3%D0%B0_%28Huso_huso%29.jpg/250px-%D0%91%D1%96%D0%BB%D1%83%D0%B3%D0%B0_%28Huso_huso%29.jpg",
"Bengal tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg/250px-Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg",
"Bezoar ibex": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Bezoarziege.jpg/250px-Bezoarziege.jpg",
"Bird of paradise": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Raggiana_Bird-of-Paradise_wild_5.jpg/250px-Raggiana_Bird-of-Paradise_wild_5.jpg",
"Black stork": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Ciconia_nigra_-Kruger_National_Park-8.jpg/250px-Ciconia_nigra_-Kruger_National_Park-8.jpg",
"Bluebell": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Hyacinthoides_non-scripta_%28Common_Bluebell%29.jpg/250px-Hyacinthoides_non-scripta_%28Common_Bluebell%29.jpg",
"Bottlebrush": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Red_bottle_brush.jpg/250px-Red_bottle_brush.jpg",
"Brazil nut tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Bertholletia_excelsa_compose.jpg/250px-Bertholletia_excelsa_compose.jpg",
"Breadfruit tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Artocarpus_altilis_%28fruit%29.jpg/250px-Artocarpus_altilis_%28fruit%29.jpg",
"Brown bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/2010-kodiak-bear-1.jpg/250px-2010-kodiak-bear-1.jpg",
"Cabbage tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/CabbageTreeKaihoka.jpg/250px-CabbageTreeKaihoka.jpg",
"Camargue horse": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Camargue_Horse_%2826645657776%29.jpg/250px-Camargue_Horse_%2826645657776%29.jpg",
"Canada goose": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Canada_goose.jpg/250px-Canada_goose.jpg",
"Candelabra euphorbia": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Euphorbia_candelabrum_1.JPG/250px-Euphorbia_candelabrum_1.JPG",
"Capybara": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Capybaracropped.jpg/250px-Capybaracropped.jpg",
"Carnation": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/W_carnation4051.jpg/250px-W_carnation4051.jpg",
"Cassowary": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cassowary_Diversity.jpg/250px-Cassowary_Diversity.jpg",
"Caucasian fir": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/%C3%96r%C3%BCmcek_Orman%C4%B1_G%C3%B6knar%C4%B1_2_Tabiat_An%C4%B1t%C4%B1.jpg/250px-%C3%96r%C3%BCmcek_Orman%C4%B1_G%C3%B6knar%C4%B1_2_Tabiat_An%C4%B1t%C4%B1.jpg",
"Caucasian leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Persian_Leopard_sitting.jpg/250px-Persian_Leopard_sitting.jpg",
"Cedar of Lebanon": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/C%C3%A8dre_du_Liban_Barouk_2005.jpg/250px-C%C3%A8dre_du_Liban_Barouk_2005.jpg",
"Ceiba (kapok) tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Kapok_tree-pod.jpg/250px-Kapok_tree-pod.jpg",
"Ceibo flower": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Corticeira_em_Bag%C3%A9_04.jpg/250px-Corticeira_em_Bag%C3%A9_04.jpg",
"Chameleon": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Panther_Chameleon_738367_%28cropped%29.jpg/250px-Panther_Chameleon_738367_%28cropped%29.jpg",
"Chamomile": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Kamomillasaunio_%28Matricaria_recutita%29.JPG/250px-Kamomillasaunio_%28Matricaria_recutita%29.JPG",
"Cherry blossom (sakura)": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sakura_and_Moss_Pink_-_%E6%A1%9C%28%E3%81%95%E3%81%8F%E3%82%89%29%E3%81%A8%E8%8A%9D%E6%A1%9C%28%E3%81%97%E3%81%B0%E3%81%96%E3%81%8F%E3%82%89%29.jpg/250px-Sakura_and_Moss_Pink_-_%E6%A1%9C%28%E3%81%95%E3%81%8F%E3%82%89%29%E3%81%A8%E8%8A%9D%E6%A1%9C%28%E3%81%97%E3%81%B0%E3%81%96%E3%81%8F%E3%82%89%29.jpg",
"Cherry blossom tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sakura_and_Moss_Pink_-_%E6%A1%9C%28%E3%81%95%E3%81%8F%E3%82%89%29%E3%81%A8%E8%8A%9D%E6%A1%9C%28%E3%81%97%E3%81%B0%E3%81%96%E3%81%8F%E3%82%89%29.jpg/250px-Sakura_and_Moss_Pink_-_%E6%A1%9C%28%E3%81%95%E3%81%8F%E3%82%89%29%E3%81%A8%E8%8A%9D%E6%A1%9C%28%E3%81%97%E3%81%B0%E3%81%96%E3%81%8F%E3%82%89%29.jpg",
"Chimpanzee": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg/250px-015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg",
"Chinese alligator": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/ChineseAlligator15.JPG/250px-ChineseAlligator15.JPG",
"Chrysanthemum": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Chrysanthemum_nangkingense.jpg/250px-Chrysanthemum_nangkingense.jpg",
"Cinchona tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Cinchona.pubescens01.jpg/250px-Cinchona.pubescens01.jpg",
"Cloudberry": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Rubus_chamaemorus%2C_from_Troms%C3%B8%2C_August_2020.jpeg/250px-Rubus_chamaemorus%2C_from_Troms%C3%B8%2C_August_2020.jpeg",
"Clownfish": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg/250px-Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg",
"Coast redwood": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/US_199_Redwood_Highway.jpg/250px-US_199_Redwood_Highway.jpg",
"Coco de mer palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Female_Coco_de_Mer_nut_in_the_surf.jpg/250px-Female_Coco_de_Mer_nut_in_the_surf.jpg",
"Coconut crab": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Coconut_Crab_Birgus_latro.jpg/250px-Coconut_Crab_Birgus_latro.jpg",
"Coconut palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg/250px-Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg",
"Coffee plant": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Coffee_Flowers.JPG/250px-Coffee_Flowers.JPG",
"Cork oak": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Cork_oak_%2828864190188%29.jpg/250px-Cork_oak_%2828864190188%29.jpg",
"Cornflower": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Centaurea_cyanus_flower_001.jpg/250px-Centaurea_cyanus_flower_001.jpg",
"Coyote": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/2009-Coyote-Yosemite.jpg/250px-2009-Coyote-Yosemite.jpg",
"Cuscus": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/KUSKUS_DI_TAHURA_BONTOBAHARI.jpg/250px-KUSKUS_DI_TAHURA_BONTOBAHARI.jpg",
"Cypress tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Taxodium_distichum_NRCSMS01010.jpg/250px-Taxodium_distichum_NRCSMS01010.jpg",
"Dahlia": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Dahlia_x_hybrida.jpg/250px-Dahlia_x_hybrida.jpg",
"Date palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Dates005.jpg/250px-Dates005.jpg",
"Dawn redwood": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Metasequoia_glyptostroboides_in_Forest_park_of_Aichi_Prefecture.jpg/250px-Metasequoia_glyptostroboides_in_Forest_park_of_Aichi_Prefecture.jpg",
"Desert monitor lizard": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Varanus_griseus_griseus_349843922.jpg/250px-Varanus_griseus_griseus_349843922.jpg",
"Douglas fir": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pseudotsuga_menziesii_4584.JPG/250px-Pseudotsuga_menziesii_4584.JPG",
"Dromedary camel": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Camelus_dromedarius_in_Nuweiba.jpg/250px-Camelus_dromedarius_in_Nuweiba.jpg",
"Ebony tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Malabar_Ebony.jpg/250px-Malabar_Ebony.jpg",
"Edelweiss": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Alpen_Edelwei%C3%9F%2C_Leontopodium_alpinum_2.JPG/250px-Alpen_Edelwei%C3%9F%2C_Leontopodium_alpinum_2.JPG",
"Egyptian vulture": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Egyptian_Vulture%2C_Socotra.jpg/250px-Egyptian_Vulture%2C_Socotra.jpg",
"Emu": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Emu_1_-_Tidbinbilla.jpg/250px-Emu_1_-_Tidbinbilla.jpg",
"English oak": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Quercus_robur.jpg/250px-Quercus_robur.jpg",
"Esparto grass": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Weaving_esparto.jpg/250px-Weaving_esparto.jpg",
"Eucalyptus (gum tree)": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Eucalyptus_tereticornis_flowers%2C_capsules%2C_buds_and_foliage.jpeg/250px-Eucalyptus_tereticornis_flowers%2C_capsules%2C_buds_and_foliage.jpeg",
"European bison": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/European_bison_%28Bison_bonasus%29_male_Bia%C5%82owieza.jpg/250px-European_bison_%28Bison_bonasus%29_male_Bia%C5%82owieza.jpg",
"European robin": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Erithacus_rubecula_with_cocked_head.jpg/250px-Erithacus_rubecula_with_cocked_head.jpg",
"European wildcat": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Felis_silvestris_silvestris_Luc_Viatour.jpg/250px-Felis_silvestris_silvestris_Luc_Viatour.jpg",
"Fennec fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Fennec_Fox_Vulpes_zerda.jpg/250px-Fennec_Fox_Vulpes_zerda.jpg",
"Fig tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Sycomoros_old.jpg/250px-Sycomoros_old.jpg",
"Fireweed": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Maitohorsma_%28Epilobium_angustifolium%29.JPG/250px-Maitohorsma_%28Epilobium_angustifolium%29.JPG",
"Flamingo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flamingos_Laguna_Colorada.jpg/250px-Flamingos_Laguna_Colorada.jpg",
"Flying fox (fruit bat)": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Polynesian_flying_fox_%28Pteropus_tonganus%29_in_flight_Taveuni.jpg/250px-Polynesian_flying_fox_%28Pteropus_tonganus%29_in_flight_Taveuni.jpg",
"Forest elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Loxodontacyclotis.jpg/250px-Loxodontacyclotis.jpg",
"Formosan black bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Formosan_Black_Bear.JPG/250px-Formosan_Black_Bear.JPG",
"Frangipani": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Plumeria_rubra-4.JPG/250px-Plumeria_rubra-4.JPG",
"Frankincense tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Boswellia_sacra.jpg/250px-Boswellia_sacra.jpg",
"Frigatebird": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Male_Frigate_bird.jpg/250px-Male_Frigate_bird.jpg",
"Giant lobelia": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Giant_lobelia_and_senecio_plants.jpg/250px-Giant_lobelia_and_senecio_plants.jpg",
"Giant panda": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/250px-Grosser_Panda.JPG",
"Giant river otter": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Giant_otters_%28Pteronura_brasiliensis%29.jpg/250px-Giant_otters_%28Pteronura_brasiliensis%29.jpg",
"Giant sequoia": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Grizzly_Giant_Mariposa_Grove.jpg/250px-Grizzly_Giant_Mariposa_Grove.jpg",
"Giant water lily (Victoria amazonica)": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Victoria_Regia_by_William_Sharp%2C_digitally_enhanced_by_rawpixel-com_5.jpg/250px-Victoria_Regia_by_William_Sharp%2C_digitally_enhanced_by_rawpixel-com_5.jpg",
"Gibbon": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Hylobates_lar_-_Kaeng_Krachan_WB.jpg/250px-Hylobates_lar_-_Kaeng_Krachan_WB.jpg",
"Ginkgo tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/GINKGOBAUM-2.jpg/250px-GINKGOBAUM-2.jpg",
"Giraffe": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/250px-Giraffe_Mikumi_National_Park.jpg",
"Golden eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/015_Wild_Golden_Eagle_in_flight_at_Pfyn-Finges_%28Switzerland%29_Photo_by_Giles_Laurent.jpg/250px-015_Wild_Golden_Eagle_in_flight_at_Pfyn-Finges_%28Switzerland%29_Photo_by_Giles_Laurent.jpg",
"Golden snub-nosed monkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Golden_Snub-nosed_Monkeys%2C_Qinling_Mountains_-_China.jpg/250px-Golden_Snub-nosed_Monkeys%2C_Qinling_Mountains_-_China.jpg",
"Golden wattle": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Acacia_pycnantha_Golden_Wattle.jpg/250px-Acacia_pycnantha_Golden_Wattle.jpg",
"Gorilla": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gorille_des_plaines_de_l%27ouest_%C3%A0_l%27Espace_Zoologique.jpg/250px-Gorille_des_plaines_de_l%27ouest_%C3%A0_l%27Espace_Zoologique.jpg",
"Grandidier's baobab": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Adansonia_grandidieri04.jpg/250px-Adansonia_grandidieri04.jpg",
"Grapevine": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Vitis_californica_with_grapes.jpg/250px-Vitis_californica_with_grapes.jpg",
"Green iguana": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Iguana_iguana_%28male_resting%29.jpg/250px-Iguana_iguana_%28male_resting%29.jpg",
"Greenheart tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Greenheart_%2813927555000%29.jpg/250px-Greenheart_%2813927555000%29.jpg",
"Grey seal": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Focas_grises_%28Halichoerus_grypus%29%2C_playa_de_Horsey%2C_Norfolk%2C_Inglaterra%2C_2022-11-20%2C_DD_11.jpg/250px-Focas_grises_%28Halichoerus_grypus%29%2C_playa_de_Horsey%2C_Norfolk%2C_Inglaterra%2C_2022-11-20%2C_DD_11.jpg",
"Grey wolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Eurasian_wolf_2.jpg/250px-Eurasian_wolf_2.jpg",
"Griffon vulture": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Gyps_fulvus_in_flight_-_Spain.jpg/250px-Gyps_fulvus_in_flight_-_Spain.jpg",
"Grizzly bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/GrizzlyBearJeanBeaufort.jpg/250px-GrizzlyBearJeanBeaufort.jpg",
"Guanaco": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Guanaco_%28Lama_guanicoe%29_Leona_Amarga.jpg/250px-Guanaco_%28Lama_guanicoe%29_Leona_Amarga.jpg",
"Harpy eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Harpia_harpyja_001_800.jpg/250px-Harpia_harpyja_001_800.jpg",
"Heather": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/CallunaVulgaris.jpg/250px-CallunaVulgaris.jpg",
"Hector's dolphin": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Hector%27s_Dolphins_at_Porpoise_Bay_1999_a_cropped.jpg/250px-Hector%27s_Dolphins_at_Porpoise_Bay_1999_a_cropped.jpg",
"Hedgehog": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Igel.JPG/250px-Igel.JPG",
"Heliconia": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Heliconia_latispatha_%28Starwiz%29.jpg/250px-Heliconia_latispatha_%28Starwiz%29.jpg",
"Hibiscus": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Hibiscus_flower_TZ.jpg/250px-Hibiscus_flower_TZ.jpg",
"Hippopotamus": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Portrait_Hippopotamus_in_the_water.jpg/250px-Portrait_Hippopotamus_in_the_water.jpg",
"Hoatzin bird": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Hoatzin_%28Opisthocomus_hoazin%29_Rio_Napo.jpg/250px-Hoatzin_%28Opisthocomus_hoazin%29_Rio_Napo.jpg",
"Holly": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Ilex-aquifolium_%28Europaeische_Stechpalme-1%29.jpg/250px-Ilex-aquifolium_%28Europaeische_Stechpalme-1%29.jpg",
"Holm oak": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Quercus_ilex_JPG1.jpg/250px-Quercus_ilex_JPG1.jpg",
"Hornbeam": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Carpinus_foliage.jpg/250px-Carpinus_foliage.jpg",
"Hornbill": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg/250px-Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg",
"Howler monkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Mantled_howler_monkey_and_baby_%2881337%292.jpg/250px-Mantled_howler_monkey_and_baby_%2881337%292.jpg",
"Hummingbird": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Trinidad_and_Tobago_hummingbirds_composite.jpg/250px-Trinidad_and_Tobago_hummingbirds_composite.jpg",
"Hyacinth macaw": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/008_Hyacinth_macaw_couple_kissing_under_Pink_Ip%C3%AA_tree_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg/250px-008_Hyacinth_macaw_couple_kissing_under_Pink_Ip%C3%AA_tree_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",
"Iberian lynx": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Lince_ib%C3%A9rico_%28Lynx_pardinus%29%2C_Almuradiel%2C_Ciudad_Real%2C_Espa%C3%B1a%2C_2021-12-19%2C_DD_07.jpg/250px-Lince_ib%C3%A9rico_%28Lynx_pardinus%29%2C_Almuradiel%2C_Ciudad_Real%2C_Espa%C3%B1a%2C_2021-12-19%2C_DD_07.jpg",
"Iberian wolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Iberian_Wolf_AdF_001.jpg/250px-Iberian_Wolf_AdF_001.jpg",
"Imperial parrot": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Amazona_imperialis_-Roseau_-Dominica_-aviary-6a-3c.jpg/250px-Amazona_imperialis_-Roseau_-Dominica_-aviary-6a-3c.jpg",
"Indian elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Elephas_maximus_%28Bandipur%29.jpg/250px-Elephas_maximus_%28Bandipur%29.jpg",
"Indian rhinoceros": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg/250px-Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg",
"Ipê tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ipe_detail.jpg/250px-Ipe_detail.jpg",
"Iris": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Iris_sanguinea_cultivar%2C_Wakehurst_Place%2C_UK_-_Diliff.jpg/250px-Iris_sanguinea_cultivar%2C_Wakehurst_Place%2C_UK_-_Diliff.jpg",
"Italian wolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/C._l._italicus_in_MNP.jpg/250px-C._l._italicus_in_MNP.jpg",
"Jaguar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Standing_jaguar.jpg/250px-Standing_jaguar.jpg",
"Japanese black pine": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Japanese_Black_Pine%2C_National_Garden%2C_Tokyo.jpg/250px-Japanese_Black_Pine%2C_National_Garden%2C_Tokyo.jpg",
"Japanese macaque (snow monkey)": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Japanese_Snow_Monkey_%28Macaque%29_Mother_Grooms_Her_Young.jpg/250px-Japanese_Snow_Monkey_%28Macaque%29_Mother_Grooms_Her_Young.jpg",
"Japanese maple": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Acer_palmatum0.jpg/250px-Acer_palmatum0.jpg",
"Kangaroo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg/250px-Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg",
"Kapok (ceiba) tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Panguana-Lupuna-2008-2.jpg/250px-Panguana-Lupuna-2008-2.jpg",
"Kapok tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Panguana-Lupuna-2008-2.jpg/250px-Panguana-Lupuna-2008-2.jpg",
"Kauri tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Agathis_robusta2.JPG/250px-Agathis_robusta2.JPG",
"Kea parrot": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Nestor_notabilis_-Fiordland%2C_New_Zealand-8b.jpg/250px-Nestor_notabilis_-Fiordland%2C_New_Zealand-8b.jpg",
"King cobra": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/12_-_The_Mystical_King_Cobra_and_Coffee_Forests.jpg/250px-12_-_The_Mystical_King_Cobra_and_Coffee_Forests.jpg",
"King protea": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Peninsula_Sandstone_Fynbos_-_KingProtea_-_Table_Mountain.JPG/250px-Peninsula_Sandstone_Fynbos_-_KingProtea_-_Table_Mountain.JPG",
"Kiwi bird": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/TeTuatahianui.jpg/250px-TeTuatahianui.jpg",
"Klinkii pine": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Araucaria-hunsteinii.jpg/250px-Araucaria-hunsteinii.jpg",
"Koala": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Koala_climbing_tree.jpg/250px-Koala_climbing_tree.jpg",
"Koi carp": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Ojiya_Nishikigoi_no_Sato_ac_%283%29.jpg/250px-Ojiya_Nishikigoi_no_Sato_ac_%283%29.jpg",
"Kola nut tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Kolanut.jpg/250px-Kolanut.jpg",
"Komodo dragon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/202306_Varanus_komodoensis.jpg/250px-202306_Varanus_komodoensis.jpg",
"Korean pine": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Pinus_koraiensis%2C_Cheremshany%2C_Sikhote_Alin%2C_Russia.jpg/250px-Pinus_koraiensis%2C_Cheremshany%2C_Sikhote_Alin%2C_Russia.jpg",
"Lavender": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Single_lavender_flower02.jpg/250px-Single_lavender_flower02.jpg",
"Leatherback sea turtle": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg/250px-Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg",
"Lemon tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/250px-P1030323.JPG",
"Linden tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Kristinas_lind_2013.jpg/250px-Kristinas_lind_2013.jpg",
"Lingonberry": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Vaccinium_vitis-idaea_20060824_003.jpg/250px-Vaccinium_vitis-idaea_20060824_003.jpg",
"Lion": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/250px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
"Little blue penguin": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Eudyptula_minor_Bruny_1.jpg/250px-Eudyptula_minor_Bruny_1.jpg",
"Llama": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Llamas%2C_Vernagt-Stausee%2C_Italy.jpg/250px-Llamas%2C_Vernagt-Stausee%2C_Italy.jpg",
"Loggerhead sea turtle": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Loggerhead_sea_turtle.jpg/250px-Loggerhead_sea_turtle.jpg",
"Lotus": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Sacred_lotus_Nelumbo_nucifera.jpg/250px-Sacred_lotus_Nelumbo_nucifera.jpg",
"Lynx": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Lynx_heads_collage.jpg/250px-Lynx_heads_collage.jpg",
"Macadamia tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Macadamia_nuts_on_tree.JPG/250px-Macadamia_nuts_on_tree.JPG",
"Magellanic penguin": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/MagellanicPenguin.jpg/250px-MagellanicPenguin.jpg",
"Mahogany tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Genuine_Mahogany_veneer_with_ripple_marks.jpg/250px-Genuine_Mahogany_veneer_with_ripple_marks.jpg",
"Mandrill": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Mandrill_Albert_September_2015_Zoo_Berlin_%282%29.jpg/250px-Mandrill_Albert_September_2015_Zoo_Berlin_%282%29.jpg",
"Mango tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Mangoes_%28Magnifera_indica%29_from_India.jpg/250px-Mangoes_%28Magnifera_indica%29_from_India.jpg",
"Mangrove tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Sonneratia_alba_-_Manado_%282%29.JPG/250px-Sonneratia_alba_-_Manado_%282%29.JPG",
"Marsican brown bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Giacomina.png/250px-Giacomina.png",
"Marula tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Marula02.jpg/250px-Marula02.jpg",
"Mediterranean monk seal": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Monachus_monachus_DSC_0274.jpg/250px-Monachus_monachus_DSC_0274.jpg",
"Meerkat": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Meerkat_%28Suricata_suricatta%29_Tswalu.jpg/250px-Meerkat_%28Suricata_suricatta%29_Tswalu.jpg",
"Monarch butterfly": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Monarch_Butterfly_Danaus_plexippus_Male_2664px.jpg/250px-Monarch_Butterfly_Danaus_plexippus_Male_2664px.jpg",
"Monkey puzzle tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Araucaria_en_Parque_Nacional_Conguillio.jpg/250px-Araucaria_en_Parque_Nacional_Conguillio.jpg",
"Montezuma cypress": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/El_Sabinal%2C_Salto_de_los_Salado%2C_Aguascalientes_51.JPG/250px-El_Sabinal%2C_Salto_de_los_Salado%2C_Aguascalientes_51.JPG",
"Moorish gecko": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Common_wall_gecko_%28Tarentola_mauritanica%29_Huelva.jpg/250px-Common_wall_gecko_%28Tarentola_mauritanica%29_Huelva.jpg",
"Moose": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alaska_moose.jpg/250px-Alaska_moose.jpg",
"Mopane tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Colophospermum_mopane_arbre_MHNT%2C_crop.jpg/250px-Colophospermum_mopane_arbre_MHNT%2C_crop.jpg",
"Mora tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Nato.jpeg/250px-Nato.jpeg",
"Moreton Bay fig": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Moretonbayfigfrom1850.JPG/250px-Moretonbayfigfrom1850.JPG",
"Mānuka": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/M%C4%81nuka_flowers_and_foliage_-_Hooton_Reserve%2C_Auckland.jpg/250px-M%C4%81nuka_flowers_and_foliage_-_Hooton_Reserve%2C_Auckland.jpg",
"Neem tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Neem_Tree_in_Rajasthan%2C_India.jpg/250px-Neem_Tree_in_Rajasthan%2C_India.jpg",
"Nile crocodile": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/NileCrocodile.jpg/250px-NileCrocodile.jpg",
"Norway spruce": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Kuusk_Keila-Paldiski_rdt_%C3%A4%C3%A4res.jpg/250px-Kuusk_Keila-Paldiski_rdt_%C3%A4%C3%A4res.jpg",
"Oak tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Quercus_robur.jpg/250px-Quercus_robur.jpg",
"Oil palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Elaeis_guineensis0.jpg/250px-Elaeis_guineensis0.jpg",
"Okapi": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Saint-Aignan_%28Loir-et-Cher%29._Okapi.jpg/250px-Saint-Aignan_%28Loir-et-Cher%29._Okapi.jpg",
"Okoumé tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/MPADN0021.jpg/250px-MPADN0021.jpg",
"Olive tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Olivesfromjordan.jpg/250px-Olivesfromjordan.jpg",
"Ombú tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Umbu_%28do_tupi_umbu%2C_com_outro_significado%29%2C_Phytolacca_dioica%2C_em_Bag%C3%A9%2C_RS%2C_Brasil.jpg/250px-Umbu_%28do_tupi_umbu%2C_com_outro_significado%29%2C_Phytolacca_dioica%2C_em_Bag%C3%A9%2C_RS%2C_Brasil.jpg",
"Orange tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/OrangeBloss_wb.jpg/250px-OrangeBloss_wb.jpg",
"Orangutan": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Orang_Utan%2C_Semenggok_Forest_Reserve%2C_Sarawak%2C_Borneo%2C_Malaysia.JPG/250px-Orang_Utan%2C_Semenggok_Forest_Reserve%2C_Sarawak%2C_Borneo%2C_Malaysia.JPG",
"Orca (killer whale)": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Killerwhales_jumping.jpg/250px-Killerwhales_jumping.jpg",
"Orchid": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Plant_Orchid_Cymbidium_aloifolium_P1110661_05_-_cropped.jpg/250px-Plant_Orchid_Cymbidium_aloifolium_P1110661_05_-_cropped.jpg",
"Pandanus tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Pandanus_utilis_fruit.JPG/250px-Pandanus_utilis_fruit.JPG",
"Panther chameleon": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Panther_chameleon_%28Furcifer_pardalis%29_male_Nosy_Be.jpg/250px-Panther_chameleon_%28Furcifer_pardalis%29_male_Nosy_Be.jpg",
"Papyrus": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Papyrus.jpg/250px-Papyrus.jpg",
"Paradise flycatcher": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/R%C3%A9union_paradise_flycatcher_%28Terpsiphone_bourbonnensis_bourbonnensis%29_male.jpg/250px-R%C3%A9union_paradise_flycatcher_%28Terpsiphone_bourbonnensis_bourbonnensis%29_male.jpg",
"Passionflower": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/OQ_Passion_flower.jpg/250px-OQ_Passion_flower.jpg",
"Patagonian cypress": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Fitzroya_cupressoides.JPG/250px-Fitzroya_cupressoides.JPG",
"Peacock": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Peacock_Plumage.jpg/250px-Peacock_Plumage.jpg",
"Peony": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/PaeoniaSuffruticosa7.jpg/250px-PaeoniaSuffruticosa7.jpg",
"Peregrine falcon": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Falco_peregrinus_m_Humber_Bay_Park_Toronto.jpg/250px-Falco_peregrinus_m_Humber_Bay_Park_Toronto.jpg",
"Pink river dolphin": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Amazonas-Flussdelfin_Orinoko3.jpg/250px-Amazonas-Flussdelfin_Orinoko3.jpg",
"Pistachio tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Pistachio_vera.jpg/250px-Pistachio_vera.jpg",
"Platypus": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Duck-billed_platypus_%28Ornithorhynchus_anatinus%29_Scottsdale.jpg/250px-Duck-billed_platypus_%28Ornithorhynchus_anatinus%29_Scottsdale.jpg",
"Polar bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg/250px-Polar_Bear_-_Alaska_%28cropped%29.jpg",
"Pomegranate tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Punica_protopunica_470564352.jpg/250px-Punica_protopunica_470564352.jpg",
"Prickly pear cactus": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Opuntia_littoralis_var_vaseyi_4.jpg/250px-Opuntia_littoralis_var_vaseyi_4.jpg",
"Przewalski's wild horse": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Przewalskis_horse_02.jpg/250px-Przewalskis_horse_02.jpg",
"Puma": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Zeppelinstra%C3%9Fe_2_Herzogenaurach_03.JPG/250px-Zeppelinstra%C3%9Fe_2_Herzogenaurach_03.JPG",
"Pōhutukawa tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/PohutukawaCornwallis.jpg/250px-PohutukawaCornwallis.jpg",
"Quinoa": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Reismelde.jpg/250px-Reismelde.jpg",
"Quiver tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/QuiverTree-Namibia-2015.JPG/250px-QuiverTree-Namibia-2015.JPG",
"Raccoon dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Nyctereutes.png/250px-Nyctereutes.png",
"Raffia palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Raphia_australis.jpg/250px-Raphia_australis.jpg",
"Rafflesia (world's largest flower)": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Rafflesia_arnoldii_Bengkulu_01.jpg/250px-Rafflesia_arnoldii_Bengkulu_01.jpg",
"Red deer": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cervus_elaphus_Luc_Viatour_6.jpg/250px-Cervus_elaphus_Luc_Viatour_6.jpg",
"Red fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg/250px-Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg",
"Red squirrel": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Squirrel_posing.jpg/250px-Squirrel_posing.jpg",
"Red-crowned crane": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Grus_japonensis_-Hokkaido%2C_Japan_-several-8_%281%29.jpg/250px-Grus_japonensis_-Hokkaido%2C_Japan_-several-8_%281%29.jpg",
"Reindeer": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Reinbukken_p%C3%A5_frisk_gr%C3%B8nt_beite._-_panoramio.jpg/250px-Reinbukken_p%C3%A5_frisk_gr%C3%B8nt_beite._-_panoramio.jpg",
"Resplendent quetzal": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Resplendent_quetzal_san_gerardo_de_dota_3.31.24_DSC_3989-topaz-denoiseraw.jpg/250px-Resplendent_quetzal_san_gerardo_de_dota_3.31.24_DSC_3989-topaz-denoiseraw.jpg",
"Rhea": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Greater_rhea_pair_arp.jpg/250px-Greater_rhea_pair_arp.jpg",
"Rhododendron": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Alpenrose_%28Rhododendron_ferrugineum%29_%289135007571%29.jpg/250px-Alpenrose_%28Rhododendron_ferrugineum%29_%289135007571%29.jpg",
"Ring-tailed lemur": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Ring-tailed_lemur_%28Lemur_catta%29.jpg/250px-Ring-tailed_lemur_%28Lemur_catta%29.jpg",
"Rose": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Rosa_rubiginosa_1.jpg/250px-Rosa_rubiginosa_1.jpg",
"Rowan tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rowanberries_in_late_August_2004_in_Helsinki.jpg/250px-Rowanberries_in_late_August_2004_in_Helsinki.jpg",
"Rubber tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Hevea_brasiliensis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-071.jpg/250px-Hevea_brasiliensis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-071.jpg",
"Sable": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Sobol_bur.jpg/250px-Sobol_bur.jpg",
"Sago palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/C00sagopalme.jpg/250px-C00sagopalme.jpg",
"Saguaro cactus": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Carnegiea_gigantea_in_Saguaro_National_Park_near_Tucson%2C_Arizona_during_November_%2858%29.jpg/250px-Carnegiea_gigantea_in_Saguaro_National_Park_near_Tucson%2C_Arizona_during_November_%2858%29.jpg",
"Saiga antelope": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Saiga_antelope_at_the_Stepnoi_Sanctuary.jpg/250px-Saiga_antelope_at_the_Stepnoi_Sanctuary.jpg",
"Saker falcon": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Falco_cherrug_%28Marek_Szczepanek%29.jpg/250px-Falco_cherrug_%28Marek_Szczepanek%29.jpg",
"Sand gazelle": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Mountain_gazelle_%28Gazella_gazella%29_and_Arabian_sand_gazelle_%28Gazella_marica%29.jpg/250px-Mountain_gazelle_%28Gazella_gazella%29_and_Arabian_sand_gazelle_%28Gazella_marica%29.jpg",
"Sandalwood tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Sandalwood.jpg/250px-Sandalwood.jpg",
"Saxaul tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Saxaul-baum.JPG/250px-Saxaul-baum.JPG",
"Scarlet macaw": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Scarlet_macaw_%28Ara_macao_cyanopterus%29_Copan.jpg/250px-Scarlet_macaw_%28Ara_macao_cyanopterus%29_Copan.jpg",
"Scots pine": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Skuleskogen_pine.jpg/250px-Skuleskogen_pine.jpg",
"Sea turtle": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chelonia_mydas_is_going_for_the_air_edit.jpg/250px-Chelonia_mydas_is_going_for_the_air_edit.jpg",
"Shea tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Vitellaria_paradoxa_MS_6563.JPG/250px-Vitellaria_paradoxa_MS_6563.JPG",
"Siberian larch": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Siberian-larch.jpg/250px-Siberian-larch.jpg",
"Siberian pine": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Pinus_sibirica_in_Siberia.jpg/250px-Pinus_sibirica_in_Siberia.jpg",
"Siberian tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/P.t.altaica_Tomak_Male.jpg/250px-P.t.altaica_Tomak_Male.jpg",
"Sika deer": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cervus_nippon_002.jpg/250px-Cervus_nippon_002.jpg",
"Silver birch": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Betula_pendula_Finland.jpg/250px-Betula_pendula_Finland.jpg",
"Silver fern": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Alsophila_tricolor_kz03.jpg/250px-Alsophila_tricolor_kz03.jpg",
"Sloth": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Bicho-pregui%C3%A7a_3.jpg/250px-Bicho-pregui%C3%A7a_3.jpg",
"Snow leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.JPG/250px-Irbis4.JPG",
"South China tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/2012_Suedchinesischer_Tiger.JPG/250px-2012_Suedchinesischer_Tiger.JPG",
"Spanish imperial eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Aguila_Imperial_Entrando_Al_Posadero_%28125891767%29.jpeg/250px-Aguila_Imperial_Entrando_Al_Posadero_%28125891767%29.jpeg",
"Spectacled bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Tremarctos_ornatus_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg/250px-Tremarctos_ornatus_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg",
"Springbok": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/174_Male_Springbok_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg/250px-174_Male_Springbok_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg",
"Stone pine": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Pinus_pinea_Wellington_Botanic_Gardens.jpg/250px-Pinus_pinea_Wellington_Botanic_Gardens.jpg",
"Sturgeon": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Montr%C3%A9al_Biodome_Acipenser_oxyrinchus_%281%29.JPG/250px-Montr%C3%A9al_Biodome_Acipenser_oxyrinchus_%281%29.JPG",
"Sugar maple": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Acer_saccharum_1-jgreenlee_%285098070608%29.jpg/250px-Acer_saccharum_1-jgreenlee_%285098070608%29.jpg",
"Sunflower": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sunflower_sky_backdrop.jpg/250px-Sunflower_sky_backdrop.jpg",
"Tanuki (raccoon dog)": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Tanuki_in_Higashiyama_Zoo_-_2.jpg/250px-Tanuki_in_Higashiyama_Zoo_-_2.jpg",
"Taro plant": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Songe-R%C3%A9union.JPG/250px-Songe-R%C3%A9union.JPG",
"Tea plant": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Csinensis.jpg/250px-Csinensis.jpg",
"Teak tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Starr_010304-0485_Tectona_grandis.jpg/250px-Starr_010304-0485_Tectona_grandis.jpg",
"Toco toucan": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg/250px-006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",
"Traveler's palm": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ravenala%2C_travellers_palms%2C_on_Maui.jpg/250px-Ravenala%2C_travellers_palms%2C_on_Maui.jpg",
"Tree kangaroo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Matschies_tree_kangaroo_Dendrolagus_matschiei_at_Bronx_Zoo_1_cropped.jpg/250px-Matschies_tree_kangaroo_Dendrolagus_matschiei_at_Bronx_Zoo_1_cropped.jpg",
"Trillium": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/TrilliumErectum.jpg/250px-TrilliumErectum.jpg",
"Tuatara": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Tuatara_%285205719005%29.jpg/250px-Tuatara_%285205719005%29.jpg",
"Tulip": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/%D7%A6%D7%91%D7%A2%D7%95%D7%A0%D7%99%D7%9D.JPG/250px-%D7%A6%D7%91%D7%A2%D7%95%D7%A0%D7%99%D7%9D.JPG",
"Umbrella thorn acacia": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Vachellia_%28ex_Acacia%29_tortilis.jpg/250px-Vachellia_%28ex_Acacia%29_tortilis.jpg",
"Vanilla orchid": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Vanilla_planifolia_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-278.jpg/250px-Vanilla_planifolia_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-278.jpg",
"Walnut tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Juglans_major_Morton.jpg/250px-Juglans_major_Morton.jpg",
"West African giraffe": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Giraffe-solo_Koure-NIGER.jpg/250px-Giraffe-solo_Koure-NIGER.jpg",
"White rhinoceros": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/109_Male_White_rhinoceros_walking_in_the_Kalahari_Desert_of_Namibia_Photo_by_Giles_Laurent.jpg/250px-109_Male_White_rhinoceros_walking_in_the_Kalahari_Desert_of_Namibia_Photo_by_Giles_Laurent.jpg",
"White spruce": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/White_Spruce_Cones.jpg/250px-White_Spruce_Cones.jpg",
"White stork": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/White_stork_%28Ciconia_ciconia%29_Bia%C5%82owieza.jpg/250px-White_stork_%28Ciconia_ciconia%29_Bia%C5%82owieza.jpg",
"White-tailed deer": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/White-tailed_deer.jpg/250px-White-tailed_deer.jpg",
"White-tailed eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/NZ7_5265_%2852812350718%29.jpg/250px-NZ7_5265_%2852812350718%29.jpg",
"Wild apple tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Purple_prince_crabapple_tree.JPG/250px-Purple_prince_crabapple_tree.JPG",
"Wild boar": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Wildschwein%2C_N%C3%A4he_Pulverstampftor_%28cropped%29.jpg/250px-Wildschwein%2C_N%C3%A4he_Pulverstampftor_%28cropped%29.jpg",
"Wild orchid": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Plant_Orchid_Cymbidium_aloifolium_P1110661_05_-_cropped.jpg/250px-Plant_Orchid_Cymbidium_aloifolium_P1110661_05_-_cropped.jpg",
"Wild rose": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/RoseWilderLane01.jpg/250px-RoseWilderLane01.jpg",
"Wild tulip": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/%D7%A6%D7%91%D7%A2%D7%95%D7%A0%D7%99%D7%9D.JPG/250px-%D7%A6%D7%91%D7%A2%D7%95%D7%A0%D7%99%D7%9D.JPG",
"Wombat": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Vombatus_ursinus_-Maria_Island_National_Park.jpg/250px-Vombatus_ursinus_-Maria_Island_National_Park.jpg",
"Yerba mate": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ilex_paraguariensis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-074.jpg/250px-Ilex_paraguariensis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-074.jpg",
"Ylang-ylang tree": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Cananga_odorata_01.JPG/250px-Cananga_odorata_01.JPG",
"Zebra": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Plains_Zebra_Equus_quagga_cropped.jpg/250px-Plains_Zebra_Equus_quagga_cropped.jpg"
};
