// BrightSprouts Academy — Sprout's Wizard Quest.
// A fantasy adventure: apprentice Sprout journeys through 3 realms, each guarded by an elemental
// wizard, then challenges the Archmage in a final spell duel. Every "spell" is a real curriculum
// question for Sprout's own grade, generated by the SAME functions that already power the site's
// worksheets (genMath()/genKinder()) -- no new maths content is authored here, only reused. Duels
// are a friendly magic contest, not violence: a beaten wizard is impressed, not hurt, and joins
// Sprout's journey. All "3D" is the site's existing technique -- flat hand-drawn SVG layers turned
// in 3D space with CSS (perspective + translateZ), the same approach as the Paleontology diorama
// and Physics atom model -- not a WebGL library, so the game stays fully offline-capable.

const WIZ_STAGES = [
  { key: "ember",   name: "Ember the Flame Wizard",  need: 4, realm: "Ember Peaks",        element: "fire",   accent: "#e0552b", accent2: "#ffb26b" },
  { key: "glacius", name: "Glacius the Frost Wizard", need: 4, realm: "Frostglass Caverns", element: "ice",    accent: "#2f8fc4", accent2: "#aee6ff" },
  { key: "tempest", name: "Tempest the Storm Wizard", need: 5, realm: "Skyreach Spire",     element: "storm",  accent: "#6b5bce", accent2: "#c9baff" }
];
const WIZ_BOSS = { key: "arch", name: "Archmage Lumis", need: 6, realm: "The Starlit Sanctum", element: "arcane", accent: "#c9a227", accent2: "#fff0b3" };
function wizAllStages() { return WIZ_STAGES.concat([WIZ_BOSS]); }

// ---------- curriculum-aligned question pool ----------
// Grade 0 has no genMath() branch (its "maths" lives under the Kindergarten "counting" subject,
// generated by genKinder()); grades 1-12 use the site's real per-grade generator directly.
function wizardPool(grade) {
  if (grade === 0) return (typeof genKinder === "function" && typeof LESSONS !== "undefined" && LESSONS[0] && LESSONS[0].counting)
    ? genKinder("counting", LESSONS[0].counting) : [];
  return (typeof genMath === "function") ? genMath(grade) : [];
}
// Multiple-choice options built by jittering ONE embedded number inside the answer string, so it
// works uniformly across every answer shape genMath() produces: a plain number ("27"), "x = 5",
// a fraction ("3/8"), a ratio ("2:3"), a unit suffix ("≈ 78.50", "55°"), or an algebra expression
// with several numbers embedded ("x² + 8x + 15") -- jittering one keeps the same shape/format
// while guaranteeing a different, still-plausible-looking wrong answer.
function wizardOptions(answer) {
  const s = String(answer);
  const nums = [...s.matchAll(/-?\d+(\.\d+)?/g)];
  const opts = new Set([s]);
  if (nums.length) {
    let guard = 0;
    while (opts.size < 4 && guard < 60) {
      guard++;
      const m = nums[rand(nums.length)];
      const orig = m[0], val = parseFloat(orig), isInt = orig.indexOf(".") === -1;
      const jitter = Math.max(1, Math.round(Math.abs(val) * 0.3) + 1);
      let nv = val + (rand(2) ? 1 : -1) * (1 + rand(jitter));
      if (isInt) nv = Math.round(nv);
      const ns = s.slice(0, m.index) + nv + s.slice(m.index + orig.length);
      if (ns !== s) opts.add(ns);
    }
  }
  let filler = 1;
  while (opts.size < 4) { const f = s + " ".repeat(filler); if (!opts.has(f)) opts.add(f); filler++; }
  return shuffleArr([...opts]);
}

// ---------- drawing: the 3D-turntable arena, reused for every realm ----------
function wqArena(stage) {
  const skyTop = { fire: "#3a1e14", ice: "#132a3a", storm: "#241a3a", arcane: "#1a1430" }[stage.element];
  const skyBot = { fire: "#5a2a1a", ice: "#1f4058", storm: "#332155", arcane: "#2a2050" }[stage.element];
  const ground = { fire: "#7a3a24", ice: "#8fbfd6", storm: "#5a4f8a", arcane: "#4a3f7a" }[stage.element];
  return `<defs>
      <linearGradient id="wq-sky" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="${skyTop}"/><stop offset="1" stop-color="${skyBot}"/>
      </linearGradient>
    </defs>
    <rect width="320" height="220" fill="url(#wq-sky)"/>
    ${wqBackdrop(stage)}
    <ellipse cx="160" cy="205" rx="200" ry="26" fill="${ground}" opacity=".9"/>
    <ellipse cx="160" cy="200" rx="150" ry="16" fill="${stage.accent}" opacity=".25"/>`;
}
function wqBackdrop(stage) {
  if (stage.element === "fire") {
    return `<path d="M-10 180 L60 90 L120 180 Z" fill="#7a3a24" opacity=".8"/>
      <path d="M40 180 L120 60 L200 180 Z" fill="#8f4a2c" opacity=".8"/>
      <circle cx="120" cy="70" r="7" fill="${stage.accent}" class="wq-tw"/>
      <circle cx="70" cy="95" r="5" fill="${stage.accent2}" class="wq-tw" style="animation-delay:.4s"/>`;
  }
  if (stage.element === "ice") {
    return `<path d="M-10 180 L50 70 L110 180 Z" fill="#c9e8f5" opacity=".7"/>
      <path d="M60 180 L140 50 L220 180 Z" fill="#eaf7fc" opacity=".7"/>
      <path d="M40 180 L50 70 L60 180 Z" fill="#aee6ff" opacity=".9"/>`;
  }
  if (stage.element === "storm") {
    return `<ellipse cx="80" cy="70" rx="60" ry="22" fill="#3a2e66" opacity=".8" class="wq-drift"/>
      <ellipse cx="220" cy="55" rx="70" ry="24" fill="#463a78" opacity=".8" class="wq-drift" style="animation-delay:1.2s"/>
      <path d="M150 90 l-8 22 10 -2 -10 24" stroke="${stage.accent2}" stroke-width="3" fill="none" class="wq-bolt"/>`;
  }
  return `<circle cx="60" cy="50" r="2" fill="#fff" class="wq-tw"/><circle cx="110" cy="35" r="1.6" fill="#fff" class="wq-tw" style="animation-delay:.3s"/>
    <circle cx="200" cy="45" r="2" fill="#fff" class="wq-tw" style="animation-delay:.6s"/><circle cx="250" cy="65" r="1.6" fill="#fff" class="wq-tw" style="animation-delay:.9s"/>
    <path d="M60 190 Q160 120 260 190" stroke="${stage.accent}" stroke-width="2" fill="none" opacity=".5"/>`;
}
// Sprout the apprentice: the same character from js/castle-game.js, plus a hat and wand so the
// theme reads as "wizard" without redrawing the whole figure. Position is on the OUTER group only
// (a plain SVG attribute); the animation classes stay on cqSprout's own inner group -- a CSS
// "transform" animation on a group that also carries translate(x,y) replaces the attribute
// instead of composing with it (see js/castle-game.js for where this first broke).
function wqSprout(x, y, cast) {
  const wand = cast ? `<path d="M18 -20 L34 -46" stroke="#8a5f2e" stroke-width="3" stroke-linecap="round"/>
      <circle cx="35" cy="-48" r="4.5" fill="#ffe9a8" class="wq-orbglow"/>` :
    `<path d="M20 4 L32 -18" stroke="#8a5f2e" stroke-width="3" stroke-linecap="round"/><circle cx="33" cy="-20" r="3.5" fill="#ffe9a8"/>`;
  return `<g transform="translate(${x} ${y})">
    ${cqSprout(0, 0, cast)}
    <path d="M-16 -38 L16 -38 L0 -62 Z" fill="#3f2f6b" stroke="#241a3a" stroke-width="1.4"/>
    <circle cx="0" cy="-62" r="3.5" fill="#ffd166"/>
    ${wand}
  </g>`;
}
// One shared wizard silhouette, coloured/shaped per element. mood: "idle" or "impressed" (after losing the duel).
function wqWizard(stage, mood, shield, need) {
  const happy = mood === "impressed";
  const robe = stage.accent, robeDk = happy ? stage.accent2 : "#241a3a";
  const smile = happy ? "M-9 12 q9 9 18 0" : "M-9 13 q9 -3 18 0";
  const brows = happy ? `M-12 -8 q6 -3 11 1 M12 -8 q-6 -3 -11 1` : `M-13 -5 q6 -5 12 -1 M13 -5 q-6 -5 -12 -1`;
  const pct = Math.max(0, Math.min(1, shield / need));
  return `<g class="wq-wizard${happy ? " wq-impressed" : " wq-idle"}">
    <ellipse cx="0" cy="80" rx="32" ry="7" fill="rgba(10,6,20,.35)"/>
    <path d="M-9 -18 C -28 6, -32 40, -28 70 Q0 80 28 70 C 32 40, 28 6, 9 -18 Z" fill="${robe}" stroke="${robeDk}" stroke-width="2.4"/>
    <path d="M-26 34 Q0 44 26 34" stroke="${robeDk}" stroke-width="3" fill="none" opacity=".55"/>
    <path d="M-20 -6 Q0 6 20 -6 L20 -2 Q0 10 -20 -2 Z" fill="${robeDk}" opacity=".35"/>
    <path d="M-9 -18 q-16 20 -13 40" stroke="${robeDk}" stroke-width="6" fill="none" stroke-linecap="round"/>
    <path d="M9 -18 q16 20 13 40" stroke="${robeDk}" stroke-width="6" fill="none" stroke-linecap="round"/>
    <circle cx="0" cy="-34" r="20" fill="#ffe3c2"/>
    <path d="M-19 -40 Q0 -50 19 -40 L0 -82 Z" fill="${robe}" stroke="${robeDk}" stroke-width="2.2"/>
    <ellipse cx="0" cy="-40" rx="20" ry="5" fill="${robeDk}" opacity=".4"/>
    <circle cx="0" cy="-82" r="4" fill="${stage.accent2}" class="wq-tw"/>
    <ellipse cx="-7" cy="-33" rx="3.2" ry="3.8" fill="#241a3a"/><ellipse cx="7" cy="-33" rx="3.2" ry="3.8" fill="#241a3a"/>
    <path d="${brows}" stroke="${robeDk}" stroke-width="2.2" fill="none" stroke-linecap="round"/>
    <path d="${smile}" stroke="#241a3a" stroke-width="2" fill="none" stroke-linecap="round"/>
    <path d="M-24 24 Q-40 22 -42 6" stroke="${robeDk}" stroke-width="7" fill="none" stroke-linecap="round"/>
    <path d="M24 24 Q40 20 42 0" stroke="${robeDk}" stroke-width="7" fill="none" stroke-linecap="round"/>
    <path d="M42 0 L42 -36" stroke="#8a5f2e" stroke-width="3.4" stroke-linecap="round"/>
    <circle cx="42" cy="-39" r="6" fill="${stage.accent2}" class="wq-orbglow"/>
  </g>
  <g class="wq-shield"><rect x="-40" y="94" width="80" height="8" rx="4" fill="#241a3a" opacity=".5"/>
    <rect x="-40" y="94" width="${(80 * pct).toFixed(1)}" height="8" rx="4" fill="${stage.accent}"/></g>
  ${happy ? `<g class="cq-sparkle"><text x="-40" y="-64" font-size="14">✨</text><text x="32" y="-72" font-size="12">✨</text></g>` : ""}`;
}
function wizardScene(stage, mood, shield, need, casting) {
  return `${wqArena(stage)}
    ${wqSprout(70, 168, casting)}
    <g transform="translate(228 108)">${wqWizard(stage, mood, shield, need)}</g>
    ${casting ? `<circle class="wq-bolt-orb" cx="0" cy="0" r="7" fill="#ffe9a8"/>` : ""}`;
}
