// BrightSprouts Academy — Story Library (1-25)
// themes: adventure | strangers (kids helping strangers) | home (helping at home)
const STORIES = [
{ id:1, title:"The Map in the Attic", theme:"adventure", ages:"6-9", moral:"Teamwork turns big problems into small ones.",
text:`Twins Theo and June found a dusty map in Grandpa's attic, marked with a red X behind the old orchard. They packed sandwiches and set off. The trail crossed a creek too wide for one jump — but June held the backpack while Theo laid a fallen branch across, and they crossed together. At the X they dug up a tin box holding Grandpa's childhood marbles and a note: "Treasure is better with a partner." When they showed Grandpa, he laughed until he cried. "I buried that with my brother sixty years ago," he said. "Took two of us then, too."` },

{ id:2, title:"Rosie and the Lighthouse Storm", theme:"adventure", ages:"7-10", moral:"Being brave means doing the right thing even when you're scared.",
text:`Rosie's aunt kept the lighthouse, and Rosie loved polishing its great lamp. One evening a storm rolled in fast, and Aunt Meri slipped on the wet stairs and hurt her ankle. "The lamp, Rosie," she winced. "Boats are counting on it." Rosie's legs shook as she climbed the spiral stairs alone, wind rattling every window. Step by step, she reached the top and lit the lamp just as darkness swallowed the sea. A fishing boat found its way home that night. Rosie learned that brave people feel scared too — they just keep climbing anyway.` },

{ id:3, title:"The Whispering Cave", theme:"adventure", ages:"7-10", moral:"Telling the truth quickly makes hard things easier.",
text:`Marco and Ben discovered a cave behind the waterfall — the one place their parents said was off-limits. Inside, Ben slipped and dropped Dad's good flashlight into a crack. They hiked home in silence, planning excuses. But at dinner, Marco's stomach hurt from the secret. "We went to the cave," he blurted. "I'm sorry. We lost the flashlight." Dad was quiet, then nodded. "I'm not happy. But I'm proud you told me — that cave floods at night. Now I know to warn other kids." The truth cost them two weeks of dishes. A lie could have cost much more.` },

{ id:4, title:"Captain Mila's Paper Boat", theme:"adventure", ages:"5-8", moral:"Don't give up — try again a different way.",
text:`Mila built a paper boat and named it The Dragonfly. At the park pond, it tipped over at once. She built a second with folded sides. It floated — then soaked through and sank. Other kids drifted away, but Mila studied the ducks gliding by. "Wax!" she said. That night she rubbed a candle stub over her third boat until the paper shone. In the morning, The Dragonfly III sailed all the way across the pond, past the fountain, into legend. "How did you make it work?" a boy asked. Mila grinned. "I didn't. My first two boats taught me how."` },

{ id:5, title:"The Lost Kite of Cloud Hill", theme:"adventure", ages:"6-9", moral:"Persistence finds what quitting never will.",
text:`When the string snapped, Kavi's homemade kite vanished over Cloud Hill. "It's gone," his cousin shrugged. "Make another." But Kavi had painted that kite with his grandmother before she moved away. He searched the meadow — nothing. The hedges — nothing. On the third afternoon, he noticed sheep wool snagged on a fence, all leaning east, and realized the wind curled around the hill. He followed the wind's path to a lone oak, and there was his kite, caught but unharmed. Kavi climbed carefully and brought it down. Some things are worth three afternoons.` },

{ id:6, title:"Two Flashlights in the Forest", theme:"adventure", ages:"8-11", moral:"Preparation is a gift you give your future self.",
text:`On the class camping trip, Dani packed exactly what the checklist said, even the boring things: extra batteries, whistle, rain poncho. Her tentmate Bree teased her: "It's one night, not an expedition." At dusk, their group took a wrong turn on the loop trail. Phones had no signal, and Bree's flashlight died within minutes. Dani handed over her spare, then blew her whistle in threes until the rangers answered. Back at camp, wrapped in dry ponchos while others shivered, Bree bumped Dani's shoulder. "Next trip, I'm copying your whole backpack."` },

{ id:7, title:"The Turtle Who Needed a Ride", theme:"adventure", ages:"5-8", moral:"An adventure is a chance to be kind along the way.",
text:`Pia and her dad were racing to the summit of Bluebell Trail to watch the sunrise. Halfway up, Pia spotted a box turtle stranded in the middle of the gravel road, cars possible any minute. "We'll miss the sunrise," Dad warned gently. Pia carried the turtle carefully in the direction it was already heading and set it in the ferns. They reached the summit late — the sun was already up, golden over the valley. "We missed it," Pia sighed. Dad shook his head. "The turtle didn't. Best view I've ever had."` },

{ id:8, title:"The Secret Garden Door", theme:"adventure", ages:"6-9", moral:"Patience grows the best surprises.",
text:`Behind the ivy on Nonna's wall, Luca found a small green door, locked tight. "What's inside?" he begged. Nonna smiled. "A surprise — but it isn't ready. Help me and you'll see." All spring, Luca watered, weeded, and waited, sure that treasure sat behind that door. In June, Nonna finally turned a brass key. Inside was a tiny walled garden Luca had been watering through a pipe all along — now bursting with strawberries, sunflowers taller than his head, and a bench with his name carved into it. "Patience," said Nonna, "is just planting you can't see yet."` },

{ id:9, title:"Sam and the Star Compass", theme:"adventure", ages:"8-11", moral:"Believe in what you've learned — and in yourself.",
text:`At astronomy camp, Sam was the quiet kid who memorized the night sky while others goofed off. On the final hike, the counselor's GPS glitched, and the group stood at a fork of three dark trails. "We're lost," someone moaned. Sam looked up, found the Big Dipper, and traced its edge stars to the North Star, hanging steady above the leftmost trail. "Camp is north," Sam said — quietly at first, then again, louder. They walked twenty minutes and saw the campfire glow. Nobody called Sam the quiet kid after that. They called him Compass.` },

{ id:10, title:"The River Race", theme:"adventure", ages:"7-10", moral:"Winning fairly is the only real winning.",
text:`Every summer, the neighborhood kids raced homemade rafts down Miller's Creek. This year Owen was sure he'd win — until he saw Jonah's raft drifting toward the rocks, its rope tangled around Jonah's ankle. Owen paddled over and tugged the rope free, watching two rafts glide past them both. They finished dead last, together. At the finish line, the older kids had already heard what happened. They took the blue ribbon and cut it in half. "New rule," said the oldest. "The race counts the whole river — not just the finish."` },

{ id:11, title:"The Mountain of Marbles", theme:"adventure", ages:"5-8", moral:"Sharing multiplies joy instead of dividing it.",
text:`On the last day of the fair, Nina won the grand prize: a jar of one hundred glitter marbles. Walking home, she met Tomas sitting on the curb — his ride had left without him, and his own game tokens were spent. Nina sat down to wait with him and poured marbles into his hands, teaching him her favorite game right there on the sidewalk. By the time his mother arrived, they'd invented three new games and laughed until their sides hurt. That summer they wore grooves in the sidewalk playing marbles. A jar shared, Nina decided, holds twice as much.` },

{ id:12, title:"The Night the Tent Flew Away", theme:"adventure", ages:"7-10", moral:"Staying calm is a superpower anyone can learn.",
text:`A midnight gust ripped the tent stakes loose, and Ellie's little brother began to panic as their shelter tumbled across the campsite. Ellie felt panic rising too — then remembered what her swim coach always said: "Slow breath. One problem at a time." She took the breath. "Aiden, hold the flashlight. Just that." He held it. She caught the tent against a picnic table, dad arrived to help re-stake it, and in ten minutes they were back in sleeping bags, hearts still thumping. "How were you so calm?" Aiden whispered. "I wasn't," Ellie said. "I just went one problem at a time."` },

{ id:13, title:"The Message in the Bottle", theme:"adventure", ages:"8-11", moral:"Finish what you start — someone may be counting on it.",
text:`Beachcombing after a storm, Kofi found a bottle holding a soggy note: "My grandpa built this boat, the Halcyon. If found, please write to me — Amos, Port Clyde." Kofi's friends said mailing it was pointless; the note looked years old. But Kofi had promised the wet paper — silently, the way you do. He wrote the letter that night. Weeks later a reply arrived: Amos was now old himself, and the bottle had sailed the sea for forty years. They became pen pals, and the next summer, Kofi stood in Port Clyde, shaking the hand of a friend the ocean had introduced.` },

{ id:14, title:"The Snowy Owl's Trail", theme:"adventure", ages:"7-10", moral:"Respect nature and it will show you wonders.",
text:`Zoe wanted a photo of the snowy owl more than anything. When she finally spotted it in the winter field, the other kids ran at it, phones out, and it vanished over the pines. Zoe stayed behind. Every day after school she returned quietly, sat on the same log, and scattered nothing, chased nothing, touched nothing. On the ninth day, the owl landed on a fence post ten steps away and looked straight at her. Zoe took one photo — then lowered the camera and just watched. The picture won the school contest, but the watching is what she still talks about.` },

{ id:15, title:"The Treasure That Wasn't Gold", theme:"adventure", ages:"6-9", moral:"Friendship is the real treasure.",
text:`Ana moved to Marlin Street the same week Diego found a "pirate coin" in the creek. All summer they hunted the rest of the treasure — digging under mossy stones, mapping the drainpipe caves, decoding scratches on the old bridge that turned out to be initials. In August, a museum lady told them the coin was just an old subway token. Diego groaned, but Ana laughed. "So our treasure was fake?" she said. "Then why was this the best summer ever?" Diego thought about it and grinned. They framed the token anyway. Some treasure just looks like a summer.` },

{ id:16, title:"The Balloon Over the Bay", theme:"adventure", ages:"6-9", moral:"Asking for help is brave, not weak.",
text:`Marisol's science-fair weather balloon — three months of work — tore free and drifted toward the bay. She chased it to the marina and stopped. She hated asking strangers for anything. But the balloon was sinking, so she took a breath and called to a fisherman untying his boat: "Please — can you help me? That's my experiment!" He could and he did, motoring out and hooking the balloon's tether with a gaff. "Lucky you spoke up," he said, handing it back. "Another minute and she was underwater." Marisol won a ribbon at the fair, but the lesson she kept was from the marina.` },

{ id:17, title:"The Cave of Echoes", theme:"adventure", ages:"5-8", moral:"The kindness you send out comes back to you.",
text:`Bruno the loud boy visited Echo Cave with his cousins. "You're slow!" he shouted at his little cousin, and the cave boomed SLOW... slow... slow. The little one's lip trembled. Bruno felt a twist in his chest. He tried again: "You're... doing great!" GREAT... great... great, sang the cave, and his cousin beamed and climbed faster. All afternoon Bruno experimented. Mean words came back mean. Kind words came back kind — three times each. On the walk home, Bruno was quiet. The world, he suspected, was one enormous Echo Cave. He decided to be careful what he shouted into it.` },

{ id:18, title:"The Umbrella at the Bus Stop", theme:"strangers", ages:"6-9", moral:"Small kindnesses can change someone's whole day.",
text:`Rain hammered the bus stop where Priya waited with her big yellow umbrella. An old man shuffled up without one, newspaper held uselessly over his head, water running off his sleeves. Priya scooted over. "There's room for two," she said. They shared the umbrella and he told her about driving buses himself for thirty years, on this very route. When her bus came, Priya pressed the umbrella into his hands. "I have a hood. You have six more blocks." He tried to refuse; she was already boarding. All week, a yellow umbrella waited for her at the bus stop, tied with a thank-you note.` },

{ id:19, title:"Mr. Aldo's Heavy Bags", theme:"strangers", ages:"5-8", moral:"Help doesn't wait to be asked.",
text:`Every Tuesday, Beto saw the same old man struggle up the hill from the market, resting his grocery bags on every low wall. One Tuesday, Beto crossed the street. "Can I carry one, sir? I'm going that way." He wasn't, really. The man — Mr. Aldo — talked the whole way up about his garden and his cat, Napoleon. It became their Tuesday routine. When Beto's family hit a hard month that winter, a basket of vegetables appeared on their step, with tomatoes redder than any store's. The note read: "From Napoleon's garden. Kindness grows back. — A."` },

{ id:20, title:"The New Kid at Lunch", theme:"strangers", ages:"6-10", moral:"Including one person can change everything for them.",
text:`Amir had eaten lunch alone for six days at his new school, studying his sandwich like it was homework. On day seven, a tray clattered down across from him. "I'm Jess. You're in my math class. Settle a debate: is a hot dog a sandwich?" Amir blinked, then laughed for the first time in a week — and argued no, absolutely not. Jess waved two more friends over to vote. By Friday, the lunch debate club was five kids strong, and Amir had invented its best question yet. Years later, at graduation, Jess's yearbook note read: "Still wrong about hot dogs. Glad I sat down."` },

{ id:21, title:"The Lost Puppy Poster", theme:"strangers", ages:"6-9", moral:"Going out of your way for others is never wasted.",
text:`Ruby saw the shivering puppy under the library steps and recognized it instantly — the sad-eyed face stapled to every telephone pole in town: BISCUIT. MUCH LOVED. The poster's address was eight blocks away, in the rain, opposite her way home. Ruby zipped the puppy inside her jacket and walked. The woman who opened the door made a sound Ruby had never heard before — half laugh, half sob — and knelt right on the wet porch. "You walked how far?" she kept asking. Ruby floated home, soaked and grinning. Being somebody's miracle, it turns out, is worth eight wet blocks.` },

{ id:22, title:"Grandma Pearl's Garden", theme:"strangers", ages:"7-10", moral:"Neighbors take care of neighbors.",
text:`The garden next door had gone wild since its owner came home from the hospital. Mo watched the old woman — not his grandma, but everyone called her Grandma Pearl — stare at the weeds from her window. Saturday morning, Mo knocked. "I mow lawns for money," he said, "but weeds I pull for stories." Pearl laughed and hired him on the spot, paying in lemonade and tales of when she was a trick rider in a traveling rodeo. By fall, the tomatoes were back, and half the neighborhood kids "worked" for stories. The garden got famous. So did the rodeo tales.` },

{ id:23, title:"The Wrong Bus", theme:"strangers", ages:"8-11", moral:"A few minutes of your time can rescue someone's whole day.",
text:`At the downtown station, Lena noticed a woman turning a paper map in circles, saying a street name to hurrying strangers who didn't stop. Lena stopped. The woman spoke little English, but she showed a photo: her daughter's graduation, starting in forty minutes across town. The map was for the wrong city — a printing mix-up. Lena walked her to Bay 12, checked with the driver, and wrote the stop's name in big letters on the map's corner. Weeks later, Lena's mom found a bakery box on their porch — the woman had asked the bus driver, who knew the neighborhood, to find "the girl who stopped."` },

{ id:24, title:"A Coat for the Cold Man", theme:"strangers", ages:"7-10", moral:"Generosity means giving what matters, not what's left over.",
text:`Winter hit early, and the man who sat near the bakery had only a thin jacket. Eli thought about him all through dinner. In his closet hung two coats: the old gray one he'd outgrown, and the new blue one he'd gotten for his birthday. The gray one would be easy to give. But it was too small for a grown man. Eli brought the blue one, plus his mom, who added soup and gloves and learned the man's name was Walter. Walter wore that blue coat all winter. Eli wore the gray one, a little snug, feeling warmer than he ever had in blue.` },

{ id:25, title:"The Farmer's Fallen Apples", theme:"strangers", ages:"5-8", moral:"Many hands make light work.",
text:`The tailgate of Farmer Rhodes' truck banged open on the hill, and a hundred apples went rolling down Main Street like red marbles. People stepped around them. The farmer, alone, chased his harvest with a bucket. Then Sofia parked her scooter and started gathering. Her brother joined. Then two kids from the bus stop, then a mail carrier, then a whole soccer team walking home. In ten minutes, every apple sat back in its crate, only a little dusty. Farmer Rhodes insisted every helper take an apple — and that fall, a crate marked FOR THE HELPERS OF MAIN STREET appeared at the school's front office.` }
];
