// BrightSprouts Academy — Story Library (26-50)
STORIES.push(
{ id:26, title:"The Library Whisperer", theme:"strangers", ages:"8-11", moral:"Sharing what you know is a gift that costs nothing.",
text:`Jaya noticed the same man at the library every Saturday, always at the computer desk, always frowning at job application forms. One day his frustration boiled over in a whisper: "I never learned this typing." Jaya, eleven and raised on keyboards, slid into the next chair. "Want the tricks? I know all of them." Week after week she coached him — home row, tab key, how to attach a résumé. In spring he arrived in a collared shirt, holding two hot chocolates. "First paycheck," he said, raising his cup. "The machine shop needed someone who could type the work orders."` },

{ id:27, title:"Lemonade for the Mail Carrier", theme:"strangers", ages:"5-8", moral:"Notice the people who work hard for you.",
text:`It was the hottest day of summer, so hot the sidewalk shimmered. From the window, Tessa watched the mail carrier trudge house to house, her cart heavy, her face red under her cap. Tessa's lemonade stand hadn't sold a single cup — everyone was hiding indoors. So she poured the biggest cup and ran it out to the curb. "On the house. You're the only one working today." The carrier drank it in one long grateful gulp. After that, the mail always seemed to come with a smile and a joke — and once, in December, with a candy cane taped to a postcard addressed simply: THE LEMONADE GIRL.` },

{ id:28, title:"The Broken Grocery Cart", theme:"strangers", ages:"6-9", moral:"Look around — someone near you needs a hand.",
text:`The wheel snapped off the cart right in the parking lot, and a hundred oranges, cans, and eggs tilted toward disaster. The young mother grabbed her toddler with one arm and the cart with the other, stuck. Dev and his dad were loading their own car. Dev didn't ask; he just jogged over and steadied the cart while his dad fetched a new one. They transferred every bag, and only one egg didn't make it. "You saved my whole Saturday," the mother laughed. In the car, Dev's dad tapped the wheel thoughtfully. "You saw her before I did," he said. "Keep those eyes."` },

{ id:29, title:"The Girl Who Spoke No English", theme:"strangers", ages:"6-10", moral:"Kindness speaks every language.",
text:`A new girl arrived mid-year, and the whispers said she spoke no English at all. At recess she stood at the fence, drawing in the dirt with a stick. Fatima walked over and saw the drawing: a cat. Fatima picked up her own stick and drew a dog. The girl added a bone. Fatima added a doghouse. Soon both were laughing at a mural of impossible animals. Fatima learned her name — Iryna — and taught her ten words; Iryna taught Fatima ten back. By June, Iryna gave a class presentation, in English, about her best friend. Everyone knew who she meant before she said it.` },

{ id:30, title:"The Old Sailor's Story", theme:"strangers", ages:"7-10", moral:"Listening is a way of giving.",
text:`At the retirement home where Miles' choir sang each month, one man never clapped — he only stared at the sea painting on the wall. The other kids avoided him. Miles sat down beside him instead. "Did you sail?" The man turned like a lighthouse beam. Forty years a merchant sailor — typhoons, whale songs, a port where the fish glowed. Miles came back the next month with a notebook, and the next. When the sailor passed away in spring, his daughter mailed Miles a package: the captain's compass, and a note. "You were the only one still asking. He navigated by that."` },

{ id:31, title:"Fixing Ferris's Flat Tire", theme:"strangers", ages:"8-11", moral:"Skills are for sharing.",
text:`Nobody at the trailhead could help the crying college kid — his bike tire was flat, his phone dead, his ride twenty miles off. But Ravi, twelve, had spent a rainy spring learning repairs at the community bike shop. "I can patch that," he said, and the whole trailhead turned. Ravi found the thorn, roughed the tube, set the patch, and pumped it firm while his mom lent her phone. The college kid — Ferris — insisted on paying; Ravi refused. So instead, Ferris rode twenty miles home and mailed the bike shop a donation "in honor of the twelve-year-old mechanic of Cedar Trail."` },

{ id:32, title:"The Ticket on the Ground", theme:"strangers", ages:"7-10", moral:"Integrity is what you do when no one is watching.",
text:`Outside the stadium, Noor spotted a fifty-dollar bill folded around a concert ticket, dropped in the crowd. Her cousin whistled. "Finders keepers — that's the rule." But Noor was already reading the ticket: Section C, Row 4 — tonight. Someone was about to have the worst night of their year. She brought it to the box office window, where a teenager was pleading with the clerk, near tears, pockets turned inside out. The look on his face when Noor held up the ticket was better than fifty dollars. "You're kidding," he kept saying. "People don't do this." "Some do," said Noor. "Pass it on."` },

{ id:33, title:"The Shivering Kitten at the Market", theme:"strangers", ages:"5-8", moral:"Caring for the helpless is everyone's job.",
text:`Under the flower stall at the Saturday market, something mewed. Junie knelt and found a soaked gray kitten, thin as a whisper. The flower seller shrugged: "Been crying there all morning." Junie couldn't shop another minute. She wrapped the kitten in her scarf and went stall to stall — the cheese lady gave a saucer of cream, the baker warmed a towel by his oven, and the bookseller called the animal rescue. While they waited, half the market gathered around one small gray life. The rescue named him Saturday. Junie visits him monthly — he's enormous now, and still thinks scarves are home.` },

{ id:34, title:"The Man Who Dropped His Photos", theme:"strangers", ages:"7-10", moral:"What's worthless to you may be precious to someone else.",
text:`The wind gusted just as the old man's envelope tore, scattering photographs down the block like leaves. He chased them with a slowness that hurt to watch. Kenji dropped his skateboard and ran — pinning photos under his sneakers, plucking one from a hedge, wading into the fountain for the last one. They dried it on a bench. The photos were gray and ordinary: a woman laughing in a kitchen, over and over. "My wife," the man explained. "The only copies." Kenji, who had four thousand photos on a phone in his pocket, understood suddenly what a treasure could look like. He walked the man home, guarding the envelope like gold.` },

{ id:35, title:"The Great Sock Mystery", theme:"home", ages:"5-8", moral:"Housework can be fun when you make it a game.",
text:`Laundry was the chore Theo hated most — until the evening he invented the Great Sock Mystery. Somewhere in the warm basket, every sock had a missing twin, and Detective Theo was on the case. He interrogated the fitted sheet (it was hiding two suspects). He matched the striped sock to its partner found clinging to a towel — static, the sneakiest culprit of all. His little sister joined as Deputy, folding shirts into "case files." Mom peeked in at the giggling and couldn't believe the empty basket. "Same time next week, detectives?" The deputies saluted with sock puppets.` },

{ id:36, title:"Pancakes for Mom", theme:"home", ages:"6-9", moral:"Giving back to those who care for you feels wonderful.",
text:`Mom had worked late shifts all week, and Saturday morning she slept like a stone. Lily and Max tiptoed to the kitchen with a plan and a recipe card. Max cracked eggs (only one shell rescue needed); Lily flipped pancakes, the first one shaped like a mistake and the fourth one shaped like a heart. They squeezed orange juice, picked a dandelion for a vase, and carried the tray upstairs together, walking like astronauts with precious cargo. Mom woke to the smell and cried a little, which confused Max. "Happy crying," Lily whispered. "It's a real thing." Mom ate every bite, even the mistake pancake. Especially the mistake pancake.` },

{ id:37, title:"The Dish Team", theme:"home", ages:"6-9", moral:"Chores shrink when families work together.",
text:`After the big family dinner, the kitchen looked like a battlefield of pots and gravy. Grandpa rolled up his sleeves, alone at the sink. "Not this year," said Zoe, grabbing a towel. She dried; her cousin stacked; her brother put away; the twins sorted silverware into a clinking assembly line. Grandpa washed and told stories about washing dishes on a navy ship, where the pots were big enough to sit in. Forty minutes of work took twelve. Afterward, the whole Dish Team got cocoa and the good marshmallows. It became the family's favorite tradition — some cousins now argue over who gets to dry.` },

{ id:38, title:"Leo and the Leaf Pile", theme:"home", ages:"5-8", moral:"Work first, play after — and play is sweeter for it.",
text:`Dad handed Leo a rake taller than Leo. The yard was a sea of orange and gold, and Leo's shows were waiting indoors. He groaned — then made a deal with himself: rake first, no peeking at the clock. He raked in rows like Dad taught him, discovering a lost frisbee and a very surprised toad. When the last leaf topped the mountain, Dad appeared with a running start. "You know what a finished leaf pile is for, right?" They leapt in together, twice, three times, leaves in their hair and down their shirts. Raking took an hour. Leo remembers the jumping.` },

{ id:39, title:"The Baby Brother Alarm", theme:"home", ages:"6-9", moral:"Being trusted with responsibility is an honor.",
text:`With Dad on the phone for work and Mom at the store, Rosa was given one job: "If the baby wakes up, come get me instantly." Rosa stationed herself outside the nursery with a book, listening like a guard at a castle. When the first squeak came, she didn't wait for a cry — she knocked on Dad's office door, calm and quick, exactly as asked. Dad reached the crib before the baby even fussed. Later he told Mom the whole story like Rosa had rescued a ship at sea. "She's ready for more jobs," he said. Rosa stood taller all week.` },

{ id:40, title:"Saturday Garage Heroes", theme:"home", ages:"7-10", moral:"Big jobs are just small jobs stacked together.",
text:`The garage had become a cave of mystery boxes, and Mom sighed every time she squeezed past to the car. So the twins declared Operation Garage Hero. Hour one was awful — dust, spiders, a box labeled CABLES?? that was somehow all one tangled cable. But they invented sorting bins: KEEP, GIVE, TOSS, ASK MOM. Progress snowballed. They found the missing beach chairs, Dad's old trophies, and a photo of Mom on a motorcycle ("You WHAT?"). By dinner, the car had a garage again. Mom paid them in pizza and motorcycle stories. Both were worth it.` },

{ id:41, title:"The Garden Waterers", theme:"home", ages:"5-8", moral:"Living things depend on you — show up every day.",
text:`When Papa planted the vegetable garden, Nia begged to help. "Gardens don't want help someday," Papa warned. "They want help every day." Nia promised. Some mornings were easy and some were cartoon mornings, but every day she filled the green can and watered — tomatoes first, they were thirstiest. When the family went to a wedding, she trained the neighbor boy with a hand-drawn map of who drinks most. In August, Nia bit into a tomato she had personally kept alive for ninety days straight. "Well?" asked Papa. Nia chewed thoughtfully. "Tastes like every day."` },

{ id:42, title:"Nana's Button Jar", theme:"home", ages:"6-9", moral:"Time spent helping family is time spent collecting memories.",
text:`Helping Nana tidy her sewing room sounded boring until Aria found the button jar — hundreds of them, glass and brass and one shaped like an anchor. "Every button has a story," Nana said, and she proved it: the anchor came off Grandpa's navy coat; the red glass one from the dress Nana wore when she met him; the tiny pearl from Aria's own baby blanket. They sorted buttons into trays all afternoon, story after story, and the tidying happened almost by accident. Aria now owns the anchor button. She keeps it in a jar she's started herself — one story so far, and counting.` },

{ id:43, title:"The Quiet Helper", theme:"home", ages:"7-10", moral:"The best helpers don't wait to be asked.",
text:`Sunday night, Marcus noticed things nobody asked him to notice: the trash was full, his little sister couldn't reach her cereal for morning, and Mom's lunch bag sat unwashed in the sink. He handled all three without a word and went to bed. Monday morning was the smoothest in family history — and nobody knew why until Mom found the trash empty and did detective math. At dinner she raised her glass. "To whoever oiled the machine." Marcus said nothing, but his ears went red, and his sister pointed at them, cackling. Now they compete: who can help sneakiest. The house has never run better.` },

{ id:44, title:"The Recycling Rangers", theme:"home", ages:"6-9", moral:"Taking care of your home includes taking care of the Earth.",
text:`When Isla learned at school that bottles take 450 years to break down, she came home on a mission. She drafted her brother, and the Recycling Rangers were born: three labeled bins, a chart on the fridge, and a strict inspection of everything headed for the trash. Dad got a warning for a banana peel (compost!). Mom got a medal, drawn in crayon, for rinsing cans unprompted. Each week, the trash bag got smaller and the recycling bin filled. At the end of the month the Rangers calculated they'd saved 212 items from the landfill. "Only 450 years to go," said Isla, satisfied.` },

{ id:45, title:"Muddy Paws and Mop Buckets", theme:"home", ages:"5-8", moral:"If you love your pet, you help with the messy parts too.",
text:`Everyone loved walking Biscuit the dog. Nobody loved what happened after rainy walks — and today Biscuit had found every puddle in the park. He burst through the door and painted the hallway in muddy paw prints before anyone could grab him. "Bath time," Mom sighed, "and floor time." Milo could have vanished to his room; loving the fun parts is easy. Instead he grabbed the dog shampoo while Mom got the mop, and they turned the tub into a bubble storm. Biscuit shook suds onto everything. It took an hour and two towels. Clean dog, clean floor, one very soaked and satisfied boy.` },

{ id:46, title:"The Table Setters' Race", theme:"home", ages:"5-8", moral:"A cheerful attitude makes every job lighter.",
text:`Setting the table was the twins' nightly chore, and their nightly argument — until Aunt Bee visited. She watched them bicker over forks, then pulled out her phone timer. "The world record for perfect table-setting," she announced, completely inventing it, "is two minutes, eleven seconds." The twins' eyes met. The next night they beat it — plates gleaming, napkins folded in triangles, forks aligned like soldiers. Then they beat their OWN record, night after night, checking each other's work like referees. Aunt Bee went home three states away. The record book she started stays on the counter: current champions, one minute, thirty-eight seconds.` },

{ id:47, title:"When the Power Went Out", theme:"home", ages:"7-10", moral:"Families shine brightest when they pull together.",
text:`The storm knocked out the power at dinnertime, and the house went dark and strange. But everyone found a job without being assigned one. Dad lit the camp stove for soup; Mira gathered every candle and flashlight to headquarters (the kitchen table); her brother filled the bathtub with water, like Grandpa always advised; Mom wrapped the baby in the warm blanket. Then, with nothing to plug in, they played shadow puppets and told stories, and the baby laughed at every wolf. When the lights blinked on at nine, the family actually groaned. Now, once a month, they turn the power off on purpose.` },

{ id:48, title:"The Big Move", theme:"home", ages:"7-10", moral:"Helping your family through change helps you too.",
text:`Sana didn't want to move — not one bit. But the boxes came anyway, so she made a choice: if the family was doing this, she'd be useful. She labeled boxes with markers AND drawings (a snoring bed for bedroom, a dancing fork for kitchen). She packed her little brother's toys last and unpacked them first, so the new house would feel like his from minute one. On moving day, the crew called her "the boss" and followed her drawings. That first strange night, it was Sana's system that found the pajamas, the toothbrushes, and the bedtime book. The new house felt less new already — partly because she'd built the map to it.` },

{ id:49, title:"Mia's Chore Chart Invention", theme:"home", ages:"6-9", moral:"Responsibility works best when it's fair and shared.",
text:`The Ruiz kids argued about chores constantly — who did more, who skipped, whose turn it wasn't. Mia, tired of the noise, invented a solution at the kitchen table: a spinning wheel of jobs, built from a pizza box and a brass fastener. Every Sunday, each kid spun. The wheel was random, the wheel was fair, and you could trade — but only trade, never skip. Arguments dropped to nearly zero, mostly replaced by dramatic groans at the wheel's choices. Mom framed the wheel years later when the kids outgrew it. "First invention," reads the label, "of engineer Mia Ruiz."` },

{ id:50, title:"The Best Birthday Gift", theme:"home", ages:"6-10", moral:"The gift of your time and effort means more than anything you can buy.",
text:`Jonah had exactly zero dollars and a problem: Mom's birthday was Sunday. His sister was buying flowers; his brother had chipped in on a scarf. Jonah thought about what Mom actually said she wanted, every single day, usually with a sigh. So Sunday morning, Mom found an envelope: TEN COUPONS, it read. One week of dinner dishes. One garage sweeping. Three "I'll watch the baby, go read your book." Two breakfast-in-beds. And three "anything you ask, no groaning." Mom hugged him longest, which annoyed his siblings until she pointed out something true: "Anyone can spend money. He spent himself."` }
);
